load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/michelangelo-ai/michelangelo/go/cmd/kubeproto/protoc-gen-kubeproto",
    visibility = ["//visibility:private"],
    deps = [
        "//go/api/utils:go_default_library",
        "//go/kubeproto/groupinfo:go_default_library",
        "//go/kubeproto/pboptions:go_default_library",
        "//go/kubeproto/tags:go_default_library",
        "//go/kubeproto/templates:go_default_library",
        "//go/kubeproto/util:go_default_library",
        "//go/kubeproto/yaml:go_default_library",
        "@com_github_dave_dst//:go_default_library",
        "@com_github_dave_dst//decorator:go_default_library",
        "@com_github_gogo_protobuf//proto:go_default_library",
        "@com_github_gogo_protobuf//protoc-gen-gogo/generator:go_default_library",
        "@com_github_gogo_protobuf//protoc-gen-gogo/plugin:go_default_library",
        "@com_github_gogo_protobuf//vanity:go_default_library",
        "@com_github_gogo_protobuf//vanity/command:go_default_library",
        "@org_golang_google_protobuf//compiler/protogen:go_default_library",
        "@org_golang_google_protobuf//proto:go_default_library",
        "@org_golang_google_protobuf//reflect/protoregistry:go_default_library",
        "@org_golang_google_protobuf//types/descriptorpb:go_default_library",
        "@org_golang_google_protobuf//types/pluginpb:go_default_library",
    ],
)

go_binary(
    name = "protoc-gen-kubeproto",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["main_test.go"],
    embed = [":go_default_library"],
    embedsrcs = ["test/expected_go_code.txt"],
    deps = [
        "//proto/test/kubeproto:go_default_library",
        "@com_github_dave_dst//:go_default_library",
        "@com_github_dave_dst//decorator:go_default_library",
        "@com_github_gogo_protobuf//protoc-gen-gogo/plugin:go_default_library",
        "@com_github_gogo_protobuf//types:go_default_library",
        "@com_github_google_go_cmp//cmp:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@io_k8s_api//core/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/api/resource:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
    ],
)
