package main

import (
	"bytes"
	"fmt"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/gogo/protobuf/proto"
	"github.com/gogo/protobuf/protoc-gen-gogo/generator"
	plugingo "github.com/gogo/protobuf/protoc-gen-gogo/plugin"
	"github.com/gogo/protobuf/vanity"
	"github.com/gogo/protobuf/vanity/command"
	"google.golang.org/protobuf/compiler/protogen"
	golangproto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/michelangelo-ai/michelangelo/go/api/utils"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/groupinfo"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/pboptions"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/tags"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/templates"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/yaml"
)

var _reProtoFileName = regexp.MustCompile(`\.pb\.go$`)
var snakeCaseSeparators = regexp.MustCompile("-\\.")

var logger = log.New(os.Stderr, "", 0)

// Call gogo proto to generate go code from protobuf
// The options are chosen to make the generated go code to be compatible
// with k8s "k8s.io/apimachinery/pkg/apis/meta/v1" library (e.g. no Equal function)
func gogoproto(reqData []byte) *plugingo.CodeGeneratorResponse {
	g := generator.New()

	if err := proto.Unmarshal(reqData, g.Request); err != nil {
		g.Error(err, "parsing input proto")
	}

	if len(g.Request.FileToGenerate) == 0 {
		g.Fail("no files to generate")
	}

	req := g.Request

	files := req.GetProtoFile()
	files = vanity.FilterFiles(files, vanity.NotGoogleProtobufDescriptorProto)

	vanity.ForEachFile(files, vanity.TurnOnMarshalerAll)
	vanity.ForEachFile(files, vanity.TurnOnSizerAll)
	vanity.ForEachFile(files, vanity.TurnOnUnmarshalerAll)

	vanity.ForEachFieldInFilesExcludingExtensions(vanity.OnlyProto2(files), vanity.TurnOffNullableForNativeTypesWithoutDefaultsOnly)
	vanity.ForEachFile(files, vanity.TurnOffGoUnrecognizedAll)
	vanity.ForEachFile(files, vanity.TurnOffGoUnkeyedAll)
	vanity.ForEachFile(files, vanity.TurnOffGoSizecacheAll)

	vanity.ForEachFile(files, vanity.TurnOffGoEnumPrefixAll)
	vanity.ForEachFile(files, vanity.TurnOffGoEnumStringerAll)
	vanity.ForEachFile(files, vanity.TurnOnEnumStringerAll)

	vanity.ForEachFile(files, vanity.TurnOnGoStringAll)
	vanity.ForEachFile(files, vanity.TurnOffGoStringerAll)
	vanity.ForEachFile(files, vanity.TurnOnStringerAll)

	return command.Generate(req)
}

// Recursively load message definitions from protobuf.
// In addition to the top level messages provided by the protoMsgs parameter,
// we also need to load the nested messages
// As go does not support nested messages, all the nested protobuf messages are
// translated into package level go structs. So, the go indent names (w/o package
// names) are enough to identify each struct in the file.
func loadProtoMsgs(msgs []*protogen.Message, protoMsgs *map[string]*protogen.Message) {
	for _, msg := range msgs {
		loaded := *protoMsgs
		if _, found := loaded[msg.GoIdent.GoName]; found {
			continue
		} else {
			(*protoMsgs)[msg.GoIdent.GoName] = msg
			loadProtoMsgs(msg.Messages, protoMsgs)
		}
	}
}

// copy the "leading detached comments" from protobuf file to go structs and fields
func copyComments(goDecs *dst.NodeDecs, protoComments *protogen.CommentSet) {
	if len(protoComments.LeadingDetached) > 0 {
		goDecs.Start.Clear()

		for _, comment := range protoComments.LeadingDetached {
			goDecs.Start.Append(comment.String())
			goDecs.Start.Append("\n")
			goDecs.Start.Append("\n")
		}
		goDecs.Start.Append("\n")

		if len(protoComments.Leading) != 0 {
			goDecs.Start.Append(protoComments.Leading.String())
		}
	}
}

func intContains(s []int, e int) bool {
	for _, a := range s {
		if a == e {
			return true
		}
	}
	return false
}

func strContains(s []string, e string) bool {
	for _, a := range s {
		if a == e {
			return true
		}
	}
	return false
}

// Remove the functions of a CRD or CRD-list type generated by gogoproto
// returns the indices of the Decls to be removed in the dstFile
func strip(dstFile *dst.File, name string) []int {
	functions := []string{"GetTypeMeta", "GetMetadata", "GoString", "MarshalToSizedBuffer", "Size", "String", "Unmarshal"}

	var remove []int
	for i, decl := range dstFile.Decls {
		funcDecl, isFuncDecl := decl.(*dst.FuncDecl)
		if !isFuncDecl {
			continue
		}
		receiver := funcDecl.Recv
		if receiver == nil {
			continue
		}
		starType, isStarExpr := receiver.List[0].Type.(*dst.StarExpr)
		if !isStarExpr {
			continue
		}
		if starType.X.(*dst.Ident).Name == name {
			if strContains(functions, funcDecl.Name.Name) || strings.HasPrefix(funcDecl.Name.Name, "Get") {
				remove = append(remove, i)
			}
		}
	}

	return remove
}

// Generate go code for a CRD or CRD list type
func genCRD(crdBuf *bytes.Buffer, filename string, name string, protoComments *protogen.CommentSet, options *pboptions.Options) {
	detachedComments := strings.Builder{}
	for i, c := range protoComments.LeadingDetached {
		if i > 0 {
			detachedComments.WriteString("\n")
		}
		detachedComments.WriteString(c.String())
	}

	if options.Bool("has_resource") {
		typeInfo := struct {
			Name             string
			FileName         string
			DetachedComments string
			Comments         string
		}{name, filename, detachedComments.String(), protoComments.Leading.String()}
		templates.CRD.Execute(crdBuf, typeInfo)
	} else { // crd list
		typeInfo := struct {
			Name             string
			FileName         string
			DetachedComments string
			Comments         string
		}{strings.TrimSuffix(name, "List"), filename, detachedComments.String(), protoComments.Leading.String()}
		templates.CRDList.Execute(crdBuf, typeInfo)
	}
}

// Modify the go file generated by gogoproto:
//  1. Append the "detached leading comments" to structs and fields. These comments are ignored by gogoproto,
//     but are important for controller-gen
//  2. Copy json names from protobufs tag to json tags. Gogoproto does not support json tags for protobuf-3,
//     as the developers of gogoproto think it's impossible to implement the full protobuf-3-to-json spec with
//     json tags. However, k8s controller runtime and k8s client still depend on json tags rather than the new
//     jsonpb API.
//  3. Replace protobuf generated k8s types (gogoproto/github.com/k8s.io/apimachinery/pkg/apis/meta/v1) with
//     genuine k8s types (k8s.io/apimachinery/pkg/apis/meta/v1)
//  4. For CRD and CRD list types, rewrite the structs (embed TypeMetadata and use reference instead of pointers),
//     generate deep copy functions, add controller-tools markers, and register the type to k8s runtime scheme
//  5. If the input file contains michelangelo.api.k8s_api_group_name option, generate group-version info for k8s runtime
func updateGoFile(gofile *plugingo.CodeGeneratorResponse_File, protofile *protogen.File,
	extTypes *protoregistry.Types, gInfo *groupinfo.GroupInfo, processedGoPackageList *map[string]bool,
	allProtoMsgs map[string]*protogen.Message) {
	dstFile, err := decorator.Parse(*gofile.Content)
	if err != nil {
		logger.Panicf("failed to parse gogoproto generated file %v: %v", gofile.GetName(), err)
	}

	// file name in camel case, this string is used by gogo proto in the generated go code
	fileName := strings.TrimSuffix(filepath.Base(protofile.Proto.GetName()), ".proto")
	fileName = generator.CamelCase(snakeCaseSeparators.ReplaceAllString(fileName, "_"))

	// if option group_info set, generate k8s groupversion info file
	options, err := pboptions.ReadOptions(extTypes, protofile.Proto.Options)
	if options != nil && options.Bool("has_group_info") {
		group := options.String("group_info.name")
		version := options.String("group_info.version")

		if group != "" && version != "" {
			var buf bytes.Buffer
			templates.GroupVersion.Execute(&buf, struct {
				Group     string
				Version   string
				GoPackage string
			}{group, version, dstFile.Name.Name})
			updatedContent := buf.String()
			gofile.Content = &updatedContent

			return
		}
	}

	protoMsgs := make(map[string]*protogen.Message)
	loadProtoMsgs(protofile.Messages, &protoMsgs)

	// By default, gogoproto uses the last part of the package path as the package alias. But if multiple packages
	// having the same last part, gogoproto will assign unique names to the packages.
	// For example, if there is another package ends with '/v1', the alias of "k8s.io/apimachinery/pkg/apis/meta/v1"
	// package may become "vv1". This will cause the go code generated from our template to be invalid, if we referred
	// the package as "v1".
	// To avoid this, we explicitly set the alias of "k8s.io/apimachinery/pkg/apis/meta/v1" to "metav1" and set the
	// alias of "github.com/michelangelo-ai/proto/michelangelo/api" to "apipb". The new aliases "metav1" and "apipb"
	// are less likely to conflict with other package aliases
	util.SetPackageAlias(dstFile, "k8s.io/apimachinery/pkg/apis/meta/v1", "metav1")
	util.SetPackageAlias(dstFile, "github.com/michelangelo-ai/proto/michelangelo/api", "apipb")

	var crdFunctionsBuf bytes.Buffer
	hasCRD := false
	var remove []int
	for i, decl := range dstFile.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if isGenDecl {
			// for each "type" declaration
			if genDecl.Tok == token.TYPE {
				typeSpec := genDecl.Specs[0].(*dst.TypeSpec)
				typeName := typeSpec.Name.Name
				protoMsg := protoMsgs[typeName]

				// type struct declaration
				structType, isStruct := typeSpec.Type.(*dst.StructType)
				if isStruct && protoMsg != nil {
					// copy the "leading detached comments" from protobuf file to go structs
					copyComments(genDecl.Decorations(), &protoMsg.Comments)

					// for each field
					for i, field := range structType.Fields.List {
						protoField := protoMsg.Fields[i]

						// copy the "leading detached comments" from protobuf file to go fields
						copyComments(genDecl.Decorations(), &protoField.Comments)

						// copy json names from protobuf tag to json tag
						tag := field.Tag.Value
						jsonTag := tags.GetJSONTag(tag)
						pbTag := tags.GetPBTag(tag)
						if pbTag != nil && jsonTag != nil && jsonTag.Name != "" {
							jsonTag.Name = pbTag.GetJSONName()
						}
						if jsonTag == nil {
							logger.Printf("Empty jsonTag in tag: %v, type %s, field: %v", tag, typeName, field)
						} else {
							tags.SetJSONTag(&field.Tag.Value, jsonTag)
						}
					}

					pbOptions := protoMsg.Desc.Options().(*descriptorpb.MessageOptions)
					options, err := pboptions.ReadOptions(extTypes, pbOptions)
					if err != nil {
						logger.Panicf("Failed to parse the options of message %v: %v", typeName, err)
					}

					if options.Bool("has_resource") || options.Bool("has_resource_list") {
						hasCRD = true

						if gInfo == nil {
							logger.Panic("Found CRD definition in message " + typeName +
								", but cannot find groupversion_info.proto file in the same directory")
						}

						remove = append(remove, i)
						remove = append(remove, strip(dstFile, typeName)...)

						genCRD(&crdFunctionsBuf, fileName, typeName, &protoMsg.Comments, options)
						if options.Bool("has_resource") {
							genCRDIndexedFields(typeName, protoMsg, &crdFunctionsBuf, options, gInfo)
							genCRDRevisionedIndex(typeName, protoMsg, &crdFunctionsBuf, options, gInfo, allProtoMsgs, extTypes)
							genImmutability(typeName, &crdFunctionsBuf, options)
							genCRDObject(typeName, gInfo, &crdFunctionsBuf)
							genCRDBlobFields(typeName, protoMsg, &crdFunctionsBuf, extTypes)
							genCRDEnumTypeFields(typeName, protoMsg, &crdFunctionsBuf, extTypes, processedGoPackageList)
							crdFunctionsBuf.Write([]byte("func init() {\n\tYamlSchemas[\"" + typeName + "\"] = `"))
							yamlStr := string(yaml.GenerateCRDYaml(protofile, extTypes, *gInfo))
							crdFunctionsBuf.Write([]byte(strings.Replace(yamlStr, "`", "`+\"`\"+`", -1)))
							crdFunctionsBuf.Write([]byte("`\n"))
							crdFunctionsBuf.Write([]byte("}"))
						}
					}
				}
			}
		}
	}

	// Remove structs / functions that we don't need or have replaced
	var newDecls []dst.Decl
	for i, d := range dstFile.Decls {
		if !intContains(remove, i) {
			newDecls = append(newDecls, d)
		}
	}
	dstFile.Decls = newDecls

	var buf bytes.Buffer
	decorator.Fprint(&buf, dstFile)
	buf.Write(crdFunctionsBuf.Bytes())
	updatedContent := buf.String()

	if hasCRD {
		updatedContent = strings.Replace(updatedContent, `import (`, "import ("+templates.CRDImports, 1)
	}

	gofile.Content = &updatedContent
}

func genCRDObject(crdName string, gInfo *groupinfo.GroupInfo, crdBuf *bytes.Buffer) {
	typeInfo := struct {
		Group   string
		Version string
		Kind    string
	}{gInfo.Name, gInfo.Version, crdName}
	templates.RegisterCRDObject.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
}

func genImmutability(crdName string, crdBuf *bytes.Buffer, crdOptions *pboptions.Options) {
	crdIsImmutable := false
	if crdOptions.Bool("resource.immutable") {
		crdIsImmutable = true
	}
	typeInfo := struct {
		Name      string
		Immutable bool
	}{crdName, crdIsImmutable}
	templates.CRDImmutability.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
}

func genCRDIndexedFields(crdName string, crdRootMsg *protogen.Message, crdBuf *bytes.Buffer, crdOptions *pboptions.Options,
	groupInfo *groupinfo.GroupInfo) {
	indexedFields := util.ParseIndexedFields(crdRootMsg, crdOptions)

	typeInfo := struct {
		Name string
	}{crdName}
	templates.CRDGetIndexedFieldsHeader.Execute(crdBuf, typeInfo)

	emitIndexedFieldExtraction(crdBuf, indexedFields)
	crdBuf.Write([]byte("\treturn indexedFields\n}\n\n"))

	// Generate IndexesPathToKeyMap for this gvk
	typeInfo2 := struct {
		Group   string
		Version string
		Kind    string
	}{groupInfo.Name, groupInfo.Version, crdName}
	templates.CRDIndexesPathToKeyMapHeader.Execute(crdBuf, typeInfo2)

	for _, field := range indexedFields {
		if field.HasFlag(util.IndexFlagPrimitive) {
			crdBuf.Write([]byte("\tIndexesPathToKeyMap[gvk][\"" + field.ProtoPath + "\"] = \"" + field.Key + "\"\n"))
		} else {
			for _, subField := range field.SubFields {
				crdBuf.Write([]byte("\tIndexesPathToKeyMap[gvk][\"" + subField.ProtoPath + "\"] = \"" + subField.Key + "\"\n"))
			}
		}
	}

	crdBuf.Write([]byte("}\n\n"))
}

// emitIndexedFieldExtraction writes the per-field extraction statements that
// populate a local `indexedFields []storage.IndexedField` slice from `m`. It is
// shared by GetIndexedKeyValuePairs (base table) and GetRevisionedIndexKeyValuePairs
// (revisioned-index sidecars) so enum/composite/nil-check conventions live in one place.
func emitIndexedFieldExtraction(crdBuf *bytes.Buffer, indexedFields []util.IndexedField) {
	declareVar := false
	for _, field := range indexedFields {
		// generate clause that check the message path
		checkMessagePathClause := "\tif m != nil "
		fieldGoPath := "m"
		for idx := 0; idx < len(field.GoPaths); idx++ {
			path := field.GoPaths[idx]
			if path == "Metadata" || path == "TypeMeta" {
				continue
			}
			fieldGoPath += "." + path
			if idx == len(field.GoPaths)-1 && field.HasFlag(util.IndexFlagPrimitive) {
				// Primitive fields are not generated as pointers. Thus, no need to check if it is null.
				break
			}
			if idx == 0 {
				// Spec and Status are not generated as pointers. Thus, no need to check if it is null.
				continue
			}
			checkMessagePathClause += "&& " + fieldGoPath + " != nil "
		}

		if field.HasFlag(util.IndexFlagPrimitive) {
			if !declareVar {
				crdBuf.Write([]byte("\tvar indexedField storage.IndexedField\n\n"))
				declareVar = true
			}
			statement := "\tindexedField.Key = \"" + field.Key + "\"\n"
			crdBuf.Write([]byte(statement))
			crdBuf.Write([]byte(checkMessagePathClause))
			crdBuf.Write([]byte("{\n"))
			statement = "\t\tindexedField.Value = " + fieldGoPath
			if field.HasFlag(util.IndexFlagEnum) {
				statement += ".String()"
			}
			statement += "\n"
			crdBuf.Write([]byte(statement))
			crdBuf.Write([]byte("\t} else {\n"))
			crdBuf.Write([]byte("\t\tindexedField.Value = nil\n"))
			crdBuf.Write([]byte("\t}\n"))
			crdBuf.Write([]byte("\tindexedFields = append(indexedFields, indexedField)\n\n"))
		} else {
			crdBuf.Write([]byte("\t{\n"))
			arrayDeclaration := "\t\tindexedSubFields := make([]storage.IndexedField, " + strconv.Itoa(len(field.SubFields)) + ")\n"
			crdBuf.Write([]byte(arrayDeclaration))
			for i, subField := range field.SubFields {
				statement := "\t\tindexedSubFields[" + strconv.Itoa(i) + "].Key = \"" + subField.Key + "\"\n"
				crdBuf.Write([]byte(statement))
			}
			checkMessagePathClause = "\t" + checkMessagePathClause
			crdBuf.Write([]byte(checkMessagePathClause))
			crdBuf.Write([]byte("{\n"))
			for i, subField := range field.SubFields {
				statement := "\t\t\tindexedSubFields[" + strconv.Itoa(i) + "].Value = " + fieldGoPath + "." + subField.GoPath + "\n"
				crdBuf.Write([]byte(statement))
			}
			crdBuf.Write([]byte("\t\t}\n"))
			crdBuf.Write([]byte("\t\tindexedFields = append(indexedFields, indexedSubFields...)\n"))
			crdBuf.Write([]byte("\t}\n\n"))
		}
	}
}

// wrapperContentPath is where every content-wrapper CRD (Revision, Draft)
// stores its wrapped base resource as a google.protobuf.Any.
const wrapperContentPath = "spec.content"

// genCRDRevisionedIndex generates two methods for a revisioned base type
// (one declaring resource.revisioned_in):
//
//   - GetRevisionedIndexKeyValuePairs: per wrapper kind, the extracted column
//     values for this object.
//   - RevisionedIndexSpecs: per wrapper kind, the wrapper GVK, sidecar table,
//     uid column, and path->column map, with the wrapper kind resolved and
//     validated against allProtoMsgs.
//
// Generated only when the type declares resource.revisioned_in, so only those
// types implement storage.RevisionedIndexable / storage.RevisionedIndexDescribable.
func genCRDRevisionedIndex(crdName string, crdRootMsg *protogen.Message, crdBuf *bytes.Buffer,
	crdOptions *pboptions.Options, gInfo *groupinfo.GroupInfo, allProtoMsgs map[string]*protogen.Message,
	extTypes *protoregistry.Types) {
	revisioned := util.ParseRevisionedIndex(crdRootMsg, crdOptions)
	if revisioned == nil {
		return
	}

	typeInfo := struct {
		Name string
	}{crdName}
	templates.CRDGetRevisionedIndexHeader.Execute(crdBuf, typeInfo)

	// Under mirror-all every wrapper kind carries the same field set, so extract
	// the values once and assign the slice to each kind's map entry (consumers
	// only read it).
	crdBuf.Write([]byte("\tvar indexedFields []storage.IndexedField\n"))
	emitIndexedFieldExtraction(crdBuf, revisioned.Fields)
	for _, kind := range revisioned.Kinds {
		crdBuf.Write([]byte("\tresult[\"" + kind + "\"] = indexedFields\n"))
	}

	crdBuf.Write([]byte("\n\treturn result\n}\n\n"))

	tableBaseName := utils.ToSnakeCase(crdName)
	templates.CRDRevisionedIndexSpecsHeader.Execute(crdBuf, typeInfo)
	for _, kind := range revisioned.Kinds {
		wrapperKindKind := resolveWrapperKind(crdName, kind, allProtoMsgs, extTypes)
		sidecar := util.SidecarFor(tableBaseName, kind)

		crdBuf.Write([]byte("\t\t{\n"))
		crdBuf.Write([]byte("\t\t\tWrapperGVK: schema.GroupVersionKind{Group: \"" + gInfo.Name + "\", Version: \"" +
			gInfo.Version + "\", Kind: \"" + wrapperKindKind + "\"},\n"))
		crdBuf.Write([]byte("\t\t\tWrapperKind: \"" + kind + "\",\n"))
		crdBuf.Write([]byte("\t\t\tContentPath: \"" + wrapperContentPath + "\",\n"))
		crdBuf.Write([]byte("\t\t\tBaseKind: \"" + crdName + "\",\n"))
		crdBuf.Write([]byte("\t\t\tTable: \"" + sidecar.Table + "\",\n"))
		crdBuf.Write([]byte("\t\t\tUIDCol: \"" + sidecar.UIDColumn + "\",\n"))
		crdBuf.Write([]byte("\t\t\tFields: []storage.RevisionedIndexField{\n"))
		for _, field := range revisioned.Fields {
			if field.Flag&util.IndexFlagPrimitive != 0 {
				crdBuf.Write([]byte("\t\t\t\t{Path: \"" + wrapperContentPath + "." + field.ProtoPath + "\", Column: \"" +
					field.Key + "\"},\n"))
			} else {
				for _, subField := range field.SubFields {
					crdBuf.Write([]byte("\t\t\t\t{Path: \"" + wrapperContentPath + "." + subField.ProtoPath + "\", Column: \"" +
						subField.Key + "\"},\n"))
				}
			}
		}
		crdBuf.Write([]byte("\t\t\t},\n"))
		crdBuf.Write([]byte("\t\t},\n"))
	}
	crdBuf.Write([]byte("\t}\n}\n\n"))
}

// resolveWrapperKind converts a revisioned_in kind string (e.g. "revision")
// to the wrapper CRD's Kind ("Revision") and validates, at codegen time,
// that a message by that name actually exists in this compile unit and
// is itself a CRD resource (has_resource).
func resolveWrapperKind(baseCrdName, kind string, allProtoMsgs map[string]*protogen.Message,
	extTypes *protoregistry.Types) string {
	if kind == "" {
		logger.Panicf("Invalid revisioned_in annotation on %v: kind is empty", baseCrdName)
	}
	wrapperKind := utils.ToPascalCase(kind)

	wrapperMsg, ok := allProtoMsgs[wrapperKind]
	if !ok {
		logger.Panicf("Invalid revisioned_in annotation on %v: kind %q does not resolve to any message "+
			"named %q in this compile unit", baseCrdName, kind, wrapperKind)
	}
	wrapperOptions, err := pboptions.ReadOptions(extTypes, wrapperMsg.Desc.Options().(*descriptorpb.MessageOptions))
	if err != nil {
		logger.Panicf("Invalid revisioned_in annotation on %v: failed to read options of wrapper message %v: %v",
			baseCrdName, wrapperKind, err)
	}
	if wrapperOptions == nil || !wrapperOptions.Bool("has_resource") {
		logger.Panicf("Invalid revisioned_in annotation on %v: kind %q resolves to message %v, which is not "+
			"a CRD resource (missing michelangelo.api.resource)", baseCrdName, kind, wrapperKind)
	}
	return wrapperKind
}

func findBlobFields(curMsg *protogen.Message, pathPrefix string, blobFields *[]string,
	processedMessageTypes *map[protogen.GoIdent]bool, extTypes *protoregistry.Types) {
	for _, field := range curMsg.Fields {
		options, err := util.GetFieldOptions(field, extTypes)
		if err != nil {
			logger.Panicf("Failed to parse the options for field %s: %v", field.Desc.TextName(), err)
		}

		newPrefix := strings.Trim(pathPrefix+"."+field.GoName, ".")
		if options.Bool("external_storage") {
			*blobFields = append(*blobFields, newPrefix)
		}

		// Only find blob fields in messages that are declared in the same package (e.g. michelangelo.api.v2)
		if field.Message != nil && field.Message.GoIdent.GoImportPath == curMsg.GoIdent.GoImportPath {
			// Maintain processed message types along the recursion path to avoid getting into infinite recursion
			if _, found := (*processedMessageTypes)[field.Message.GoIdent]; !found {
				(*processedMessageTypes)[field.Message.GoIdent] = true
				findBlobFields(field.Message, newPrefix, blobFields, processedMessageTypes, extTypes)
				delete(*processedMessageTypes, field.Message.GoIdent)
			}
		}
	}
}

func genCRDBlobFields(crdName string, crdMsg *protogen.Message, crdBuf *bytes.Buffer, extTypes *protoregistry.Types) {
	var blobFields []string
	processedMessageTypes := make(map[protogen.GoIdent]bool)
	findBlobFields(crdMsg, "", &blobFields, &processedMessageTypes, extTypes)

	hasBlobFields := len(blobFields) > 0
	typeInfo := struct {
		Name          string
		HasBlobFields bool
	}{crdName, hasBlobFields}
	templates.CRDHasBlobFields.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
	genClearCrdFields(crdName, blobFields, crdBuf)
	templates.CRDFillBlobFields.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
}

func genClearCrdFields(crdName string, blobFields []string, crdBuf *bytes.Buffer) {
	typeInfo := struct {
		Name string
	}{crdName}
	templates.CRDClearBlobFieldsHeader.Execute(crdBuf, typeInfo)

	for _, blobFieldName := range blobFields {
		crdBuf.Write([]byte(fmt.Sprintf("\tif %s {\n", getIfNestedFieldsNotNil(blobFieldName))))
		statement := fmt.Sprintf("\t\tm.%s = nil\n", blobFieldName)
		crdBuf.Write([]byte(statement))
		crdBuf.Write([]byte("\t}\n"))
	}

	crdBuf.Write([]byte("}\n\n"))
}

func getIfNestedFieldsNotNil(blobFieldName string) string {
	paths := strings.Split(blobFieldName, ".")
	statement := ""
	cur := fmt.Sprintf("m.%s", paths[0])
	for i := 1; i < len(paths); i++ {
		cur += fmt.Sprintf(".%s", paths[i])
		// `Spec` and `Status` are not pointer type so we should skip generating `!= nil` statement
		if paths[i] == "Spec" || paths[i] == "Status" {
			continue
		}
		if len(statement) > 0 {
			statement += " && "
		}
		statement += fmt.Sprintf("%s != nil", cur)
	}
	return statement
}

func protoFileName(goFileName string) string {
	return string(_reProtoFileName.ReplaceAll([]byte(goFileName), []byte(".proto")))
}

func generate(reqData []byte) *plugingo.CodeGeneratorResponse {
	// generate go code with gogoproto
	resp := gogoproto(reqData)

	gofiles := make(map[string]*plugingo.CodeGeneratorResponse_File)
	for _, f := range resp.File {
		gofiles[protoFileName(f.GetName())] = f
	}

	// parse protoc request with golang proto
	// golang proto api is easier to use than gogo proto api
	var req pluginpb.CodeGeneratorRequest
	golangproto.Unmarshal(reqData, &req)
	util.ReplaceImportPath(&req)

	// initialize golang proto generator
	gen, err := protogen.Options{}.New(&req)
	if err != nil {
		logger.Panicf("failed to initialize golang proto generator %v", err)
	}

	// Load protobuf extensions from all the imported protobuf files
	extTypes := pboptions.LoadPBExtensions(gen.Files)

	// Load group info
	gInfoMap := groupinfo.Load(gen, extTypes)

	// Every CRD message across the files being generated in this invocation,
	// keyed by Go/proto name (e.g. "Revision"). A base type's revisioned_in[].kind
	// (e.g. "revision") is validated against this set at codegen time.
	allProtoMsgs := make(map[string]*protogen.Message)
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		loadProtoMsgs(f.Messages, &allProtoMsgs)
	}

	processedGoPackageList := make(map[string]bool)
	for _, f := range gen.Files {
		// skip the proto file that don't need to generate go code,
		// such as imported proto files
		if !f.Generate {
			continue
		}
		gInfo, ok := gInfoMap[string(f.Desc.Package())]
		if !ok {
			logger.Panicln(fmt.Sprintf("Failed to derive API group version info for protobuf package: %v. "+
				"Make sure to define groupversion_info.proto for the API group.", f.Desc.Package()))
		}
		updateGoFile(gofiles[f.Proto.GetName()], f, extTypes, gInfo, &processedGoPackageList, allProtoMsgs)
	}
	return resp
}

// findEnumTypeFields recursively finds all enum fields within a given protobuf message and its nested messages.
//
// This function:
// - Traverses through all fields of the given message (`curMsg`).
// - Identifies enum fields and adds them to `enumTypeFields`, ensuring they are not duplicated.
// - Recursively processes nested messages to extract enum fields from them as well.
// - Maintains a record of processed message types and Go package imports to avoid redundant processing.
//
// Args:
//
//	curMsg                 *protogen.Message     - The current protobuf message being analyzed.
//	pathPrefix             string               - The prefix representing the field hierarchy (used for recursion).
//	enumTypeFields             *[]string            - A list to store discovered enum type names.
//	processedMessageTypes  *map[protogen.GoIdent]bool - Tracks already processed message types to prevent cycles.
//	extTypes               *protoregistry.Types - A registry of external types (not used in this function but may be useful for extensions).
//	processedGoPackageList *map[string]bool     - A map to track processed Go packages and prevent duplicate enum field entries.
func findEnumTypeFields(curMsg *protogen.Message, pathPrefix string, enumTypeFields *[]string,
	processedMessageTypes *map[protogen.GoIdent]bool, extTypes *protoregistry.Types, processedGoPackageList *map[string]bool) {
	for _, field := range curMsg.Fields {
		// Check if this field is an enum
		if field.Enum != nil {
			// Only include enums that are declared in the same package (e.g. michelangelo.test.kubeproto)
			// to avoid generating UnmarshalJSON methods for external package enums that are not imported
			if field.Enum.GoIdent.GoImportPath == curMsg.GoIdent.GoImportPath {
				key := fmt.Sprintf("%s.%s", field.Enum.GoIdent.GoImportPath, field.Enum.GoIdent.GoName)
				if _, found := (*processedGoPackageList)[key]; !found {
					(*processedGoPackageList)[key] = true
					newPrefix := strings.Trim(field.Enum.GoIdent.GoName, ".")
					*enumTypeFields = append(*enumTypeFields, newPrefix)
				}
			}
		}
		// Continue processing nested messages
		if field.Message != nil && field.Message.GoIdent.GoImportPath == curMsg.GoIdent.GoImportPath {
			if _, found := (*processedMessageTypes)[field.Message.GoIdent]; !found {
				(*processedMessageTypes)[field.Message.GoIdent] = true
				findEnumTypeFields(field.Message, pathPrefix+"."+field.GoName, enumTypeFields, processedMessageTypes,
					extTypes, processedGoPackageList)
				delete(*processedMessageTypes, field.Message.GoIdent)
			}
		}
	}
}

// genCRDEnumTypeFields generates UnmarshalJSON methods for all enum fields in a given CRD (Custom Resource Definition) message.
//
// This function:
// - Identifies all enum fields within the provided CRD protobuf message (`crdMsg`).
// - Uses `findEnumTypeFields` to traverse nested messages and collect enum field names.
// - Iterates through the discovered enum fields and generates UnmarshalJSON methods using a template.
// - Writes the generated code to the provided buffer (`crdBuf`).
//
// Args:
//
//	crdName                string                    - The name of the CRD being processed.
//	crdMsg                 *protogen.Message         - The protobuf message representing the CRD.
//	crdBuf                 *bytes.Buffer            - The buffer to write the generated code to.
//	extTypes               *protoregistry.Types     - A registry of external types (may be useful for future extensions).
//	processedGoPackageList *map[string]bool         - A map to track processed Go packages to avoid redundant processing.
func genCRDEnumTypeFields(crdName string, crdMsg *protogen.Message, crdBuf *bytes.Buffer, extTypes *protoregistry.Types,
	processedGoPackageList *map[string]bool,
) {
	processedMessageTypes := make(map[protogen.GoIdent]bool)
	enumTypeFields := make([]string, 0)
	// Find all enum fields in the CRD message
	findEnumTypeFields(crdMsg, "", &enumTypeFields, &processedMessageTypes, extTypes, processedGoPackageList)

	// Generate UnmarshalJSON methods for each enum field
	for _, enumTypeName := range enumTypeFields {
		typeInfo := struct {
			EnumTypeName string
		}{
			EnumTypeName: enumTypeName,
		}
		templates.CRDUnmarshalEnum.Execute(crdBuf, typeInfo)
		crdBuf.Write([]byte("\n"))
	}
}

func main() {
	reqData := util.ReadRequest()
	resp := generate(reqData)
	command.Write(resp)
}
