// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package backendsmocks is a generated GoMock package.
package backendsmocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	backends "github.com/michelangelo-ai/michelangelo/go/components/inferenceserver/backends"
	v2 "github.com/michelangelo-ai/michelangelo/proto-go/api/v2"
	zap "go.uber.org/zap"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// CheckModelStatus mocks base method.
func (m *MockBackend) CheckModelStatus(ctx context.Context, logger *zap.Logger, kubeClient client.Client, httpClient *http.Client, apiServerURL, inferenceServerName, namespace, modelName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckModelStatus", ctx, logger, kubeClient, httpClient, apiServerURL, inferenceServerName, namespace, modelName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckModelStatus indicates an expected call of CheckModelStatus.
func (mr *MockBackendMockRecorder) CheckModelStatus(ctx, logger, kubeClient, httpClient, apiServerURL, inferenceServerName, namespace, modelName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckModelStatus", reflect.TypeOf((*MockBackend)(nil).CheckModelStatus), ctx, logger, kubeClient, httpClient, apiServerURL, inferenceServerName, namespace, modelName)
}

// CreateServer mocks base method.
func (m *MockBackend) CreateServer(ctx context.Context, logger *zap.Logger, kubeClient client.Client, inferenceServer *v2.InferenceServer) (*backends.ServerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", ctx, logger, kubeClient, inferenceServer)
	ret0, _ := ret[0].(*backends.ServerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockBackendMockRecorder) CreateServer(ctx, logger, kubeClient, inferenceServer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockBackend)(nil).CreateServer), ctx, logger, kubeClient, inferenceServer)
}

// DeleteServer mocks base method.
func (m *MockBackend) DeleteServer(ctx context.Context, logger *zap.Logger, kubeClient client.Client, inferenceServerName, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, logger, kubeClient, inferenceServerName, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockBackendMockRecorder) DeleteServer(ctx, logger, kubeClient, inferenceServerName, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockBackend)(nil).DeleteServer), ctx, logger, kubeClient, inferenceServerName, namespace)
}

// GetServerStatus mocks base method.
func (m *MockBackend) GetServerStatus(ctx context.Context, logger *zap.Logger, kubeClient client.Client, inferenceServerName, namespace string) (*backends.ServerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerStatus", ctx, logger, kubeClient, inferenceServerName, namespace)
	ret0, _ := ret[0].(*backends.ServerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerStatus indicates an expected call of GetServerStatus.
func (mr *MockBackendMockRecorder) GetServerStatus(ctx, logger, kubeClient, inferenceServerName, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerStatus", reflect.TypeOf((*MockBackend)(nil).GetServerStatus), ctx, logger, kubeClient, inferenceServerName, namespace)
}

// IsHealthy mocks base method.
func (m *MockBackend) IsHealthy(ctx context.Context, logger *zap.Logger, kubeClient client.Client, inferenceServerName, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx, logger, kubeClient, inferenceServerName, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockBackendMockRecorder) IsHealthy(ctx, logger, kubeClient, inferenceServerName, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockBackend)(nil).IsHealthy), ctx, logger, kubeClient, inferenceServerName, namespace)
}
