package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"regexp"
	"strconv"
	"strings"
	"text/template"

	"github.com/michelangelo-ai/michelangelo/go/kubeproto/pboptions"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/templates"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

var validateFieldTmp = template.Must(template.New("validateField").Parse(`
		if {{.Condition}} {
			return status.Error(codes.InvalidArgument, prefix + n + " " + {{.Msg}})
		}`))

var validateMsg = `
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}`

// validateDurationStructural is emitted unconditionally for every google.protobuf.Duration
// field, regardless of whether a bound annotation is present, since a structurally invalid
// Duration (out-of-range seconds/nanos, or seconds/nanos with mismatched signs) is never
// meaningful. Bounds match the google.protobuf.Duration spec
// (https://protobuf.dev/reference/protobuf/google.protobuf/#duration). Declared as local
// constants scoped to this field's block, since multiple .proto files sharing a Go package
// each emit this snippet independently and package-level constants would collide.
var validateDurationStructural = `
		const (
			durationMaxNanos   = 999999999
			durationMinNanos   = -999999999
			durationMaxSeconds = 315576000000
			durationMinSeconds = -315576000000
		)
		if v.GetSeconds() < durationMinSeconds || v.GetSeconds() > durationMaxSeconds {
			return status.Error(codes.InvalidArgument, prefix + n + " " + "seconds out of range")
		}
		if v.GetNanos() < durationMinNanos || v.GetNanos() > durationMaxNanos {
			return status.Error(codes.InvalidArgument, prefix + n + " " + "nanos out of range")
		}
		if (v.GetSeconds() < 0 && v.GetNanos() > 0) || (v.GetSeconds() > 0 && v.GetNanos() < 0) {
			return status.Error(codes.InvalidArgument, prefix + n + " " + "seconds and nanos must have the same sign")
		}`

var validateOneofFmt = `
	if this.Get%s() == nil {
		return status.Error(codes.InvalidArgument, "one field in oneof " + prefix + "%s(%s) must be set")
	}
`

var logger = log.New(os.Stderr, "", 0)

func generateFile(gen *protogen.Plugin, file *protogen.File, extTypes *protoregistry.Types) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + ".pb.validation.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-validation. DO NOT EDIT.")
	g.P(``)
	g.P("package ", file.GoPackageName)
	g.P(`

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa
`)

	for _, msg := range file.Messages {
		var patterns, sets []string
		addPattern := func(p string) string {
			name := msg.GoIdent.GoName + "Pattern" + strconv.Itoa(len(patterns))
			patterns = append(patterns, fmt.Sprintf("var %s = regexp.MustCompile(%s)", name, strconv.Quote(p)))
			return name
		}
		addSet := func(typeName string, setContent string) string {
			name := msg.GoIdent.GoName + "Set" + strconv.Itoa(len(sets))
			sets = append(sets, fmt.Sprintf("var %s = map[%s]bool {%s} ", name, typeName, setContent))
			return name
		}
		validateCode := ""

		pbMsgOptions := msg.Desc.Options().(*descriptorpb.MessageOptions)
		msgOptions, err := pboptions.ReadOptions(extTypes, pbMsgOptions)
		if err != nil {
			compilerErrMsg(msg, err.Error())
		}
		noDefault := false
		if msgOptions.Bool("no_default") {
			noDefault = true
		}

		for _, field := range msg.Fields {
			pbOptions := field.Desc.Options().(*descriptorpb.FieldOptions)
			options, err := pboptions.ReadOptions(extTypes, pbOptions)
			if err != nil {
				compilerErrField(field, err.Error())
			}
			hasValidation := options.Bool("has_validation[0]")

			fieldValidateCode := ""
			itemsValidateCode := ""
			keysValidateCode := ""
			valuesValidateCode := ""
			if !hasValidation {
				if noDefault {
					fieldValidateCode += validateNoDefault(field, nil)
				}
			} else {
				required := false
				optional := false
				for i := 0; ; i++ {
					validationName := fmt.Sprintf("validation[%d]", i)
					if !options.Bool("has_" + validationName) {
						break
					}
					validation := options.GetSubOptions(validationName)
					if validation.Bool("optional") {
						field.Desc.FullName()
						if required {
							compilerErrField(field, "both 'optional' and 'required' are specified")
						}
						if optional {
							compilerErrField(field, "duplicated 'optional' rules")
						}
						optional = true
					}
					if validation.Bool("required") {
						if optional {
							compilerErrField(field, "both 'optional' and 'required' are specified")
						}
						if required {
							compilerErrField(field, "duplicated 'required' rules")
						}
						required = true
						fieldValidateCode += validateNoDefault(field, validation)
					}

					if validation.String("max_items") != "" || validation.String("min_items") != "" {
						fieldValidateCode += validateMaxMinItems(field, validation)
					}

					if validation.Bool("unique_items") {
						fieldValidateCode += validateUniqueItems(field, validation)
					}

					fieldValidateCode += validateSimpleValue(field, validation, addPattern, addSet, fieldTarget)

					if validation.Bool("has_items") {
						if !field.Desc.IsList() {
							compilerErrField(field, fmt.Sprintf("items validation only applies to repeated field"))
						}
						itemsValidateCode += validateSimpleValue(field, validation.GetSubOptions("items"), addPattern, addSet, itemsTarget)
					}
					if validation.Bool("has_keys") {
						if !field.Desc.IsMap() {
							compilerErrField(field, fmt.Sprintf("keys validation only applies to map field"))
						}
						keysValidateCode += validateSimpleValue(field, validation.GetSubOptions("keys"), addPattern, addSet, keysTarget)
					}
					if validation.Bool("has_values") {
						if !field.Desc.IsMap() {
							compilerErrField(field, fmt.Sprintf("values validation only applies to map field"))
						}
						valuesValidateCode += validateSimpleValue(field, validation.GetSubOptions("values"), addPattern, addSet, valuesTarget)
					}
				}

				if noDefault && !optional {
					fieldValidateCode = validateNoDefault(field, nil) + fieldValidateCode
				}
			}
			if field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsMap() && !field.Desc.IsList() {
				fieldValidateCode += validateMsg
			}
			if isDurationKind(field, fieldTarget) {
				fieldValidateCode += validateDurationStructural
			}
			if field.Desc.IsList() && field.Desc.Kind() == protoreflect.MessageKind {
				itemsValidateCode += validateMsg
			}
			if field.Desc.IsList() && isDurationKind(field, itemsTarget) {
				itemsValidateCode += validateDurationStructural
			}
			if field.Desc.IsMap() && field.Desc.MapValue().Kind() == protoreflect.MessageKind {
				valuesValidateCode += validateMsg
			}
			if field.Desc.IsMap() && isDurationKind(field, valuesTarget) {
				valuesValidateCode += validateDurationStructural
			}
			if fieldValidateCode != "" || itemsValidateCode != "" || keysValidateCode != "" || valuesValidateCode != "" {
				if field.Oneof != nil {
					validateCode += fmt.Sprintf("\n\tif f, ok := this.%s.(*%s); ok {"+
						"\n\t\tv := f.%s", field.Oneof.GoName, field.GoIdent.GoName, field.GoName)
				} else {
					if field.Desc.Kind() == protoreflect.MessageKind {
						validateCode += fmt.Sprintf("\n\t{\n\t\tv := this.Get%s()", field.GoName)
					} else {
						validateCode += fmt.Sprintf("\n\t{\n\t\tv := this.%s", field.GoName)
					}
				}
				if fieldValidateCode != "" {
					validateCode += fmt.Sprintf("\n\t\tn := `%s`", field.Desc.TextName())
					validateCode += fieldValidateCode
				}
				if itemsValidateCode != "" {
					itemsValidateCode = indent(itemsValidateCode)
					validateCode += fmt.Sprintf("\n\t\tfor i, v := range v {\n\t\t\tn := `%s[` + strconv.Itoa(i) + `]`\n%s\n\t\t}",
						field.Desc.TextName(), itemsValidateCode)
				}
				if keysValidateCode != "" {
					keysValidateCode = indent(keysValidateCode)
					validateCode += fmt.Sprintf("\n\t\tfor v := range v {\n\t\t\tn := `%s key`\n%s\n\t\t}",
						field.Desc.TextName(), keysValidateCode)
				}
				if valuesValidateCode != "" {
					valuesValidateCode = indent(valuesValidateCode)
					validateCode += fmt.Sprintf("\n\t\tfor k, v := range v {\n\t\t\tn := fmt.Sprintf(`%s[%%v]`, k)\n%s\n\t\t}",
						field.Desc.TextName(), valuesValidateCode)
				}
				validateCode += "\n\t}"
			}
		}
		for _, oneof := range msg.Oneofs {
			pbOptions := oneof.Desc.Options().(*descriptorpb.OneofOptions)
			options, err := pboptions.ReadOptions(extTypes, pbOptions)
			if err != nil {
				logger.Panicf("%s: Error while parsing options of oneof %s.%s: %s",
					oneof.Location.SourceFile, oneof.Parent.Desc.Name(), oneof.Desc.Name(), err.Error())
			}
			if options.Bool("required") || (noDefault && !options.Bool("optional")) {
				fields := ""
				for i, f := range oneof.Fields {
					if i > 0 {
						fields += ","
					}
					fields += f.Desc.TextName()
				}
				validateCode += fmt.Sprintf(validateOneofFmt, oneof.GoName, oneof.Desc.Name(), fields)
			}
		}

		for i := 0; i < len(patterns); i++ {
			g.P(patterns[i])
		}

		for i := 0; i < len(sets); i++ {
			g.P(sets[i])
		}

		// Use the template from the templates package
		var buf bytes.Buffer
		typeName := msg.GoIdent.GoName
		typeNameLower := strings.ToLower(typeName[:1]) + typeName[1:]

		templates.Validation.Execute(&buf, struct {
			TypeName      string
			TypeNameLower string
			ValidateLogic string
		}{
			TypeName:      typeName,
			TypeNameLower: typeNameLower,
			ValidateLogic: validateCode,
		})
		g.P(buf.String())
	}

	return g
}

func compilerErrField(field *protogen.Field, errMsg string) {
	logger.Panicf("%s: Error while parsing validation rules for field %s.%s: %s",
		field.Location.SourceFile, field.Parent.Desc.Name(), field.Desc.TextName(), errMsg)
}

func compilerErrMsg(msg *protogen.Message, errMsg string) {
	logger.Panicf("%s: Error while parsing validation rules for message %s: %s", msg.Location.SourceFile, msg.Desc.Name(), errMsg)
}

func validateField(validation *pboptions.Options, errMsg string, condition string) string {
	if validation != nil && validation.String("msg") != "" {
		errMsg = validation.String("msg")
	}
	var buf bytes.Buffer
	validateFieldTmp.Execute(&buf, struct {
		Condition string
		Msg       string
	}{condition, strconv.Quote(errMsg)})
	return buf.String()
}

func validateNoDefault(field *protogen.Field, validation *pboptions.Options) string {
	condition := ""
	msg := ""
	if field.Desc.IsList() || field.Desc.IsMap() {
		condition = "len(v) == 0"
		msg = "cannot be empty"
	} else {
		switch field.Desc.Kind() {
		case protoreflect.BoolKind:
			return ""
		case protoreflect.EnumKind:
			condition = "v == 0"
			msg = "must be a non-zero value"
		case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Fixed32Kind, protoreflect.Fixed64Kind,
			protoreflect.Sint32Kind, protoreflect.Sint64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
			protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind, protoreflect.FloatKind, protoreflect.DoubleKind:
			condition = "v == 0"
			msg = "must be a non-zero number"
		case protoreflect.StringKind, protoreflect.BytesKind:
			condition = "len(v) == 0"
			msg = "cannot be empty"
		case protoreflect.MessageKind:
			condition = "v == nil"
			msg = "cannot be nil"
		default:
			compilerErrField(field, fmt.Sprintf("unsupported protobuf kind: %v", field.Desc.Kind()))
		}
	}

	return validateField(validation, msg, condition)
}

type targetType int

const (
	fieldTarget targetType = iota
	itemsTarget
	keysTarget
	valuesTarget
)

// validation rules that can be applied to a field, an item in a list, a key in a map, or a value in a map
func validateSimpleValue(field *protogen.Field, validation *pboptions.Options, addPattern func(p string) string, addSet func(typeName string, setContent string) string, target targetType) string {
	validateCode := ""
	if validation.String("max") != "" || validation.String("min") != "" {
		validateCode += validateMaxMin(field, validation, target)
	}

	if validation.String("max_length") != "" || validation.String("min_length") != "" {
		validateCode += validateMaxMinLength(field, validation, target)
	}

	if validation.String("pattern") != "" {
		validateCode += validatePattern(field, validation, addPattern, target, true)
	}

	if validation.String("not_pattern") != "" {
		validateCode += validatePattern(field, validation, addPattern, target, false)
	}

	if validation.Int64("len(in)") > 0 {
		validateCode += validateIn(field, validation, addSet, true, target)
	}

	if validation.Int64("len(not_in)") > 0 {
		validateCode += validateIn(field, validation, addSet, false, target)
	}

	wellKnownFormats := []string{"uuid", "email", "uri", "ipv4", "ipv6", "ip", "hostname", "host_address"}
	for _, format := range wellKnownFormats {
		if validation.Bool(format) {
			validateCode += validateWellKnownFormat(field, validation, format, target)
		}
	}
	return validateCode
}

// getScalarKind returns the Kind of the target; returns 0 if the target is not a scalar value
func getScalarKind(field *protogen.Field, target targetType) protoreflect.Kind {
	switch target {
	case fieldTarget:
		if field.Desc.IsMap() || field.Desc.IsList() {
			return 0 // invalid kind
		}
		return field.Desc.Kind()
	case itemsTarget:
		return field.Desc.Kind()
	case keysTarget:
		return field.Desc.MapKey().Kind()
	case valuesTarget:
		return field.Desc.MapValue().Kind()
	}
	// invalid kind
	return 0
}

// durationMessageFullName is the well-known type name used to recognize google.protobuf.Duration
// fields regardless of which Go protobuf implementation (gogo, golang/protobuf) generated them.
const durationMessageFullName protoreflect.FullName = "google.protobuf.Duration"

// isDurationKind reports whether the resolved field for the given target is a
// google.protobuf.Duration message field.
func isDurationKind(field *protogen.Field, target targetType) bool {
	if getScalarKind(field, target) != protoreflect.MessageKind {
		return false
	}
	switch target {
	case fieldTarget, itemsTarget:
		return field.Desc.Message().FullName() == durationMessageFullName
	case valuesTarget:
		return field.Desc.MapValue().Message().FullName() == durationMessageFullName
	}
	return false
}

func getInt(field *protogen.Field, str string, bits int) string {
	if str == "" {
		return ""
	}
	x, err := strconv.ParseInt(str, 10, bits)
	if err != nil {
		compilerErrField(field, fmt.Sprintf("%s is not a valid %d-bit integer", str, bits))
	}
	return strconv.FormatInt(x, 10)
}

func getUInt(field *protogen.Field, str string, bits int) string {
	if str == "" {
		return ""
	}
	x, err := strconv.ParseUint(str, 10, bits)
	if err != nil {
		compilerErrField(field, fmt.Sprintf("%s is not a valid %d-bit integer", str, bits))
	}
	return strconv.FormatUint(x, 10)
}

func getFloat(field *protogen.Field, str string, bits int) string {
	if str == "" {
		return ""
	}
	_, err := strconv.ParseFloat(str, bits)
	if err != nil {
		compilerErrField(field, fmt.Sprintf("%s is not a valid float number", str))
	}
	return str
}

// minMaxOpsRange returns the min / max operators and the range format string.
func minMaxOpsRange(validation *pboptions.Options) (string, string, string) {
	minOp := ">="
	minBracket := "["
	if validation.Bool("excl_min") {
		minOp = ">"
		minBracket = "("
	}
	maxOp := "<="
	maxBracket := "]"
	if validation.Bool("excl_max") {
		maxOp = "<"
		maxBracket = ")"
	}
	return minOp, maxOp, minBracket + "%v,%v" + maxBracket
}

func validateMaxMin(field *protogen.Field, validation *pboptions.Options, target targetType) string {
	kind := getScalarKind(field, target)
	strMax := validation.String("max")
	strMin := validation.String("min")

	if isDurationKind(field, target) {
		return validateDurationMaxMin(field, validation, strMax, strMin)
	}

	goMax := "" // max in go syntax
	goMin := "" // min in go syntax

	switch kind {
	case protoreflect.EnumKind:
		goType := field.Enum.GoIdent.GoName
		if strMax != "" {
			goMax = fmt.Sprintf("%s(%s)", goType, getInt(field, strMax, 32))
		}
		if strMin != "" {
			goMin = fmt.Sprintf("%s(%s)", goType, getInt(field, strMin, 32))
		}
	case protoreflect.Int32Kind, protoreflect.Fixed32Kind,
		protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		goMax = getInt(field, strMax, 32)
		goMin = getInt(field, strMin, 32)
	case protoreflect.Int64Kind, protoreflect.Fixed64Kind,
		protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		goMax = getInt(field, strMax, 64)
		goMin = getInt(field, strMin, 64)
	case protoreflect.Uint32Kind:
		goMax = getUInt(field, strMax, 32)
		goMin = getUInt(field, strMin, 32)
	case protoreflect.Uint64Kind:
		goMax = getUInt(field, strMax, 64)
		goMin = getUInt(field, strMin, 64)
	case protoreflect.FloatKind:
		goMax = getFloat(field, strMax, 32)
		goMin = getFloat(field, strMin, 32)
	case protoreflect.DoubleKind:
		goMax = getFloat(field, strMax, 64)
		goMin = getFloat(field, strMin, 64)
	default:
		compilerErrField(field, fmt.Sprintf("max / min validation only applies to numeric, enum, or google.protobuf.Duration fields"))
	}

	minOp, maxOp, rangeFmt := minMaxOpsRange(validation)
	condition := ""
	msg := ""
	if goMax != "" && goMin != "" {
		condition = "!(v" + minOp + goMin + " && " + "v" + maxOp + goMax + ")"
		msg = fmt.Sprintf("must be in the range "+rangeFmt, strMin, strMax)
	} else if goMax != "" {
		condition = "!(v" + maxOp + goMax + ")"
		msg = fmt.Sprintf("must be %s %s", maxOp, strMax)
	} else if goMin != "" {
		condition = "!(v" + minOp + goMin + ")"
		msg = fmt.Sprintf("must be %s %s", minOp, strMin)
	} else {
		return ""
	}

	return validateField(validation, msg, condition)
}

// validateDurationMaxMin generates a bound check for google.protobuf.Duration fields.
// min/max are interpreted as seconds, consistent with how they're interpreted as the
// target numeric type for int/float fields.
func validateDurationMaxMin(field *protogen.Field, validation *pboptions.Options, strMax string, strMin string) string {
	goMax := getFloat(field, strMax, 64)
	goMin := getFloat(field, strMin, 64)

	const secondsExpr = "(float64(v.GetSeconds()) + float64(v.GetNanos())/1e9)"

	minOp, maxOp, rangeFmt := minMaxOpsRange(validation)
	condition := ""
	msg := ""
	if goMax != "" && goMin != "" {
		condition = "!(" + secondsExpr + minOp + goMin + " && " + secondsExpr + maxOp + goMax + ")"
		msg = fmt.Sprintf("must be in the range "+rangeFmt+" seconds", strMin, strMax)
	} else if goMax != "" {
		condition = "!(" + secondsExpr + maxOp + goMax + ")"
		msg = fmt.Sprintf("must be %s %s seconds", maxOp, strMax)
	} else if goMin != "" {
		condition = "!(" + secondsExpr + minOp + goMin + ")"
		msg = fmt.Sprintf("must be %s %s seconds", minOp, strMin)
	} else {
		return ""
	}

	return validateField(validation, msg, condition)
}

func validateMaxMinItems(field *protogen.Field, validation *pboptions.Options) string {
	if !field.Desc.IsList() && !field.Desc.IsMap() {
		compilerErrField(field, fmt.Sprintf("max_items / min_items validation only applies to repeated or map fields"))
	}
	strMax := validation.String("max_items")
	strMin := validation.String("min_items")
	goMax := getInt(field, strMax, 32)
	goMin := getInt(field, strMin, 32)
	condition := ""
	msg := ""
	if goMax != "" && goMin != "" {
		condition = "!(len(v) >= " + goMin + " && " + "len(v) <= " + goMax + ")"
		msg = fmt.Sprintf("must contain %s to %s items, inclusive", strMin, strMax)
	} else if goMax != "" {
		condition = "!(len(v) <= " + goMax + ")"
		msg = fmt.Sprintf("must contain no more than %s items", strMax)
	} else if goMin != "" {
		condition = "!(len(v) >= " + goMin + ")"
		msg = fmt.Sprintf("must contain at least %s items", strMin)
	} else {
		return ""
	}

	return validateField(validation, msg, condition)
}

func validateMaxMinLength(field *protogen.Field, validation *pboptions.Options, target targetType) string {
	kind := getScalarKind(field, target)
	if kind != protoreflect.StringKind && kind != protoreflect.BytesKind {
		compilerErrField(field, fmt.Sprintf("max_length / min_length validation only applies to string or bytes fields"))
	}
	strMax := validation.String("max_length")
	strMin := validation.String("min_length")
	goMax := getInt(field, strMax, 32)
	goMin := getInt(field, strMin, 32)
	condition := ""
	msg := ""
	elements := "characters"
	if kind == protoreflect.BytesKind {
		elements = "bytes"
	}
	if goMax != "" && goMin != "" {
		condition = "!(len(v) >= " + goMin + " && " + "len(v) <= " + goMax + ")"
		msg = fmt.Sprintf("must be %s to %s %s long, inclusive", strMin, strMax, elements)
	} else if goMax != "" {
		condition = "!(len(v) <= " + goMax + ")"
		msg = fmt.Sprintf("must be no more than %s %s long", strMax, elements)
	} else if goMin != "" {
		condition = "!(len(v) >= " + goMin + ")"
		msg = fmt.Sprintf("must be at least %s %s long", strMin, elements)
	} else {
		return ""
	}

	return validateField(validation, msg, condition)
}

func validatePattern(field *protogen.Field, validation *pboptions.Options, addPattern func(string) string, target targetType, positive bool) string {
	kind := getScalarKind(field, target)
	if kind != protoreflect.StringKind {
		compilerErrField(field, fmt.Sprintf("pattern validation only applies to string or bytes fields"))
	}
	var patternStr string
	if positive {
		patternStr = validation.String("pattern")
	} else {
		patternStr = validation.String("not_pattern")
	}
	_, err := regexp.Compile(patternStr)
	if err != nil {
		compilerErrField(field, "error when parsing pattern: "+err.Error())
	}

	p := addPattern("^" + patternStr + "$")
	var condition string
	var msg string
	if positive {
		condition = fmt.Sprintf("!%s.MatchString(v)", p)
		msg = "must match regular expression pattern /" + patternStr + "/"
	} else {
		condition = fmt.Sprintf("%s.MatchString(v)", p)
		msg = "must not match regular expression pattern /" + patternStr + "/"
	}

	return validateField(validation, msg, condition)
}

func validateUniqueItems(field *protogen.Field, validation *pboptions.Options) string {
	compilerErrField(field, "unique validation has not been implemented")
	return ""
}

func validateIn(field *protogen.Field, validation *pboptions.Options, addSet func(string, string) string, in bool, target targetType) string {
	kind := getScalarKind(field, target)
	if kind == 0 || kind == protoreflect.BytesKind || kind == protoreflect.MessageKind {
		compilerErrField(field, fmt.Sprintf("in / not_in validation only applies to numeric, string, or enum fields"))
	}

	key := "in"
	if !in {
		key = "not_in"
	}
	length := int(validation.Int64(fmt.Sprintf("len(%s)", key)))
	listStr := make([]string, length)
	for i := 0; i < length; i++ {
		listStr[i] = validation.String(fmt.Sprintf("%s[%d]", key, i))
	}

	msg := "must be "
	if length > 1 {
		msg += "either "
	}
	if key != "in" {
		msg = "cannot be "
	}
	for i := 0; i < length; i++ {
		if i != 0 {
			msg += ", "
		}
		if length > 1 && i == length-1 {
			if key == "in" {
				msg += "or "
			} else {
				msg += "nor "
			}
		}
		str := listStr[i]
		if kind == protoreflect.StringKind {
			str = strconv.Quote(str)
		}
		msg += str
	}

	listGo := make([]string, length)
	goType := ""
	switch kind {
	case protoreflect.EnumKind:
		goType = field.Enum.GoIdent.GoName
		for i := 0; i < length; i++ {
			listGo[i] = fmt.Sprintf("%s(%s)", goType, getInt(field, listStr[i], 32))
		}
	case protoreflect.Int32Kind, protoreflect.Fixed32Kind,
		protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		goType = "int32"
		for i := 0; i < length; i++ {
			listGo[i] = getInt(field, listStr[i], 32)
		}
	case protoreflect.Int64Kind, protoreflect.Fixed64Kind,
		protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		goType = "int64"
		for i := 0; i < length; i++ {
			listGo[i] = getInt(field, listStr[i], 64)
		}
	case protoreflect.Uint32Kind:
		goType = "uint32"
		for i := 0; i < length; i++ {
			listGo[i] = getUInt(field, listStr[i], 32)
		}
	case protoreflect.Uint64Kind:
		goType = "uint64"
		for i := 0; i < length; i++ {
			listGo[i] = getUInt(field, listStr[i], 64)
		}
	case protoreflect.FloatKind:
		goType = "float32"
		for i := 0; i < length; i++ {
			listGo[i] = getFloat(field, listStr[i], 32)
		}
	case protoreflect.DoubleKind:
		goType = "float64"
		for i := 0; i < length; i++ {
			listGo[i] = getFloat(field, listStr[i], 64)
		}
	case protoreflect.StringKind:
		goType = "string"
		for i := 0; i < length; i++ {
			listGo[i] = strconv.Quote(listStr[i])
		}
	default:
		compilerErrField(field, fmt.Sprintf("in / not_in validation only applies to numeric, string, or enum fields"))
	}
	setStr := ""
	for i := 0; i < length; i++ {
		setStr += "\n\t" + listGo[i] + ": true,"
	}
	setStr += "\n"

	setName := addSet(goType, setStr)
	condition := "!" + setName + "[v]"
	if key == "not_in" {
		condition = setName + "[v]"
	}

	return validateField(validation, msg, condition)
}

func validateWellKnownFormat(field *protogen.Field, validation *pboptions.Options, format string, target targetType) string {
	kind := getScalarKind(field, target)
	if kind != protoreflect.StringKind {
		compilerErrField(field, fmt.Sprintf("%s validation only applies to string fields", format))
	}
	condition := ""
	msg := ""
	switch format {
	case "uuid":
		condition = "_, err := uuid.Parse(v); err != nil"
		msg = "must be a valid UUID"
	case "email":
		condition = "_, err := mail.ParseAddress(v); err != nil"
		msg = "must be a valid email address"
	case "uri":
		condition = "_, err := url.ParseRequestURI(v); err != nil"
		msg = "must be a valid URI"
	case "ip":
		condition = "ip := net.ParseIP(v); ip == nil"
		msg = "must be a valid IP address"
	case "ipv4":
		condition = "ip := net.ParseIP(v); ip == nil || strings.Contains(v, \":\")"
		msg = "must be a valid IPv4 address"
	case "ipv6":
		condition = "ip := net.ParseIP(v); ip == nil || !strings.Contains(v, \":\")"
		msg = "must be a valid IPv6 address"
	default:
		compilerErrField(field, "not implemented")
	}

	return validateField(validation, msg, condition)
}

var lineRegex = regexp.MustCompile(`(?m)^.*$`)

func indent(s string) string {
	return lineRegex.ReplaceAllString(s, "\t$0")
}

func generate(reqData []byte) *pluginpb.CodeGeneratorResponse {
	gen, extTypes, err := util.GetPluginAndExtensions(reqData, false)
	if err != nil {
		logger.Panic(err)
	}

	for _, f := range gen.Files {
		// skip the proto file that don't need to generate go code,
		// such as imported proto files
		if !f.Generate {
			continue
		}
		generateFile(gen, f, extTypes)
	}

	return gen.Response()
}

func main() {
	reqData := util.ReadRequest()
	resp := generate(reqData)
	util.WriteResponse(resp)
}
