apiVersion: michelangelo.api/v2
kind: InferenceServer
metadata:
  name: inference-server-example
  namespace: default
  labels:
    app: inference-server
spec:
  tenancyType: TENANCY_TYPE_DEDICATED
  backendType: BACKEND_TYPE_TRITON
  ownerSpec:
    tier: 1
  initSpec:
    resourceSpec:
      cpu: 2
      memory: "4Gi"
    servingSpec:
      version: "latest"
    numInstances: 1
  decomSpec:
    decommission: false
  owner:
    name: "user-example"
  clusterTargets:
  - clusterId: michelangelo-sandbox
    kubernetes:
      host: https://kubernetes.default.svc
      port: "443"
      tokenTag: cluster-michelangelo-sandbox-is-token
      caDataTag: cluster-michelangelo-sandbox-ca-data
