apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  namespace: "ma-dev-test"
  name: "hello-world"
  annotations:
    michelangelo/uniflow-image: michelangelo-hello-world:local
spec:
  type: "PIPELINE_TYPE_TRAIN"
  manifest:
    filePath: examples.hello_world.hello_world
