{{- if and .Values.envoy.enabled .Values.envoy.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "envoy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "michelangelo.componentLabels" (dict "context" . "component" "envoy") | nindent 4 }}
  {{- with merge (.Values.envoy.ingress.annotations | default dict) .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.envoy.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.envoy.ingress.tls }}
  tls:
    {{- range .Values.envoy.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.envoy.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "michelangelo.componentFullname" (dict "context" $ "component" "envoy") }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
