{{- if .Values.envoy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "envoy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "michelangelo.componentLabels" (dict "context" . "component" "envoy") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "michelangelo.componentSelectorLabels" (dict "context" . "component" "envoy") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "michelangelo.componentSelectorLabels" (dict "context" . "component" "envoy") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "michelangelo.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: envoy
          image: {{ .Values.images.envoy }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["-c", "/etc/envoy/envoy.yaml"]
          ports:
            - name: http
              containerPort: {{ .Values.envoy.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
            - name: descriptors
              mountPath: /etc/envoy-descriptors/descriptors.pb
              subPath: descriptors.pb
          {{- with (or .Values.envoy.resources .Values.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "envoy-config") }}
        - name: descriptors
          configMap:
            name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "envoy-descriptors") }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
