{{- if and .Values.ui.enabled .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "ui") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "michelangelo.componentLabels" (dict "context" . "component" "ui") | nindent 4 }}
  {{- with merge (.Values.ui.ingress.annotations | default dict) .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ui.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{- toYaml .Values.ui.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ required "ui.ingress.hostname is required when ui.ingress.enabled=true" .Values.ui.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "ui") }}
                port:
                  name: http
{{- end }}
