// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/test/kubeproto/test_draft.proto

package kubeproto

import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/storage"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TestDraftSpec struct {
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *TestDraftSpec) Reset()      { *m = TestDraftSpec{} }
func (*TestDraftSpec) ProtoMessage() {}
func (*TestDraftSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9e51616fdb8a5, []int{0}
}
func (m *TestDraftSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestDraftSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestDraftSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestDraftSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDraftSpec.Merge(m, src)
}
func (m *TestDraftSpec) XXX_Size() int {
	return m.Size()
}
func (m *TestDraftSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDraftSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TestDraftSpec proto.InternalMessageInfo

func (m *TestDraftSpec) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TestDraftStatus struct {
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *TestDraftStatus) Reset()      { *m = TestDraftStatus{} }
func (*TestDraftStatus) ProtoMessage() {}
func (*TestDraftStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9e51616fdb8a5, []int{1}
}
func (m *TestDraftStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestDraftStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestDraftStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestDraftStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDraftStatus.Merge(m, src)
}
func (m *TestDraftStatus) XXX_Size() int {
	return m.Size()
}
func (m *TestDraftStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDraftStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TestDraftStatus proto.InternalMessageInfo

func (m *TestDraftStatus) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TestDraft) Reset()      { *m = TestDraft{} }
func (*TestDraft) ProtoMessage() {}
func (*TestDraft) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9e51616fdb8a5, []int{2}
}
func (m *TestDraft) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestDraft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestDraft.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestDraft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDraft.Merge(m, src)
}
func (m *TestDraft) XXX_Size() int {
	return m.Size()
}
func (m *TestDraft) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDraft.DiscardUnknown(m)
}

var xxx_messageInfo_TestDraft proto.InternalMessageInfo

func (m *TestDraftList) Reset()      { *m = TestDraftList{} }
func (*TestDraftList) ProtoMessage() {}
func (*TestDraftList) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9e51616fdb8a5, []int{3}
}
func (m *TestDraftList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestDraftList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestDraftList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestDraftList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDraftList.Merge(m, src)
}
func (m *TestDraftList) XXX_Size() int {
	return m.Size()
}
func (m *TestDraftList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDraftList.DiscardUnknown(m)
}

var xxx_messageInfo_TestDraftList proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TestDraftSpec)(nil), "michelangelo.test.kubeproto.TestDraftSpec")
	proto.RegisterType((*TestDraftStatus)(nil), "michelangelo.test.kubeproto.TestDraftStatus")
	proto.RegisterType((*TestDraft)(nil), "michelangelo.test.kubeproto.TestDraft")
	proto.RegisterType((*TestDraftList)(nil), "michelangelo.test.kubeproto.TestDraftList")
}

func init() {
	proto.RegisterFile("michelangelo/test/kubeproto/test_draft.proto", fileDescriptor_53b9e51616fdb8a5)
}

var fileDescriptor_53b9e51616fdb8a5 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x67, 0x9a, 0x6e, 0xed, 0x4e, 0x11, 0x21, 0x78, 0x08, 0x15, 0x86, 0x92, 0x83, 0x56,
	0x29, 0x33, 0xb6, 0x7a, 0x90, 0x2a, 0x82, 0xa5, 0x27, 0xad, 0x08, 0xb1, 0x27, 0x2f, 0x65, 0x36,
	0xfb, 0x4c, 0xc7, 0x34, 0xc9, 0x90, 0x79, 0x5b, 0xd8, 0x9b, 0xf8, 0x09, 0xfc, 0x2a, 0x7e, 0x0b,
	0x8f, 0x7b, 0xec, 0xd1, 0xcd, 0x5e, 0x04, 0x2f, 0x3d, 0x7b, 0x92, 0x99, 0x6c, 0xd7, 0xad, 0x82,
	0xe4, 0xe0, 0x29, 0x79, 0xef, 0xfd, 0xdf, 0x8f, 0xff, 0xfb, 0x0f, 0xdb, 0x29, 0x74, 0x7a, 0x0a,
	0x67, 0xaa, 0xcc, 0xe0, 0xac, 0x92, 0x08, 0x16, 0x65, 0x3e, 0x1a, 0x80, 0xa9, 0x2b, 0x6c, 0xcb,
	0x93, 0x61, 0xad, 0xde, 0xa3, 0xf0, 0x8d, 0xf0, 0xce, 0xb2, 0x5a, 0xb8, 0xb1, 0x58, 0xa8, 0x37,
	0x1f, 0xe7, 0x4f, 0xac, 0xd0, 0x95, 0x54, 0x46, 0x17, 0x2a, 0x3d, 0xd5, 0x25, 0xd4, 0x63, 0x69,
	0xf2, 0xcc, 0x35, 0xac, 0x2c, 0x00, 0x95, 0x3c, 0xdf, 0x95, 0x19, 0x94, 0x50, 0x2b, 0x84, 0x61,
	0x8b, 0xdc, 0xe4, 0xd7, 0x0c, 0x28, 0xa3, 0x65, 0x65, 0x50, 0x57, 0xa5, 0x6d, 0xe7, 0xf1, 0x7d,
	0x76, 0xf3, 0x18, 0x2c, 0x1e, 0x3a, 0x17, 0x6f, 0x0d, 0xa4, 0x61, 0xc4, 0x6e, 0xa4, 0x55, 0x89,
	0x50, 0x62, 0x44, 0xb7, 0xe8, 0x76, 0x3f, 0xb9, 0x2a, 0xe3, 0x7b, 0xec, 0xd6, 0x6f, 0x29, 0x2a,
	0x1c, 0xd9, 0xf0, 0x36, 0xeb, 0xa5, 0xd5, 0x68, 0x2e, 0xed, 0x25, 0x6d, 0x11, 0x7f, 0x59, 0x61,
	0xfd, 0x85, 0x32, 0x7c, 0xc5, 0xfa, 0x38, 0x36, 0x70, 0xe2, 0x1c, 0x7a, 0xdd, 0xc6, 0x9e, 0x10,
	0xed, 0x2d, 0x62, 0xf9, 0x16, 0x61, 0xf2, 0xcc, 0x35, 0xac, 0x70, 0x4a, 0x71, 0xbe, 0x2b, 0x8e,
	0xc7, 0x06, 0x5e, 0x03, 0xaa, 0x64, 0x1d, 0xe7, 0x7f, 0xe1, 0x11, 0x5b, 0x77, 0xd3, 0xa1, 0x42,
	0x15, 0xad, 0x78, 0xd6, 0xc3, 0x6e, 0xac, 0x37, 0x83, 0x0f, 0x90, 0x62, 0x4b, 0xbb, 0x22, 0x84,
	0xcf, 0xd9, 0xaa, 0x35, 0x90, 0x46, 0x81, 0x27, 0x3d, 0x10, 0xff, 0x88, 0x5f, 0x5c, 0x4b, 0x29,
	0xf1, 0x7b, 0xe1, 0x21, 0x5b, 0xb3, 0x3e, 0x88, 0x68, 0xd5, 0x13, 0x76, 0x3a, 0x12, 0xfc, 0x4e,
	0x32, 0xdf, 0xdd, 0x0f, 0x3e, 0x1d, 0x90, 0xf8, 0x07, 0x5d, 0x7a, 0x88, 0x23, 0x6d, 0xff, 0x73,
	0x6e, 0x2f, 0xff, 0xca, 0xad, 0x23, 0xcb, 0x59, 0xf9, 0x23, 0xb5, 0x67, 0xac, 0xa7, 0x11, 0x0a,
	0x1b, 0x05, 0x5b, 0xc1, 0xf6, 0xc6, 0xde, 0xdd, 0x6e, 0x47, 0x27, 0xed, 0xd2, 0x7e, 0xf0, 0xf3,
	0x05, 0x39, 0x78, 0x3a, 0x99, 0x72, 0x72, 0x31, 0xe5, 0xe4, 0x72, 0xca, 0xe9, 0xc7, 0x86, 0xd3,
	0xaf, 0x0d, 0xa7, 0x93, 0x86, 0xd3, 0x6f, 0x0d, 0xa7, 0xdf, 0x1b, 0x4e, 0x2e, 0x1b, 0x4e, 0x3f,
	0xcf, 0x38, 0x99, 0xcc, 0x38, 0xb9, 0x98, 0x71, 0xf2, 0xae, 0xbf, 0x40, 0x0e, 0xd6, 0xfc, 0xe7,
	0xd1, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x58, 0x18, 0x19, 0x5c, 0x03, 0x00, 0x00,
}

func (this *TestDraftSpec) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.TestDraftSpec{")
	s = append(s, "Content: "+fmt.Sprintf("%#v", this.Content)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TestDraftStatus) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.TestDraftStatus{")
	s = append(s, "Count: "+fmt.Sprintf("%#v", this.Count)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTestDraft(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TestDraftSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestDraftSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestDraftSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintTestDraft(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TestDraftStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestDraftStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestDraftStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintTestDraft(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TestDraft) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestDraft) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestDraftList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestDraftList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func encodeVarintTestDraft(dAtA []byte, offset int, v uint64) int {
	offset -= sovTestDraft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TestDraftSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovTestDraft(uint64(l))
	}
	return n
}

func (m *TestDraftStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovTestDraft(uint64(m.Count))
	}
	return n
}

func sovTestDraft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTestDraft(x uint64) (n int) {
	return sovTestDraft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TestDraftSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestDraftSpec{`,
		`Content:` + fmt.Sprintf("%v", this.Content) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TestDraftStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestDraftStatus{`,
		`Count:` + fmt.Sprintf("%v", this.Count) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTestDraft(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TestDraftSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestDraft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestDraftSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestDraftSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestDraft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTestDraft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TestDraftStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestDraft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestDraftStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestDraftStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTestDraft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTestDraft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTestDraft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTestDraft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTestDraft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTestDraft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTestDraft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTestDraft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTestDraft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTestDraft = fmt.Errorf("proto: unexpected end of group")
)

type TestDraft struct {
	metav1.TypeMeta   `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// Spec of the desired behavior of the TestDraft.
	Spec TestDraftSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Most recently observed status of the TestDraft.
	Status TestDraftStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *TestDraft) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *TestDraft) GetMetadata() *metav1.ObjectMeta {
	return &m.ObjectMeta
}

func (m *TestDraft) GetSpec() TestDraftSpec {
	if m != nil {
		return m.Spec
	}
	return TestDraftSpec{}
}

func (m *TestDraft) GetStatus() TestDraftStatus {
	if m != nil {
		return m.Status
	}
	return TestDraftStatus{}
}

func (m *TestDraft) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestDraft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestDraft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestDraft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestDraft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TestDraft) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovTestDraft(uint64(l))
	l = m.ObjectMeta.Size()
	n += 1 + l + sovTestDraft(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovTestDraft(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovTestDraft(uint64(l))
	return n
}

func (this *TestDraft) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestDraft{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "metav1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "TestDraftSpec", "TestDraftSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "TestDraftStatus", "TestDraftStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}

func (m *TestDraft) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestDraft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestDraft: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestDraft: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestDraft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTestDraft
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTestDraft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

/* As gogo proto's jsonpb library does not support marshal and unmarshal for
   inline field (TypeMeta), we work around this by implementing the
   marshal and unmarshal functions for Spec and Status respectively. */
func (m *TestDraftSpec) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *TestDraftSpec) UnmarshalJSON(b []byte) error {
	err := (&jsonpb.Unmarshaler{
	  AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
	  AnyResolver: &util.GenericResolver{},
	}).Unmarshal(bytes.NewReader(b), m)
	if err == nil {
        return nil
	}

    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

	visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
	util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
	if len(paths) > 0 {
	    b, err = util.ApplyInlineFields(b, paths)
	}
    type Alias TestDraftSpec
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (m *TestDraftStatus) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *TestDraftStatus) UnmarshalJSON(b []byte) error {
    err := (&jsonpb.Unmarshaler{
      AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
      AnyResolver: &util.GenericResolver{},
    }).Unmarshal(bytes.NewReader(b), m)
    if err == nil {
        return nil
    }
    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

    visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
    util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
    if len(paths) > 0 {
        b, err = util.ApplyInlineFields(b, paths)
    }
    type Alias TestDraftStatus
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (in *TestDraft) DeepCopy() *TestDraft {
	if in == nil {
		return nil
	}
	out := new(TestDraft)
	in.DeepCopyInto(out)
	return out
}

func (in *TestDraft) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TestDraft) DeepCopyInto(out *TestDraft) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *proto.Clone(&in.Spec).(*TestDraftSpec)
	out.Status = *proto.Clone(&in.Status).(*TestDraftStatus)
}

func init() {
	SchemeBuilder.Register(&TestDraft{})
}

func (m *TestDraft) GetIndexedKeyValuePairs() ([]storage.IndexedField){
	var indexedFields []storage.IndexedField
	return indexedFields
}


func init() {
	gvk := schema.GroupVersionKind{
		Group: "michelangelo.api",
		Version: "v2",
		Kind: "TestDraft",
	}
	IndexesPathToKeyMap[gvk] = make(map[string]string)

	// default index
	IndexesPathToKeyMap[gvk]["metadata.namespace"] = "namespace"
	IndexesPathToKeyMap[gvk]["metadata.name"] = "name"
}

func (m *TestDraft) IsImmutableKind() bool {

	return false
}

func init() {
	CrdObjects["TestDraft"] = &TestDraft{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "michelangelo.api/v2",
			Kind: "TestDraft",
		},
	}
}

func (m *TestDraft) HasBlobFields() bool {
	return false
}

func (m *TestDraft) ClearBlobFields() {
}

func (m *TestDraft) FillBlobFields(object k8sruntime.Object) {
	other := object.(*TestDraft)
	m.Spec = other.Spec
	m.Status = other.Status
}

func init() {
	YamlSchemas["TestDraft"] = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: testdrafts.michelangelo.api
spec:
  group: michelangelo.api
  names:
    kind: TestDraft
    listKind: TestDraftList
    plural: testdrafts
    singular: testdraft
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              content:
                type: string
            type: object
          status:
            properties:
              count:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
`
}

type TestDraftList struct {
	metav1.TypeMeta `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ListMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// A list of TestDraft
	Items []TestDraft `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
}

func (m *TestDraftList) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *TestDraftList) GetMetadata() *metav1.ListMeta {
	return &m.ListMeta
}

func (m *TestDraftList) GetItems() []TestDraft {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TestDraftList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTestDraft(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestDraft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestDraft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TestDraftList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovTestDraft(uint64(l))
	l = m.ListMeta.Size()
	n += 1 + l + sovTestDraft(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovTestDraft(uint64(l))
		}
	}
	return n
}

func (this *TestDraftList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]TestDraft{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "TestDraft", "TestDraft", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&TestDraftList{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "metav1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}

func (m *TestDraftList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestDraft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestDraftList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestDraftList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestDraft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestDraft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestDraft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, TestDraft{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestDraft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTestDraft
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTestDraft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (in *TestDraftList) DeepCopy() *TestDraftList {
	if in == nil {
		return nil
	}
	out := new(TestDraftList)
	in.DeepCopyInto(out)
	return out
}

func (in *TestDraftList) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TestDraftList) DeepCopyInto(out *TestDraftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestDraft, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func init() {
	SchemeBuilder.Register(&TestDraftList{})
}
