// Code generated by protoc-gen-validation. DO NOT EDIT.

package kubeproto

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// testDraftSpecValidateExt is an extension hook for additional validation logic
var testDraftSpecValidateExt func(*TestDraftSpec, string) error

func (this *TestDraftSpec) Validate(prefix string) error {

	// Call extension validation if registered
	if testDraftSpecValidateExt != nil {
		if err := testDraftSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftSpecValidateExt registers an extension validation function
func RegisterTestDraftSpecValidateExt(f func(*TestDraftSpec, string) error) {
	testDraftSpecValidateExt = f
}

// testDraftStatusValidateExt is an extension hook for additional validation logic
var testDraftStatusValidateExt func(*TestDraftStatus, string) error

func (this *TestDraftStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if testDraftStatusValidateExt != nil {
		if err := testDraftStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftStatusValidateExt registers an extension validation function
func RegisterTestDraftStatusValidateExt(f func(*TestDraftStatus, string) error) {
	testDraftStatusValidateExt = f
}

// testDraftValidateExt is an extension hook for additional validation logic
var testDraftValidateExt func(*TestDraft, string) error

func (this *TestDraft) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testDraftValidateExt != nil {
		if err := testDraftValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftValidateExt registers an extension validation function
func RegisterTestDraftValidateExt(f func(*TestDraft, string) error) {
	testDraftValidateExt = f
}

// testDraftListValidateExt is an extension hook for additional validation logic
var testDraftListValidateExt func(*TestDraftList, string) error

func (this *TestDraftList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if testDraftListValidateExt != nil {
		if err := testDraftListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftListValidateExt registers an extension validation function
func RegisterTestDraftListValidateExt(f func(*TestDraftList, string) error) {
	testDraftListValidateExt = f
}
