// Code generated by protoc-gen-validation. DO NOT EDIT.

package kubeproto

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// testWrapperSpecValidateExt is an extension hook for additional validation logic
var testWrapperSpecValidateExt func(*TestWrapperSpec, string) error

func (this *TestWrapperSpec) Validate(prefix string) error {

	// Call extension validation if registered
	if testWrapperSpecValidateExt != nil {
		if err := testWrapperSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperSpecValidateExt registers an extension validation function
func RegisterTestWrapperSpecValidateExt(f func(*TestWrapperSpec, string) error) {
	testWrapperSpecValidateExt = f
}

// testWrapperStatusValidateExt is an extension hook for additional validation logic
var testWrapperStatusValidateExt func(*TestWrapperStatus, string) error

func (this *TestWrapperStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if testWrapperStatusValidateExt != nil {
		if err := testWrapperStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperStatusValidateExt registers an extension validation function
func RegisterTestWrapperStatusValidateExt(f func(*TestWrapperStatus, string) error) {
	testWrapperStatusValidateExt = f
}

// testWrapperValidateExt is an extension hook for additional validation logic
var testWrapperValidateExt func(*TestWrapper, string) error

func (this *TestWrapper) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testWrapperValidateExt != nil {
		if err := testWrapperValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperValidateExt registers an extension validation function
func RegisterTestWrapperValidateExt(f func(*TestWrapper, string) error) {
	testWrapperValidateExt = f
}

// testWrapperListValidateExt is an extension hook for additional validation logic
var testWrapperListValidateExt func(*TestWrapperList, string) error

func (this *TestWrapperList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if testWrapperListValidateExt != nil {
		if err := testWrapperListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperListValidateExt registers an extension validation function
func RegisterTestWrapperListValidateExt(f func(*TestWrapperList, string) error) {
	testWrapperListValidateExt = f
}
