// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/test/kubeproto/test_msg3.proto

package kubeproto

import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/storage"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *TestMsg3) Reset()      { *m = TestMsg3{} }
func (*TestMsg3) ProtoMessage() {}
func (*TestMsg3) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97e63b146517aae, []int{0}
}
func (m *TestMsg3) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestMsg3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestMsg3.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestMsg3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg3.Merge(m, src)
}
func (m *TestMsg3) XXX_Size() int {
	return m.Size()
}
func (m *TestMsg3) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg3.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg3 proto.InternalMessageInfo

type TestMsg3Spec struct {
	Any *types.Any `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
}

func (m *TestMsg3Spec) Reset()      { *m = TestMsg3Spec{} }
func (*TestMsg3Spec) ProtoMessage() {}
func (*TestMsg3Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97e63b146517aae, []int{1}
}
func (m *TestMsg3Spec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestMsg3Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestMsg3Spec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestMsg3Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg3Spec.Merge(m, src)
}
func (m *TestMsg3Spec) XXX_Size() int {
	return m.Size()
}
func (m *TestMsg3Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg3Spec.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg3Spec proto.InternalMessageInfo

func (m *TestMsg3Spec) GetAny() *types.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

type TestMsg3Status struct {
	Any *types.Any `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
}

func (m *TestMsg3Status) Reset()      { *m = TestMsg3Status{} }
func (*TestMsg3Status) ProtoMessage() {}
func (*TestMsg3Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97e63b146517aae, []int{2}
}
func (m *TestMsg3Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestMsg3Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestMsg3Status.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestMsg3Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg3Status.Merge(m, src)
}
func (m *TestMsg3Status) XXX_Size() int {
	return m.Size()
}
func (m *TestMsg3Status) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg3Status.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg3Status proto.InternalMessageInfo

func (m *TestMsg3Status) GetAny() *types.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMsg3)(nil), "michelangelo.test.kubeproto.TestMsg3")
	proto.RegisterType((*TestMsg3Spec)(nil), "michelangelo.test.kubeproto.TestMsg3Spec")
	proto.RegisterType((*TestMsg3Status)(nil), "michelangelo.test.kubeproto.TestMsg3Status")
}

func init() {
	proto.RegisterFile("michelangelo/test/kubeproto/test_msg3.proto", fileDescriptor_c97e63b146517aae)
}

var fileDescriptor_c97e63b146517aae = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0x3b, 0x5c, 0x72, 0xc3, 0x1d, 0x6f, 0x34, 0x69, 0x5c, 0xd4, 0x6b, 0x32, 0x31, 0xac,
	0xd4, 0x6b, 0xce, 0x78, 0xc5, 0x85, 0xf1, 0x5f, 0x22, 0x2e, 0x15, 0x4d, 0x2a, 0x2b, 0x37, 0x64,
	0x5a, 0x8e, 0x43, 0x2d, 0x6d, 0x27, 0xcc, 0x40, 0xd2, 0x9d, 0xf1, 0x09, 0x7c, 0x1e, 0x9f, 0xc0,
	0x25, 0x4b, 0x96, 0x50, 0x36, 0x2c, 0x79, 0x04, 0xd3, 0x69, 0x21, 0xb0, 0x31, 0xb8, 0x6a, 0xcf,
	0x7c, 0xdf, 0xf7, 0x3b, 0x67, 0xe6, 0xd0, 0xeb, 0x24, 0x0a, 0x47, 0x38, 0x16, 0xa9, 0xc4, 0x71,
	0xc6, 0x0d, 0x6a, 0xc3, 0xe3, 0x69, 0x80, 0x6a, 0x92, 0x99, 0xaa, 0x1c, 0x24, 0x5a, 0x76, 0xc0,
	0xd6, 0xee, 0xfd, 0x43, 0x33, 0x94, 0x2a, 0xec, 0xcd, 0x57, 0xcf, 0xe3, 0x17, 0x1a, 0xa2, 0x8c,
	0x0b, 0x15, 0x25, 0x22, 0x1c, 0x45, 0x29, 0x4e, 0x72, 0xae, 0x62, 0x59, 0x1e, 0x68, 0x9e, 0xa0,
	0x11, 0x7c, 0x76, 0xc3, 0x25, 0xa6, 0x38, 0x11, 0x06, 0x87, 0x15, 0xf2, 0xea, 0x9e, 0xcc, 0x32,
	0x39, 0x46, 0x6e, 0xab, 0x60, 0xfa, 0x8d, 0x8b, 0x34, 0xaf, 0x25, 0x76, 0x34, 0x9a, 0x50, 0x11,
	0xcf, 0x94, 0x89, 0xb2, 0x54, 0x57, 0x7a, 0xfb, 0x77, 0x83, 0xb6, 0xfa, 0xa8, 0x4d, 0x4f, 0xcb,
	0x8e, 0xfb, 0x81, 0x5e, 0x98, 0x5c, 0xe1, 0xa0, 0xec, 0xe3, 0x91, 0x07, 0xe4, 0xe1, 0xad, 0x67,
	0x00, 0xd5, 0x44, 0x70, 0x38, 0x11, 0xa8, 0x58, 0x96, 0x07, 0x1a, 0x4a, 0x27, 0xcc, 0x6e, 0xa0,
	0x9f, 0x2b, 0xec, 0xa1, 0x11, 0x7e, 0xcb, 0xd4, 0x7f, 0xee, 0x47, 0xda, 0x2a, 0xd5, 0xa1, 0x30,
	0xc2, 0x6b, 0x58, 0xd6, 0xd3, 0xd3, 0x58, 0x9f, 0x83, 0xef, 0x18, 0x9a, 0x8a, 0xb6, 0x23, 0xb8,
	0x6f, 0x68, 0x53, 0x2b, 0x0c, 0xbd, 0x33, 0x4b, 0x7a, 0x04, 0xff, 0x78, 0x44, 0xd8, 0xdd, 0xe7,
	0x8b, 0xc2, 0xd0, 0xb7, 0x31, 0xf7, 0x3d, 0x3d, 0xd7, 0x46, 0x98, 0xa9, 0xf6, 0x9a, 0x16, 0x70,
	0x7d, 0x1a, 0xc0, 0x46, 0xfc, 0x3a, 0xfa, 0xf2, 0xce, 0xcf, 0xee, 0xe5, 0x63, 0xfa, 0x49, 0x24,
	0xa8, 0x95, 0x08, 0x71, 0xd8, 0x7e, 0x4d, 0x2f, 0x0f, 0x7b, 0xb9, 0x4f, 0xe8, 0x99, 0x48, 0xf3,
	0xfa, 0xe5, 0xee, 0x42, 0xb5, 0x15, 0xd8, 0x6d, 0x05, 0xde, 0xa5, 0x79, 0xb7, 0xb9, 0xdc, 0x34,
	0x88, 0x5f, 0xda, 0xda, 0x6f, 0xe9, 0xed, 0xe3, 0x46, 0xff, 0x97, 0xef, 0xbe, 0x9a, 0xaf, 0x98,
	0xb3, 0x58, 0x31, 0x67, 0xbb, 0x62, 0xe4, 0x47, 0xc1, 0xc8, 0x9f, 0x82, 0x91, 0x79, 0xc1, 0xc8,
	0xb2, 0x60, 0x64, 0x53, 0x30, 0x67, 0x5b, 0x30, 0xf2, 0x6b, 0xcd, 0x9c, 0xf9, 0x9a, 0x39, 0x8b,
	0x35, 0x73, 0xbe, 0x5e, 0xec, 0xaf, 0x18, 0x9c, 0xdb, 0x4f, 0xe7, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x20, 0x69, 0xbd, 0x1b, 0xbb, 0x02, 0x00, 0x00,
}

func (this *TestMsg3Spec) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.TestMsg3Spec{")
	if this.Any != nil {
		s = append(s, "Any: "+fmt.Sprintf("%#v", this.Any)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TestMsg3Status) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.TestMsg3Status{")
	if this.Any != nil {
		s = append(s, "Any: "+fmt.Sprintf("%#v", this.Any)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTestMsg3(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TestMsg3) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestMsg3) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestMsg3Spec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestMsg3Spec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestMsg3Spec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Any != nil {
		{
			size, err := m.Any.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTestMsg3(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TestMsg3Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestMsg3Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestMsg3Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Any != nil {
		{
			size, err := m.Any.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTestMsg3(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTestMsg3(dAtA []byte, offset int, v uint64) int {
	offset -= sovTestMsg3(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *TestMsg3Spec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Any != nil {
		l = m.Any.Size()
		n += 1 + l + sovTestMsg3(uint64(l))
	}
	return n
}

func (m *TestMsg3Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Any != nil {
		l = m.Any.Size()
		n += 1 + l + sovTestMsg3(uint64(l))
	}
	return n
}

func sovTestMsg3(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTestMsg3(x uint64) (n int) {
	return sovTestMsg3(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TestMsg3Spec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestMsg3Spec{`,
		`Any:` + strings.Replace(fmt.Sprintf("%v", this.Any), "Any", "types.Any", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TestMsg3Status) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestMsg3Status{`,
		`Any:` + strings.Replace(fmt.Sprintf("%v", this.Any), "Any", "types.Any", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTestMsg3(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TestMsg3Spec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestMsg3
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestMsg3Spec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestMsg3Spec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Any", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestMsg3
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Any == nil {
				m.Any = &types.Any{}
			}
			if err := m.Any.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestMsg3(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TestMsg3Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestMsg3
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestMsg3Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestMsg3Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Any", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestMsg3
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Any == nil {
				m.Any = &types.Any{}
			}
			if err := m.Any.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestMsg3(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTestMsg3(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTestMsg3
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTestMsg3
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTestMsg3
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTestMsg3
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTestMsg3        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTestMsg3          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTestMsg3 = fmt.Errorf("proto: unexpected end of group")
)

type TestMsg3 struct {
	metav1.TypeMeta   `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// Spec of the desired behavior of the TestMsg3.
	Spec TestMsg3Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Most recently observed status of the TestMsg3.
	Status TestMsg3Status `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *TestMsg3) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *TestMsg3) GetMetadata() *metav1.ObjectMeta {
	return &m.ObjectMeta
}

func (m *TestMsg3) GetSpec() TestMsg3Spec {
	if m != nil {
		return m.Spec
	}
	return TestMsg3Spec{}
}

func (m *TestMsg3) GetStatus() TestMsg3Status {
	if m != nil {
		return m.Status
	}
	return TestMsg3Status{}
}

func (m *TestMsg3) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestMsg3(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestMsg3(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestMsg3(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestMsg3(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TestMsg3) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovTestMsg3(uint64(l))
	l = m.ObjectMeta.Size()
	n += 1 + l + sovTestMsg3(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovTestMsg3(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovTestMsg3(uint64(l))
	return n
}

func (this *TestMsg3) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestMsg3{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "metav1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "TestMsg3Spec", "TestMsg3Spec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "TestMsg3Status", "TestMsg3Status", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}

func (m *TestMsg3) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestMsg3
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestMsg3: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestMsg3: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestMsg3
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestMsg3
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestMsg3
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestMsg3
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestMsg3
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestMsg3(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTestMsg3
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

/* As gogo proto's jsonpb library does not support marshal and unmarshal for
   inline field (TypeMeta), we work around this by implementing the
   marshal and unmarshal functions for Spec and Status respectively. */
func (m *TestMsg3Spec) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *TestMsg3Spec) UnmarshalJSON(b []byte) error {
	err := (&jsonpb.Unmarshaler{
	  AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
	  AnyResolver: &util.GenericResolver{},
	}).Unmarshal(bytes.NewReader(b), m)
	if err == nil {
        return nil
	}

    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

	visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
	util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
	if len(paths) > 0 {
	    b, err = util.ApplyInlineFields(b, paths)
	}
    type Alias TestMsg3Spec
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (m *TestMsg3Status) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *TestMsg3Status) UnmarshalJSON(b []byte) error {
    err := (&jsonpb.Unmarshaler{
      AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
      AnyResolver: &util.GenericResolver{},
    }).Unmarshal(bytes.NewReader(b), m)
    if err == nil {
        return nil
    }
    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

    visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
    util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
    if len(paths) > 0 {
        b, err = util.ApplyInlineFields(b, paths)
    }
    type Alias TestMsg3Status
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (in *TestMsg3) DeepCopy() *TestMsg3 {
	if in == nil {
		return nil
	}
	out := new(TestMsg3)
	in.DeepCopyInto(out)
	return out
}

func (in *TestMsg3) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TestMsg3) DeepCopyInto(out *TestMsg3) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *proto.Clone(&in.Spec).(*TestMsg3Spec)
	out.Status = *proto.Clone(&in.Status).(*TestMsg3Status)
}

func init() {
	SchemeBuilder.Register(&TestMsg3{})
}

func (m *TestMsg3) GetIndexedKeyValuePairs() ([]storage.IndexedField){
	var indexedFields []storage.IndexedField
	return indexedFields
}


func init() {
	gvk := schema.GroupVersionKind{
		Group: "michelangelo.api",
		Version: "v2",
		Kind: "TestMsg3",
	}
	IndexesPathToKeyMap[gvk] = make(map[string]string)

	// default index
	IndexesPathToKeyMap[gvk]["metadata.namespace"] = "namespace"
	IndexesPathToKeyMap[gvk]["metadata.name"] = "name"
}

func (m *TestMsg3) IsImmutableKind() bool {

	return false
}

func init() {
	CrdObjects["TestMsg3"] = &TestMsg3{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "michelangelo.api/v2",
			Kind: "TestMsg3",
		},
	}
}

func (m *TestMsg3) HasBlobFields() bool {
	return true
}

func (m *TestMsg3) ClearBlobFields() {
	if m.Spec.Any != nil {
		m.Spec.Any = nil
	}
	if m.Status.Any != nil {
		m.Status.Any = nil
	}
}

func (m *TestMsg3) FillBlobFields(object k8sruntime.Object) {
	other := object.(*TestMsg3)
	m.Spec = other.Spec
	m.Status = other.Status
}

func init() {
	YamlSchemas["TestMsg3"] = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: testmsg3s.michelangelo.api
spec:
  group: michelangelo.api
  names:
    kind: TestMsg3
    listKind: TestMsg3List
    plural: testmsg3s
    singular: testmsg3
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              any:
                properties:
                  '@type':
                    description: A URL/resource name that uniquely identifies the
                      type of the serialized protocol buffer message.
                    type: string
                  value:
                    description: Serialized data of the above type.
                    format: byte
                    type: string
                type: object
            type: object
          status:
            properties:
              any:
                properties:
                  '@type':
                    description: A URL/resource name that uniquely identifies the
                      type of the serialized protocol buffer message.
                    type: string
                  value:
                    description: Serialized data of the above type.
                    format: byte
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
`
}