// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/test/kubeproto/test_wrapper.proto

package kubeproto

import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/storage"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TestWrapperSpec struct {
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *TestWrapperSpec) Reset()      { *m = TestWrapperSpec{} }
func (*TestWrapperSpec) ProtoMessage() {}
func (*TestWrapperSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5df94bc21656b, []int{0}
}
func (m *TestWrapperSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestWrapperSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestWrapperSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestWrapperSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestWrapperSpec.Merge(m, src)
}
func (m *TestWrapperSpec) XXX_Size() int {
	return m.Size()
}
func (m *TestWrapperSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TestWrapperSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TestWrapperSpec proto.InternalMessageInfo

func (m *TestWrapperSpec) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TestWrapperStatus struct {
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *TestWrapperStatus) Reset()      { *m = TestWrapperStatus{} }
func (*TestWrapperStatus) ProtoMessage() {}
func (*TestWrapperStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5df94bc21656b, []int{1}
}
func (m *TestWrapperStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestWrapperStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestWrapperStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestWrapperStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestWrapperStatus.Merge(m, src)
}
func (m *TestWrapperStatus) XXX_Size() int {
	return m.Size()
}
func (m *TestWrapperStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TestWrapperStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TestWrapperStatus proto.InternalMessageInfo

func (m *TestWrapperStatus) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TestWrapper) Reset()      { *m = TestWrapper{} }
func (*TestWrapper) ProtoMessage() {}
func (*TestWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5df94bc21656b, []int{2}
}
func (m *TestWrapper) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestWrapper.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestWrapper.Merge(m, src)
}
func (m *TestWrapper) XXX_Size() int {
	return m.Size()
}
func (m *TestWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TestWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TestWrapper proto.InternalMessageInfo

func (m *TestWrapperList) Reset()      { *m = TestWrapperList{} }
func (*TestWrapperList) ProtoMessage() {}
func (*TestWrapperList) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5df94bc21656b, []int{3}
}
func (m *TestWrapperList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestWrapperList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestWrapperList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestWrapperList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestWrapperList.Merge(m, src)
}
func (m *TestWrapperList) XXX_Size() int {
	return m.Size()
}
func (m *TestWrapperList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestWrapperList.DiscardUnknown(m)
}

var xxx_messageInfo_TestWrapperList proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TestWrapperSpec)(nil), "michelangelo.test.kubeproto.TestWrapperSpec")
	proto.RegisterType((*TestWrapperStatus)(nil), "michelangelo.test.kubeproto.TestWrapperStatus")
	proto.RegisterType((*TestWrapper)(nil), "michelangelo.test.kubeproto.TestWrapper")
	proto.RegisterType((*TestWrapperList)(nil), "michelangelo.test.kubeproto.TestWrapperList")
}

func init() {
	proto.RegisterFile("michelangelo/test/kubeproto/test_wrapper.proto", fileDescriptor_32a5df94bc21656b)
}

var fileDescriptor_32a5df94bc21656b = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x31, 0x6b, 0x14, 0x41,
	0x14, 0xc7, 0x67, 0xb2, 0xb9, 0x98, 0x9b, 0x2b, 0xc4, 0xc5, 0x62, 0x89, 0x30, 0x84, 0xab, 0x4e,
	0x94, 0x19, 0x13, 0x2d, 0x24, 0x82, 0x68, 0x0a, 0x0b, 0x8d, 0x08, 0x6b, 0x40, 0xb0, 0x09, 0x73,
	0x9b, 0xc7, 0x65, 0xdc, 0xec, 0xee, 0xb0, 0xf3, 0x2e, 0x72, 0x9d, 0xf8, 0x09, 0xfc, 0x36, 0x7e,
	0x05, 0xcb, 0x2b, 0x53, 0x7a, 0x7b, 0x8d, 0x9d, 0xa9, 0xad, 0x64, 0x67, 0x36, 0x61, 0x73, 0x82,
	0x6c, 0x91, 0x6a, 0xf7, 0xbd, 0xf9, 0xbf, 0x1f, 0xef, 0xff, 0x7f, 0x4c, 0x64, 0x3a, 0x39, 0x81,
	0x53, 0x95, 0x4f, 0xe0, 0xb4, 0x90, 0x08, 0x16, 0x65, 0x3a, 0x1d, 0x83, 0x29, 0x0b, 0xf4, 0xe5,
	0xd1, 0xe7, 0x52, 0x19, 0x03, 0xa5, 0x70, 0xad, 0xf0, 0x5e, 0x5b, 0x2f, 0x6a, 0x81, 0xb8, 0xd2,
	0x6f, 0x3d, 0x49, 0x9f, 0x5a, 0xa1, 0x0b, 0xa9, 0x8c, 0xce, 0x54, 0x72, 0xa2, 0x73, 0x28, 0x67,
	0xd2, 0xa4, 0x93, 0xba, 0x61, 0x65, 0x06, 0xa8, 0xe4, 0xd9, 0x8e, 0x9c, 0x40, 0x0e, 0xa5, 0x42,
	0x38, 0xf6, 0xc8, 0x2d, 0x7e, 0x6d, 0x05, 0x65, 0xb4, 0x2c, 0x0c, 0xea, 0x22, 0xb7, 0xfe, 0x7d,
	0xf8, 0x80, 0xdd, 0x3e, 0x04, 0x8b, 0x1f, 0xfc, 0x1e, 0xef, 0x0d, 0x24, 0x61, 0xc4, 0x6e, 0x25,
	0x45, 0x8e, 0x90, 0x63, 0x44, 0xb7, 0xe9, 0xa8, 0x1f, 0x5f, 0x96, 0xc3, 0xfb, 0xec, 0x4e, 0x5b,
	0x8c, 0x0a, 0xa7, 0x36, 0xbc, 0xcb, 0x7a, 0x49, 0x31, 0x6d, 0xc4, 0xbd, 0xd8, 0x17, 0xc3, 0xef,
	0x6b, 0x6c, 0xd0, 0xd2, 0x86, 0x6f, 0x58, 0x1f, 0x67, 0x06, 0x8e, 0xea, 0x3d, 0x9d, 0x72, 0xb0,
	0x2b, 0x84, 0x77, 0x24, 0xda, 0x8e, 0x84, 0x49, 0x27, 0x75, 0xc3, 0x8a, 0x5a, 0x29, 0xce, 0x76,
	0xc4, 0xe1, 0xcc, 0xc0, 0x5b, 0x40, 0x15, 0x6f, 0x62, 0xf3, 0x17, 0x1e, 0xb0, 0xcd, 0xfa, 0xf5,
	0x58, 0xa1, 0x8a, 0xd6, 0x1c, 0xeb, 0x51, 0x37, 0xd6, 0xbb, 0xf1, 0x27, 0x48, 0xd0, 0xd3, 0x2e,
	0x09, 0xe1, 0x0b, 0xb6, 0x6e, 0x0d, 0x24, 0x51, 0xe0, 0x48, 0x0f, 0xc5, 0x7f, 0x8e, 0x20, 0x56,
	0xb2, 0x8a, 0xdd, 0x64, 0xf8, 0x8a, 0x6d, 0x58, 0x17, 0x46, 0xb4, 0xde, 0x38, 0xeb, 0xca, 0x70,
	0x53, 0x71, 0x33, 0xbd, 0x17, 0x7c, 0xdd, 0x27, 0xc3, 0xdf, 0xf4, 0xda, 0x49, 0x0e, 0xb4, 0xc5,
	0x9b, 0x4d, 0xef, 0xf5, 0x3f, 0xe9, 0x75, 0x64, 0xd5, 0xab, 0xac, 0x64, 0xf7, 0x9c, 0xf5, 0x34,
	0x42, 0x66, 0xa3, 0x60, 0x3b, 0x18, 0x0d, 0x76, 0x47, 0x5d, 0x8d, 0xc7, 0x7e, 0x6c, 0x2f, 0xf8,
	0xf3, 0x92, 0xec, 0x3f, 0x9b, 0x2f, 0x38, 0x39, 0x5f, 0x70, 0x72, 0xb1, 0xe0, 0xf4, 0x4b, 0xc5,
	0xe9, 0x8f, 0x8a, 0xd3, 0x79, 0xc5, 0xe9, 0xcf, 0x8a, 0xd3, 0x5f, 0x15, 0x27, 0x17, 0x15, 0xa7,
	0xdf, 0x96, 0x9c, 0xcc, 0x97, 0x9c, 0x9c, 0x2f, 0x39, 0xf9, 0xd8, 0xbf, 0x82, 0x8e, 0x37, 0xdc,
	0xe7, 0xf1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x52, 0x28, 0x54, 0x6c, 0x03, 0x00, 0x00,
}

func (this *TestWrapperSpec) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.TestWrapperSpec{")
	s = append(s, "Content: "+fmt.Sprintf("%#v", this.Content)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TestWrapperStatus) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.TestWrapperStatus{")
	s = append(s, "Count: "+fmt.Sprintf("%#v", this.Count)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTestWrapper(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TestWrapperSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestWrapperSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestWrapperSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintTestWrapper(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TestWrapperStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestWrapperStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestWrapperStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintTestWrapper(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TestWrapper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestWrapper) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestWrapperList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestWrapperList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func encodeVarintTestWrapper(dAtA []byte, offset int, v uint64) int {
	offset -= sovTestWrapper(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TestWrapperSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovTestWrapper(uint64(l))
	}
	return n
}

func (m *TestWrapperStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovTestWrapper(uint64(m.Count))
	}
	return n
}

func sovTestWrapper(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTestWrapper(x uint64) (n int) {
	return sovTestWrapper(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TestWrapperSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestWrapperSpec{`,
		`Content:` + fmt.Sprintf("%v", this.Content) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TestWrapperStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestWrapperStatus{`,
		`Count:` + fmt.Sprintf("%v", this.Count) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTestWrapper(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TestWrapperSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestWrapper
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestWrapperSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestWrapperSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestWrapper(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TestWrapperStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestWrapper
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestWrapperStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestWrapperStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTestWrapper(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTestWrapper(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTestWrapper
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTestWrapper
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTestWrapper
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTestWrapper
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTestWrapper        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTestWrapper          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTestWrapper = fmt.Errorf("proto: unexpected end of group")
)

type TestWrapper struct {
	metav1.TypeMeta   `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// Spec of the desired behavior of the TestWrapper.
	Spec TestWrapperSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Most recently observed status of the TestWrapper.
	Status TestWrapperStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *TestWrapper) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *TestWrapper) GetMetadata() *metav1.ObjectMeta {
	return &m.ObjectMeta
}

func (m *TestWrapper) GetSpec() TestWrapperSpec {
	if m != nil {
		return m.Spec
	}
	return TestWrapperSpec{}
}

func (m *TestWrapper) GetStatus() TestWrapperStatus {
	if m != nil {
		return m.Status
	}
	return TestWrapperStatus{}
}

func (m *TestWrapper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestWrapper(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestWrapper(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestWrapper(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestWrapper(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TestWrapper) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovTestWrapper(uint64(l))
	l = m.ObjectMeta.Size()
	n += 1 + l + sovTestWrapper(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovTestWrapper(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovTestWrapper(uint64(l))
	return n
}

func (this *TestWrapper) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TestWrapper{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "metav1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "TestWrapperSpec", "TestWrapperSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "TestWrapperStatus", "TestWrapperStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}

func (m *TestWrapper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestWrapper
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestWrapper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestWrapper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestWrapper(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

/* As gogo proto's jsonpb library does not support marshal and unmarshal for
   inline field (TypeMeta), we work around this by implementing the
   marshal and unmarshal functions for Spec and Status respectively. */
func (m *TestWrapperSpec) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *TestWrapperSpec) UnmarshalJSON(b []byte) error {
	err := (&jsonpb.Unmarshaler{
	  AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
	  AnyResolver: &util.GenericResolver{},
	}).Unmarshal(bytes.NewReader(b), m)
	if err == nil {
        return nil
	}

    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

	visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
	util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
	if len(paths) > 0 {
	    b, err = util.ApplyInlineFields(b, paths)
	}
    type Alias TestWrapperSpec
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (m *TestWrapperStatus) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *TestWrapperStatus) UnmarshalJSON(b []byte) error {
    err := (&jsonpb.Unmarshaler{
      AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
      AnyResolver: &util.GenericResolver{},
    }).Unmarshal(bytes.NewReader(b), m)
    if err == nil {
        return nil
    }
    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

    visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
    util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
    if len(paths) > 0 {
        b, err = util.ApplyInlineFields(b, paths)
    }
    type Alias TestWrapperStatus
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (in *TestWrapper) DeepCopy() *TestWrapper {
	if in == nil {
		return nil
	}
	out := new(TestWrapper)
	in.DeepCopyInto(out)
	return out
}

func (in *TestWrapper) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TestWrapper) DeepCopyInto(out *TestWrapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *proto.Clone(&in.Spec).(*TestWrapperSpec)
	out.Status = *proto.Clone(&in.Status).(*TestWrapperStatus)
}

func init() {
	SchemeBuilder.Register(&TestWrapper{})
}

func (m *TestWrapper) GetIndexedKeyValuePairs() ([]storage.IndexedField){
	var indexedFields []storage.IndexedField
	return indexedFields
}


func init() {
	gvk := schema.GroupVersionKind{
		Group: "michelangelo.api",
		Version: "v2",
		Kind: "TestWrapper",
	}
	IndexesPathToKeyMap[gvk] = make(map[string]string)

	// default index
	IndexesPathToKeyMap[gvk]["metadata.namespace"] = "namespace"
	IndexesPathToKeyMap[gvk]["metadata.name"] = "name"
}

func (m *TestWrapper) IsImmutableKind() bool {

	return false
}

func init() {
	CrdObjects["TestWrapper"] = &TestWrapper{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "michelangelo.api/v2",
			Kind: "TestWrapper",
		},
	}
}

func (m *TestWrapper) HasBlobFields() bool {
	return false
}

func (m *TestWrapper) ClearBlobFields() {
}

func (m *TestWrapper) FillBlobFields(object k8sruntime.Object) {
	other := object.(*TestWrapper)
	m.Spec = other.Spec
	m.Status = other.Status
}

func init() {
	YamlSchemas["TestWrapper"] = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: testwrappers.michelangelo.api
spec:
  group: michelangelo.api
  names:
    kind: TestWrapper
    listKind: TestWrapperList
    plural: testwrappers
    singular: testwrapper
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              content:
                type: string
            type: object
          status:
            properties:
              count:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
`
}

type TestWrapperList struct {
	metav1.TypeMeta `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ListMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// A list of TestWrapper
	Items []TestWrapper `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
}

func (m *TestWrapperList) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *TestWrapperList) GetMetadata() *metav1.ListMeta {
	return &m.ListMeta
}

func (m *TestWrapperList) GetItems() []TestWrapper {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TestWrapperList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTestWrapper(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestWrapper(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTestWrapper(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TestWrapperList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovTestWrapper(uint64(l))
	l = m.ListMeta.Size()
	n += 1 + l + sovTestWrapper(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovTestWrapper(uint64(l))
		}
	}
	return n
}

func (this *TestWrapperList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]TestWrapper{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "TestWrapper", "TestWrapper", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&TestWrapperList{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "metav1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}

func (m *TestWrapperList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTestWrapper
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestWrapperList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestWrapperList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTestWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTestWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, TestWrapper{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTestWrapper(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTestWrapper
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (in *TestWrapperList) DeepCopy() *TestWrapperList {
	if in == nil {
		return nil
	}
	out := new(TestWrapperList)
	in.DeepCopyInto(out)
	return out
}

func (in *TestWrapperList) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TestWrapperList) DeepCopyInto(out *TestWrapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func init() {
	SchemeBuilder.Register(&TestWrapperList{})
}
