// Code generated by protoc-gen-validation. DO NOT EDIT.

package kubeproto

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// validationMsg1ValidateExt is an extension hook for additional validation logic
var validationMsg1ValidateExt func(*ValidationMsg1, string) error

func (this *ValidationMsg1) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
		if !(v >= 10 && v <= 100) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be in the range [10,100]")
		}
	}
	{
		v := this.F3
		n := `f3`
		if len(v) == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"custom error message")
		}
	}
	{
		v := this.F4
		n := `f4`
		if !(v >= Enum1(2)) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be >= 2")
		}
	}
	{
		v := this.GetF5()
		n := `f5`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if validationMsg1ValidateExt != nil {
		if err := validationMsg1ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg1ValidateExt registers an extension validation function
func RegisterValidationMsg1ValidateExt(f func(*ValidationMsg1, string) error) {
	validationMsg1ValidateExt = f
}

// validationMsg2ValidateExt is an extension hook for additional validation logic
var validationMsg2ValidateExt func(*ValidationMsg2, string) error

func (this *ValidationMsg2) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
		if !(v <= 5) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be <= 5")
		}
	}
	{
		v := this.F3
		n := `f3`
		if len(v) == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be empty")
		}
	}
	{
		v := this.F4
		n := `f4`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero value")
		}
	}
	{
		v := this.GetF5()
		n := `f5`
		if v == nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be nil")
		}
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.F6
		n := `f6`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
	}
	{
		v := this.F7
		n := `f7`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
		if !(v > -1) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"custom msg min")
		}
		if !(v <= 1.0) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"custom msg max")
		}
	}
	{
		v := this.F8
		n := `f8`
		if !(v >= -0.1 && v < 0.5) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be in the range [-0.1,0.5)")
		}
	}
	{
		v := this.F9
		n := `f9`
		if len(v) == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be empty")
		}
	}
	{
		v := this.F10
		n := `f10`
		if len(v) == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be empty")
		}
	}
	// Call extension validation if registered
	if validationMsg2ValidateExt != nil {
		if err := validationMsg2ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg2ValidateExt registers an extension validation function
func RegisterValidationMsg2ValidateExt(f func(*ValidationMsg2, string) error) {
	validationMsg2ValidateExt = f
}

// validationMsg3ValidateExt is an extension hook for additional validation logic
var validationMsg3ValidateExt func(*ValidationMsg3, string) error

func (this *ValidationMsg3) Validate(prefix string) error {

	// Call extension validation if registered
	if validationMsg3ValidateExt != nil {
		if err := validationMsg3ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg3ValidateExt registers an extension validation function
func RegisterValidationMsg3ValidateExt(f func(*ValidationMsg3, string) error) {
	validationMsg3ValidateExt = f
}

// validationMsg4ValidateExt is an extension hook for additional validation logic
var validationMsg4ValidateExt func(*ValidationMsg4, string) error

func (this *ValidationMsg4) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if !(len(v) >= 3 && len(v) <= 10) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be 3 to 10 characters long, inclusive")
		}
	}
	{
		v := this.F2
		n := `f2`
		if !(len(v) >= 2) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must contain at least 2 items")
		}
	}
	{
		v := this.F3
		n := `f3`
		if !(len(v) >= 1 && len(v) <= 100) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be 1 to 100 bytes long, inclusive")
		}
	}
	{
		v := this.GetF4()
		n := `f4`
		if !(len(v) >= 1 && len(v) <= 3) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must contain 1 to 3 items, inclusive")
		}
	}
	// Call extension validation if registered
	if validationMsg4ValidateExt != nil {
		if err := validationMsg4ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg4ValidateExt registers an extension validation function
func RegisterValidationMsg4ValidateExt(f func(*ValidationMsg4, string) error) {
	validationMsg4ValidateExt = f
}

var ValidationMsg5Pattern0 = regexp.MustCompile("^[ab]+$")
var ValidationMsg5Pattern1 = regexp.MustCompile("^aa.*$")
var ValidationMsg5Pattern2 = regexp.MustCompile("^[1-9][0-9]*$")

// validationMsg5ValidateExt is an extension hook for additional validation logic
var validationMsg5ValidateExt func(*ValidationMsg5, string) error

func (this *ValidationMsg5) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if !ValidationMsg5Pattern0.MatchString(v) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must match regular expression pattern /[ab]+/")
		}
		if ValidationMsg5Pattern1.MatchString(v) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must not match regular expression pattern /aa.*/")
		}
	}
	{
		v := this.F2
		n := `f2`
		if !ValidationMsg5Pattern2.MatchString(v) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a positive number")
		}
	}
	// Call extension validation if registered
	if validationMsg5ValidateExt != nil {
		if err := validationMsg5ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg5ValidateExt registers an extension validation function
func RegisterValidationMsg5ValidateExt(f func(*ValidationMsg5, string) error) {
	validationMsg5ValidateExt = f
}

var ValidationMsg6Set0 = map[string]bool{
	"a": true,
	"b": true,
}
var ValidationMsg6Set1 = map[int32]bool{
	1: true,
	2: true,
}
var ValidationMsg6Set2 = map[Enum1]bool{
	Enum1(1): true,
	Enum1(2): true,
}
var ValidationMsg6Set3 = map[string]bool{
	"a": true,
	"b": true,
}
var ValidationMsg6Set4 = map[string]bool{
	"c": true,
}
var ValidationMsg6Set5 = map[uint64]bool{
	100: true,
	200: true,
	300: true,
}
var ValidationMsg6Set6 = map[float64]bool{
	1.0: true,
	2.0: true,
}

// validationMsg6ValidateExt is an extension hook for additional validation logic
var validationMsg6ValidateExt func(*ValidationMsg6, string) error

func (this *ValidationMsg6) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if !ValidationMsg6Set0[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be either \"a\", or \"b\"")
		}
	}
	{
		v := this.F2
		n := `f2`
		if !ValidationMsg6Set1[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"custom msg")
		}
	}
	{
		v := this.F3
		n := `f3`
		if !ValidationMsg6Set2[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be either 1, or 2")
		}
	}
	{
		v := this.F4
		n := `f4`
		if ValidationMsg6Set3[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be \"a\", nor \"b\"")
		}
		if ValidationMsg6Set4[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be \"c\"")
		}
	}
	{
		v := this.F5
		n := `f5`
		if ValidationMsg6Set5[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be 100, 200, nor 300")
		}
	}
	{
		v := this.F6
		n := `f6`
		if !ValidationMsg6Set6[v] {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be either 1.0, or 2.0")
		}
	}
	// Call extension validation if registered
	if validationMsg6ValidateExt != nil {
		if err := validationMsg6ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg6ValidateExt registers an extension validation function
func RegisterValidationMsg6ValidateExt(f func(*ValidationMsg6, string) error) {
	validationMsg6ValidateExt = f
}

// validationMsg7ValidateExt is an extension hook for additional validation logic
var validationMsg7ValidateExt func(*ValidationMsg7, string) error

func (this *ValidationMsg7) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if _, err := uuid.Parse(v); err != nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid UUID")
		}
	}
	{
		v := this.F2
		n := `f2`
		if _, err := mail.ParseAddress(v); err != nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid email address")
		}
	}
	{
		v := this.F3
		n := `f3`
		if _, err := url.ParseRequestURI(v); err != nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid URI")
		}
	}
	{
		v := this.F4
		n := `f4`
		if ip := net.ParseIP(v); ip == nil || strings.Contains(v, ":") {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid IPv4 address")
		}
	}
	{
		v := this.F5
		n := `f5`
		if ip := net.ParseIP(v); ip == nil || !strings.Contains(v, ":") {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid IPv6 address")
		}
	}
	{
		v := this.F6
		n := `f6`
		if ip := net.ParseIP(v); ip == nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid IP address")
		}
	}
	// Call extension validation if registered
	if validationMsg7ValidateExt != nil {
		if err := validationMsg7ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg7ValidateExt registers an extension validation function
func RegisterValidationMsg7ValidateExt(f func(*ValidationMsg7, string) error) {
	validationMsg7ValidateExt = f
}

// validationMsg8ValidateExt is an extension hook for additional validation logic
var validationMsg8ValidateExt func(*ValidationMsg8, string) error

func (this *ValidationMsg8) Validate(prefix string) error {

	{
		v := this.GetF1()
		n := `f1`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetF2()
		n := `f2`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if validationMsg8ValidateExt != nil {
		if err := validationMsg8ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg8ValidateExt registers an extension validation function
func RegisterValidationMsg8ValidateExt(f func(*ValidationMsg8, string) error) {
	validationMsg8ValidateExt = f
}

// validationMsg9ValidateExt is an extension hook for additional validation logic
var validationMsg9ValidateExt func(*ValidationMsg9, string) error

func (this *ValidationMsg9) Validate(prefix string) error {

	{
		v := this.F1
		n := `f1`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
	}
	{
		v := this.GetF2()
		n := `f2`
		if v == nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be nil")
		}
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if validationMsg9ValidateExt != nil {
		if err := validationMsg9ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg9ValidateExt registers an extension validation function
func RegisterValidationMsg9ValidateExt(f func(*ValidationMsg9, string) error) {
	validationMsg9ValidateExt = f
}

var ValidationMsg10Pattern0 = regexp.MustCompile("^[ab]+$")
var ValidationMsg10Pattern1 = regexp.MustCompile("^[a-z]+$")
var ValidationMsg10Set0 = map[string]bool{
	"one":   true,
	"two":   true,
	"three": true,
}

// validationMsg10ValidateExt is an extension hook for additional validation logic
var validationMsg10ValidateExt func(*ValidationMsg10, string) error

func (this *ValidationMsg10) Validate(prefix string) error {

	{
		v := this.F1
		for i, v := range v {
			n := `f1[` + strconv.Itoa(i) + `]`

			if !ValidationMsg10Pattern0.MatchString(v) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must match regular expression pattern /[ab]+/")
			}
		}
	}
	{
		v := this.GetF2()
		n := `f2`
		if !(len(v) >= 2) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must contain at least 2 items")
		}
		for v := range v {
			n := `f2 key`

			if !(v >= 1 && v <= 5) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must be in the range [1,5]")
			}
		}
		for k, v := range v {
			n := fmt.Sprintf(`f2[%v]`, k)

			if !ValidationMsg10Pattern1.MatchString(v) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must match regular expression pattern /[a-z]+/")
			}
		}
	}
	{
		v := this.F3
		for i, v := range v {
			n := `f3[` + strconv.Itoa(i) + `]`

			if !(v >= 10) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"custom msg1")
			}
			if !(v <= 100) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"custom msg2")
			}
		}
	}
	{
		v := this.GetF4()
		for i, v := range v {
			n := `f4[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	{
		v := this.GetF5()
		for k, v := range v {
			n := fmt.Sprintf(`f5[%v]`, k)

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	{
		v := this.F6
		for i, v := range v {
			n := `f6[` + strconv.Itoa(i) + `]`

			if !ValidationMsg10Set0[v] {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must be either \"one\", \"two\", or \"three\"")
			}
		}
	}
	{
		v := this.GetF7()
		for v := range v {
			n := `f7 key`

			if _, err := uuid.Parse(v); err != nil {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a valid UUID")
			}
		}
		for k, v := range v {
			n := fmt.Sprintf(`f7[%v]`, k)

			if !(len(v) >= 3) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must be at least 3 bytes long")
			}
		}
	}
	// Call extension validation if registered
	if validationMsg10ValidateExt != nil {
		if err := validationMsg10ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg10ValidateExt registers an extension validation function
func RegisterValidationMsg10ValidateExt(f func(*ValidationMsg10, string) error) {
	validationMsg10ValidateExt = f
}

// validationMsg11ValidateExt is an extension hook for additional validation logic
var validationMsg11ValidateExt func(*ValidationMsg11, string) error

func (this *ValidationMsg11) Validate(prefix string) error {

	if f, ok := this.Test.(*ValidationMsg11_F2); ok {
		v := f.F2
		n := `f2`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	if this.GetTest() == nil {
		return status.Error(codes.InvalidArgument, "one field in oneof "+prefix+"test(f1,f2) must be set")
	}

	// Call extension validation if registered
	if validationMsg11ValidateExt != nil {
		if err := validationMsg11ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg11ValidateExt registers an extension validation function
func RegisterValidationMsg11ValidateExt(f func(*ValidationMsg11, string) error) {
	validationMsg11ValidateExt = f
}

// validationMsg12ValidateExt is an extension hook for additional validation logic
var validationMsg12ValidateExt func(*ValidationMsg12, string) error

func (this *ValidationMsg12) Validate(prefix string) error {

	if f, ok := this.TestOneof.(*ValidationMsg12_F1); ok {
		v := f.F1
		n := `f1`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
	}
	if f, ok := this.TestOneof.(*ValidationMsg12_F2); ok {
		v := f.F2
		n := `f2`
		if v == nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be nil")
		}
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	if f, ok := this.TestOneofOptional.(*ValidationMsg12_F3); ok {
		v := f.F3
		n := `f3`
		if v == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be a non-zero number")
		}
	}
	if f, ok := this.TestOneofOptional.(*ValidationMsg12_F4); ok {
		v := f.F4
		n := `f4`
		if v == nil {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be nil")
		}
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	if this.GetTestOneof() == nil {
		return status.Error(codes.InvalidArgument, "one field in oneof "+prefix+"test_oneof(f1,f2) must be set")
	}

	// Call extension validation if registered
	if validationMsg12ValidateExt != nil {
		if err := validationMsg12ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg12ValidateExt registers an extension validation function
func RegisterValidationMsg12ValidateExt(f func(*ValidationMsg12, string) error) {
	validationMsg12ValidateExt = f
}

// validationMsg13ValidateExt is an extension hook for additional validation logic
var validationMsg13ValidateExt func(*ValidationMsg13, string) error

func (this *ValidationMsg13) Validate(prefix string) error {

	{
		v := this.GetF1()
		n := `f1`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
		const (
			durationMaxNanos   = 999999999
			durationMinNanos   = -999999999
			durationMaxSeconds = 315576000000
			durationMinSeconds = -315576000000
		)
		if v.GetSeconds() < durationMinSeconds || v.GetSeconds() > durationMaxSeconds {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds out of range")
		}
		if v.GetNanos() < durationMinNanos || v.GetNanos() > durationMaxNanos {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"nanos out of range")
		}
		if (v.GetSeconds() < 0 && v.GetNanos() > 0) || (v.GetSeconds() > 0 && v.GetNanos() < 0) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds and nanos must have the same sign")
		}
	}
	{
		v := this.GetF2()
		n := `f2`
		if !((float64(v.GetSeconds())+float64(v.GetNanos())/1e9) > 0 && (float64(v.GetSeconds())+float64(v.GetNanos())/1e9) <= 3600) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be in the range (0,3600] seconds")
		}
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
		const (
			durationMaxNanos   = 999999999
			durationMinNanos   = -999999999
			durationMaxSeconds = 315576000000
			durationMinSeconds = -315576000000
		)
		if v.GetSeconds() < durationMinSeconds || v.GetSeconds() > durationMaxSeconds {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds out of range")
		}
		if v.GetNanos() < durationMinNanos || v.GetNanos() > durationMaxNanos {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"nanos out of range")
		}
		if (v.GetSeconds() < 0 && v.GetNanos() > 0) || (v.GetSeconds() > 0 && v.GetNanos() < 0) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds and nanos must have the same sign")
		}
	}
	{
		v := this.GetF3()
		for i, v := range v {
			n := `f3[` + strconv.Itoa(i) + `]`

			if !((float64(v.GetSeconds()) + float64(v.GetNanos())/1e9) <= 60) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must be <= 60 seconds")
			}
			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
			const (
				durationMaxNanos   = 999999999
				durationMinNanos   = -999999999
				durationMaxSeconds = 315576000000
				durationMinSeconds = -315576000000
			)
			if v.GetSeconds() < durationMinSeconds || v.GetSeconds() > durationMaxSeconds {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds out of range")
			}
			if v.GetNanos() < durationMinNanos || v.GetNanos() > durationMaxNanos {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"nanos out of range")
			}
			if (v.GetSeconds() < 0 && v.GetNanos() > 0) || (v.GetSeconds() > 0 && v.GetNanos() < 0) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds and nanos must have the same sign")
			}
		}
	}
	{
		v := this.GetF4()
		for k, v := range v {
			n := fmt.Sprintf(`f4[%v]`, k)

			if !((float64(v.GetSeconds()) + float64(v.GetNanos())/1e9) >= 1) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"must be >= 1 seconds")
			}
			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
			const (
				durationMaxNanos   = 999999999
				durationMinNanos   = -999999999
				durationMaxSeconds = 315576000000
				durationMinSeconds = -315576000000
			)
			if v.GetSeconds() < durationMinSeconds || v.GetSeconds() > durationMaxSeconds {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds out of range")
			}
			if v.GetNanos() < durationMinNanos || v.GetNanos() > durationMaxNanos {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"nanos out of range")
			}
			if (v.GetSeconds() < 0 && v.GetNanos() > 0) || (v.GetSeconds() > 0 && v.GetNanos() < 0) {
				return status.Error(codes.InvalidArgument, prefix+n+" "+"seconds and nanos must have the same sign")
			}
		}
	}
	// Call extension validation if registered
	if validationMsg13ValidateExt != nil {
		if err := validationMsg13ValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterValidationMsg13ValidateExt registers an extension validation function
func RegisterValidationMsg13ValidateExt(f func(*ValidationMsg13, string) error) {
	validationMsg13ValidateExt = f
}
