// Code generated by protoc-gen-kubeconversion. DO NOT EDIT.
package v2alpha1

import (
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	v2 "github.com/michelangelo-ai/michelangelo/proto-go/api/v2"
	conversion1 "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	conversion "sigs.k8s.io/controller-runtime/pkg/conversion"
)

func ConvertOwnerInfoToHub(in *OwnerInfo, out *v2.OwnerInfo) error {
	if in == nil {
		return nil
	}
	out.OwningTeam = in.OwningTeam
	if in.Owners == nil {
		out.Owners = nil
	} else {
		out.Owners = []string{}
	}
	for _, v := range in.Owners {
		out.Owners = append(out.Owners, v)
	}
	if in.OwnerGroups == nil {
		out.OwnerGroups = nil
	} else {
		out.OwnerGroups = []string{}
	}
	for _, v := range in.OwnerGroups {
		out.OwnerGroups = append(out.OwnerGroups, v)
	}
	return nil
}

func ConvertOwnerInfoFromHub(in *v2.OwnerInfo, out *OwnerInfo) error {
	if in == nil {
		return nil
	}
	out.OwningTeam = in.OwningTeam
	if in.Owners == nil {
		out.Owners = nil
	} else {
		out.Owners = []string{}
	}
	for _, v := range in.Owners {
		out.Owners = append(out.Owners, v)
	}
	if in.OwnerGroups == nil {
		out.OwnerGroups = nil
	} else {
		out.OwnerGroups = []string{}
	}
	for _, v := range in.OwnerGroups {
		out.OwnerGroups = append(out.OwnerGroups, v)
	}
	return nil
}

type CustomProjectConvertor interface {
	ConvertToHub(src *Project, dst *v2.Project) error
	ConvertFromHub(src *v2.Project, dst *Project) error
}

func SetCustomProjectConvertor(convertor CustomProjectConvertor) {
	if customProjectConvertor == nil {
		customProjectConvertor = convertor
	} else {
		panic("CustomProjectConvertor has already been set")
	}
}

var customProjectConvertor CustomProjectConvertor = nil

func (src *Project) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*v2.Project)
	// Preserve ObjectMeta (name, namespace, labels, annotations, etc.)
	dst.ObjectMeta = src.ObjectMeta
	if err := ConvertProjectSpecToHub(&src.Spec, &dst.Spec); err != nil {
		return err
	}
	if err := ConvertProjectStatusToHub(&src.Status, &dst.Status); err != nil {
		return err
	}
	if customProjectConvertor != nil {
		return customProjectConvertor.ConvertToHub(src, dst)
	}
	return nil
}

func (dst *Project) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*v2.Project)
	// Preserve ObjectMeta (name, namespace, labels, annotations, etc.)
	dst.ObjectMeta = src.ObjectMeta
	if err := ConvertProjectSpecFromHub(&src.Spec, &dst.Spec); err != nil {
		return err
	}
	if err := ConvertProjectStatusFromHub(&src.Status, &dst.Status); err != nil {
		return err
	}
	if customProjectConvertor != nil {
		return customProjectConvertor.ConvertFromHub(src, dst)
	}
	return nil
}

func init() {
	SchemeBuilder.SchemeBuilder.Register(func(s *runtime.Scheme) error {
		if err := s.AddGeneratedConversionFunc((*Project)(nil), (*v2.Project)(nil), func(a, b interface{}, _ conversion1.Scope) error {
			return a.(*Project).ConvertTo(b.(conversion.Hub))
		}); err != nil {
			return err
		}
		return s.AddGeneratedConversionFunc((*v2.Project)(nil), (*Project)(nil), func(a, b interface{}, _ conversion1.Scope) error {
			return b.(*Project).ConvertFrom(a.(conversion.Hub))
		})
	})
}

func ConvertProjectSpecToHub(in *ProjectSpec, out *v2.ProjectSpec) error {
	if in == nil {
		return nil
	}
	out.Description = in.ProjectDescription
	if in.Owner == nil {
		out.Owner = nil
	} else {
		out.Owner = &v2.OwnerInfo{}
		ConvertOwnerInfoToHub(in.Owner, out.Owner)
	}
	out.Tier = in.Tier
	out.GitRepo = in.GitRepo
	out.RootDir = in.RootDir
	if in.Commit == nil {
		out.Commit = nil
	} else {
		out.Commit = &v2.CommitInfo{}
		ConvertCommitInfoToHub(in.Commit, out.Commit)
	}
	if in.SupportingLinks == nil {
		out.SupportingLinks = nil
	} else {
		out.SupportingLinks = make(map[string]string, len(in.SupportingLinks))
		for k, v := range in.SupportingLinks {
			out.SupportingLinks[k] = v
		}
	}
	if in.RetentionConfig == nil {
		out.RetentionConfig = nil
	} else {
		out.RetentionConfig = &v2.RetentionConfig{}
		ConvertRetentionConfigToHub(in.RetentionConfig, out.RetentionConfig)
	}
	return nil
}

func ConvertProjectSpecFromHub(in *v2.ProjectSpec, out *ProjectSpec) error {
	if in == nil {
		return nil
	}
	out.ProjectDescription = in.Description
	if in.Owner == nil {
		out.Owner = nil
	} else {
		out.Owner = &OwnerInfo{}
		ConvertOwnerInfoFromHub(in.Owner, out.Owner)
	}
	out.Tier = in.Tier
	out.GitRepo = in.GitRepo
	out.RootDir = in.RootDir
	if in.Commit == nil {
		out.Commit = nil
	} else {
		out.Commit = &CommitInfo{}
		ConvertCommitInfoFromHub(in.Commit, out.Commit)
	}
	if in.SupportingLinks == nil {
		out.SupportingLinks = nil
	} else {
		out.SupportingLinks = make(map[string]string, len(in.SupportingLinks))
		for k, v := range in.SupportingLinks {
			out.SupportingLinks[k] = v
		}
	}
	if in.RetentionConfig == nil {
		out.RetentionConfig = nil
	} else {
		out.RetentionConfig = &RetentionConfig{}
		ConvertRetentionConfigFromHub(in.RetentionConfig, out.RetentionConfig)
	}
	return nil
}

func ConvertProjectStatusToHub(in *ProjectStatus, out *v2.ProjectStatus) error {
	if in == nil {
		return nil
	}
	out.State = v2.ProjectState(int32(in.State))
	out.Phase = v2.ProjectPhase(int32(in.Phase))
	out.ErrorMessage = in.ErrorMessage
	out.LastUpdateTime = proto.Clone(in.LastUpdateTime).(*types.Timestamp)
	return nil
}

func ConvertProjectStatusFromHub(in *v2.ProjectStatus, out *ProjectStatus) error {
	if in == nil {
		return nil
	}
	out.State = ProjectState(int32(in.State))
	out.Phase = ProjectPhase(int32(in.Phase))
	out.ErrorMessage = in.ErrorMessage
	out.LastUpdateTime = proto.Clone(in.LastUpdateTime).(*types.Timestamp)
	return nil
}

func ConvertRetentionToHub(in *Retention, out *v2.Retention) error {
	if in == nil {
		return nil
	}
	out.RetentionInDays = in.RetentionInDays
	return nil
}

func ConvertRetentionFromHub(in *v2.Retention, out *Retention) error {
	if in == nil {
		return nil
	}
	out.RetentionInDays = in.RetentionInDays
	return nil
}

func ConvertRetentionConfigToHub(in *RetentionConfig, out *v2.RetentionConfig) error {
	if in == nil {
		return nil
	}
	if in.OnlineDeploymentRetention == nil {
		out.OnlineDeploymentRetention = nil
	} else {
		out.OnlineDeploymentRetention = &v2.Retention{}
		ConvertRetentionToHub(in.OnlineDeploymentRetention, out.OnlineDeploymentRetention)
	}
	if in.OfflineDeploymentRetention == nil {
		out.OfflineDeploymentRetention = nil
	} else {
		out.OfflineDeploymentRetention = &v2.Retention{}
		ConvertRetentionToHub(in.OfflineDeploymentRetention, out.OfflineDeploymentRetention)
	}
	if in.EndpointRetention == nil {
		out.EndpointRetention = nil
	} else {
		out.EndpointRetention = &v2.Retention{}
		ConvertRetentionToHub(in.EndpointRetention, out.EndpointRetention)
	}
	if in.ModelRetention == nil {
		out.ModelRetention = nil
	} else {
		out.ModelRetention = &v2.Retention{}
		ConvertRetentionToHub(in.ModelRetention, out.ModelRetention)
	}
	out.NotificationControl = v2.NotificationControl(int32(in.NotificationControl))
	return nil
}

func ConvertRetentionConfigFromHub(in *v2.RetentionConfig, out *RetentionConfig) error {
	if in == nil {
		return nil
	}
	if in.OnlineDeploymentRetention == nil {
		out.OnlineDeploymentRetention = nil
	} else {
		out.OnlineDeploymentRetention = &Retention{}
		ConvertRetentionFromHub(in.OnlineDeploymentRetention, out.OnlineDeploymentRetention)
	}
	if in.OfflineDeploymentRetention == nil {
		out.OfflineDeploymentRetention = nil
	} else {
		out.OfflineDeploymentRetention = &Retention{}
		ConvertRetentionFromHub(in.OfflineDeploymentRetention, out.OfflineDeploymentRetention)
	}
	if in.EndpointRetention == nil {
		out.EndpointRetention = nil
	} else {
		out.EndpointRetention = &Retention{}
		ConvertRetentionFromHub(in.EndpointRetention, out.EndpointRetention)
	}
	if in.ModelRetention == nil {
		out.ModelRetention = nil
	} else {
		out.ModelRetention = &Retention{}
		ConvertRetentionFromHub(in.ModelRetention, out.ModelRetention)
	}
	out.NotificationControl = NotificationControl(int32(in.NotificationControl))
	return nil
}
