apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  namespace: "ma-examples"
  name: "california-housing-xgb"
  annotations:
    michelangelo/uniflow-image: michelangelo-california-housing:local
    michelangelo/uniflow-image-pull-policy: IfNotPresent
spec:
  type: "PIPELINE_TYPE_TRAIN"
  manifest:
    filePath: examples.pipelines.california_housing_xgb.california_housing_xgb
