apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  namespace: "ma-examples"
  name: "california-housing-xgb"
  annotations:
    michelangelo/uniflow-image: california-housing-xgb-local:run-24
    michelangelo/uniflow-image-pull-policy: IfNotPresent
spec:
  type: "PIPELINE_TYPE_TRAIN"
  manifest:
    filePath: examples.pipelines.california_housing_xgb.california_housing_xgb
    uniflowTar: "s3://michelangelo/uniflow/ma-examples_california-housing-xgb.tar.gz"
