load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "blob_storage.go",
        "metadata_storage.go",
        "storage_config.go",
    ],
    importpath = "github.com/michelangelo-ai/michelangelo/go/storage",
    visibility = ["//visibility:public"],
    deps = [
        "//proto/api:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/runtime:go_default_library",
        "@io_k8s_apimachinery//pkg/runtime/schema:go_default_library",
    ],
)
