load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["types.go"],
    importpath = "github.com/michelangelo-ai/michelangelo/go/base/notification/types",
    visibility = ["//visibility:public"],
    deps = [
        "//go/api:go_default_library",
        "//proto/api/v2:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["types_test.go"],
    embed = [":go_default_library"],
    deps = [
        "//go/api:go_default_library",
        "//proto/api:go_default_library",
        "//proto/api/v2:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
    ],
)
