// Code generated by MockGen. DO NOT EDIT.
// Source: mapper.go

// Package typesmocks is a generated GoMock package.
package typesmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/michelangelo-ai/michelangelo/go/components/jobs/common/types"
	v2 "github.com/michelangelo-ai/michelangelo/proto-go/api/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockMapper is a mock of Mapper interface.
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
}

// MockMapperMockRecorder is the mock recorder for MockMapper.
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance.
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// GetLocalName mocks base method.
func (m *MockMapper) GetLocalName(obj runtime.Object) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalName", obj)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetLocalName indicates an expected call of GetLocalName.
func (mr *MockMapperMockRecorder) GetLocalName(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalName", reflect.TypeOf((*MockMapper)(nil).GetLocalName), obj)
}

// MapGlobalJobClusterToLocal mocks base method.
func (m *MockMapper) MapGlobalJobClusterToLocal(jobClusterObject runtime.Object, cluster *v2.Cluster) (runtime.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapGlobalJobClusterToLocal", jobClusterObject, cluster)
	ret0, _ := ret[0].(runtime.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapGlobalJobClusterToLocal indicates an expected call of MapGlobalJobClusterToLocal.
func (mr *MockMapperMockRecorder) MapGlobalJobClusterToLocal(jobClusterObject, cluster interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapGlobalJobClusterToLocal", reflect.TypeOf((*MockMapper)(nil).MapGlobalJobClusterToLocal), jobClusterObject, cluster)
}

// MapGlobalJobToLocal mocks base method.
func (m *MockMapper) MapGlobalJobToLocal(jobObject, jobClusterObject runtime.Object, cluster *v2.Cluster) (runtime.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapGlobalJobToLocal", jobObject, jobClusterObject, cluster)
	ret0, _ := ret[0].(runtime.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapGlobalJobToLocal indicates an expected call of MapGlobalJobToLocal.
func (mr *MockMapperMockRecorder) MapGlobalJobToLocal(jobObject, jobClusterObject, cluster interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapGlobalJobToLocal", reflect.TypeOf((*MockMapper)(nil).MapGlobalJobToLocal), jobObject, jobClusterObject, cluster)
}

// MapLocalClusterStatusToGlobal mocks base method.
func (m *MockMapper) MapLocalClusterStatusToGlobal(localClusterObject runtime.Object) (*types.JobClusterStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapLocalClusterStatusToGlobal", localClusterObject)
	ret0, _ := ret[0].(*types.JobClusterStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapLocalClusterStatusToGlobal indicates an expected call of MapLocalClusterStatusToGlobal.
func (mr *MockMapperMockRecorder) MapLocalClusterStatusToGlobal(localClusterObject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapLocalClusterStatusToGlobal", reflect.TypeOf((*MockMapper)(nil).MapLocalClusterStatusToGlobal), localClusterObject)
}

// MapLocalJobStatusToGlobal mocks base method.
func (m *MockMapper) MapLocalJobStatusToGlobal(localJobObject runtime.Object) (*types.JobStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapLocalJobStatusToGlobal", localJobObject)
	ret0, _ := ret[0].(*types.JobStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapLocalJobStatusToGlobal indicates an expected call of MapLocalJobStatusToGlobal.
func (mr *MockMapperMockRecorder) MapLocalJobStatusToGlobal(localJobObject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapLocalJobStatusToGlobal", reflect.TypeOf((*MockMapper)(nil).MapLocalJobStatusToGlobal), localJobObject)
}
