load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "module.go",
        "temporalclient.go",
    ],
    importpath = "github.com/michelangelo-ai/michelangelo/go/base/workflowclient/temporalclient",
    visibility = ["//visibility:public"],
    deps = [
        "//go/base/config:go_default_library",
        "//go/base/workflowclient/interface:go_default_library",
        "//go/worker/workflowfx:go_default_library",
        "@com_github_cadence_workflow_starlark_worker//temporal:go_default_library",
        "@io_temporal_go_api//common/v1:go_default_library",
        "@io_temporal_go_api//enums/v1:go_default_library",
        "@io_temporal_go_api//filter/v1:go_default_library",
        "@io_temporal_go_api//serviceerror:go_default_library",
        "@io_temporal_go_api//workflowservice/v1:go_default_library",
        "@io_temporal_go_sdk//client:go_default_library",
        "@org_golang_google_protobuf//types/known/timestamppb:go_default_library",
        "@org_uber_go_fx//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "module_test.go",
        "temporalclient_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//go/base/config:go_default_library",
        "//go/base/workflowclient/interface:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//mock:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@io_temporal_go_api//common/v1:go_default_library",
        "@io_temporal_go_api//enums/v1:go_default_library",
        "@io_temporal_go_api//serviceerror:go_default_library",
        "@io_temporal_go_api//workflow/v1:go_default_library",
        "@io_temporal_go_api//workflowservice/v1:go_default_library",
        "@io_temporal_go_sdk//client:go_default_library",
        "@io_temporal_go_sdk//converter:go_default_library",
        "@io_temporal_go_sdk//mocks:go_default_library",
    ],
)
