apiVersion: michelangelo.api/v2
kind: Project
metadata:
  name: ma-dev-test
  namespace: ma-dev-test
  annotations:
    michelangelo/worker_queue: default
spec:
  description: My ML Project
  owner:
    owningTeam: "00000000-0000-0000-0000-000000000001"
    owners:
      - craig.marker
  tier: 4
  gitRepo: https://github.com/uber/michelangelo
  rootDir: python/michelangelo/cli/sandbox/crds
