// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package routingmocks is a generated GoMock package.
package routingmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	routing "github.com/michelangelo-ai/michelangelo/go/components/common/routing"
	dynamic "k8s.io/client-go/dynamic"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddRules mocks base method.
func (m *MockManager) AddRules(ctx context.Context, client dynamic.Interface, name, namespace string, rules ...routing.Rule) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, client, name, namespace}
	for _, a := range rules {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddRules", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRules indicates an expected call of AddRules.
func (mr *MockManagerMockRecorder) AddRules(ctx, client, name, namespace interface{}, rules ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, client, name, namespace}, rules...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRules", reflect.TypeOf((*MockManager)(nil).AddRules), varargs...)
}

// Create mocks base method.
func (m *MockManager) Create(ctx context.Context, client dynamic.Interface, name, namespace string, config routing.RouteConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, client, name, namespace, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockManagerMockRecorder) Create(ctx, client, name, namespace, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockManager)(nil).Create), ctx, client, name, namespace, config)
}

// Delete mocks base method.
func (m *MockManager) Delete(ctx context.Context, client dynamic.Interface, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, client, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagerMockRecorder) Delete(ctx, client, name, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManager)(nil).Delete), ctx, client, name, namespace)
}

// Exists mocks base method.
func (m *MockManager) Exists(ctx context.Context, client dynamic.Interface, name, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, client, name, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockManagerMockRecorder) Exists(ctx, client, name, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockManager)(nil).Exists), ctx, client, name, namespace)
}

// RemoveRules mocks base method.
func (m *MockManager) RemoveRules(ctx context.Context, client dynamic.Interface, name, namespace string, matchPaths ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, client, name, namespace}
	for _, a := range matchPaths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveRules", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRules indicates an expected call of RemoveRules.
func (mr *MockManagerMockRecorder) RemoveRules(ctx, client, name, namespace interface{}, matchPaths ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, client, name, namespace}, matchPaths...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRules", reflect.TypeOf((*MockManager)(nil).RemoveRules), varargs...)
}

// RuleExists mocks base method.
func (m *MockManager) RuleExists(ctx context.Context, client dynamic.Interface, name, namespace string, rule routing.Rule) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuleExists", ctx, client, name, namespace, rule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RuleExists indicates an expected call of RuleExists.
func (mr *MockManagerMockRecorder) RuleExists(ctx, client, name, namespace, rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuleExists", reflect.TypeOf((*MockManager)(nil).RuleExists), ctx, client, name, namespace, rule)
}
