// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go

// Package secretsmocks is a generated GoMock package.
package secretsmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	secrets "github.com/michelangelo-ai/michelangelo/go/components/inferenceserver/clientfactory/secrets"
	v2 "github.com/michelangelo-ai/michelangelo/proto-go/api/v2"
)

// MockSecretProvider is a mock of SecretProvider interface.
type MockSecretProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSecretProviderMockRecorder
}

// MockSecretProviderMockRecorder is the mock recorder for MockSecretProvider.
type MockSecretProviderMockRecorder struct {
	mock *MockSecretProvider
}

// NewMockSecretProvider creates a new mock instance.
func NewMockSecretProvider(ctrl *gomock.Controller) *MockSecretProvider {
	mock := &MockSecretProvider{ctrl: ctrl}
	mock.recorder = &MockSecretProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretProvider) EXPECT() *MockSecretProviderMockRecorder {
	return m.recorder
}

// GetClientAuth mocks base method.
func (m *MockSecretProvider) GetClientAuth(ctx context.Context, cluster *v2.ClusterTarget) (secrets.ClientAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientAuth", ctx, cluster)
	ret0, _ := ret[0].(secrets.ClientAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientAuth indicates an expected call of GetClientAuth.
func (mr *MockSecretProviderMockRecorder) GetClientAuth(ctx, cluster interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientAuth", reflect.TypeOf((*MockSecretProvider)(nil).GetClientAuth), ctx, cluster)
}
