// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/api/v2/conditions.proto

package v2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ConditionStatus int32

const (
	CONDITION_STATUS_UNKNOWN ConditionStatus = 0
	CONDITION_STATUS_TRUE    ConditionStatus = 1
	CONDITION_STATUS_FALSE   ConditionStatus = 2
)

var ConditionStatus_name = map[int32]string{
	0: "CONDITION_STATUS_UNKNOWN",
	1: "CONDITION_STATUS_TRUE",
	2: "CONDITION_STATUS_FALSE",
}

var ConditionStatus_value = map[string]int32{
	"CONDITION_STATUS_UNKNOWN": 0,
	"CONDITION_STATUS_TRUE":    1,
	"CONDITION_STATUS_FALSE":   2,
}

func (ConditionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_86da4f4e5971c5f6, []int{0}
}

type Condition struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status               ConditionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=michelangelo.api.v2.ConditionStatus" json:"status,omitempty"`
	Reason               string          `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastUpdatedTimestamp int64           `protobuf:"varint,5,opt,name=last_updated_timestamp,json=lastUpdatedTimestamp,proto3" json:"lastUpdatedTimestamp,omitempty"`
	Metadata             *types.Any      `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ObservedGeneration   int64           `protobuf:"varint,7,opt,name=observed_generation,json=observedGeneration,proto3" json:"observedGeneration,omitempty"`
}

func (m *Condition) Reset()      { *m = Condition{} }
func (*Condition) ProtoMessage() {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_86da4f4e5971c5f6, []int{0}
}
func (m *Condition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return m.Size()
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Condition) GetStatus() ConditionStatus {
	if m != nil {
		return m.Status
	}
	return CONDITION_STATUS_UNKNOWN
}

func (m *Condition) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Condition) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Condition) GetLastUpdatedTimestamp() int64 {
	if m != nil {
		return m.LastUpdatedTimestamp
	}
	return 0
}

func (m *Condition) GetMetadata() *types.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Condition) GetObservedGeneration() int64 {
	if m != nil {
		return m.ObservedGeneration
	}
	return 0
}

func init() {
	proto.RegisterEnum("michelangelo.api.v2.ConditionStatus", ConditionStatus_name, ConditionStatus_value)
	proto.RegisterType((*Condition)(nil), "michelangelo.api.v2.Condition")
}

func init() {
	proto.RegisterFile("michelangelo/api/v2/conditions.proto", fileDescriptor_86da4f4e5971c5f6)
}

var fileDescriptor_86da4f4e5971c5f6 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x33, 0xd9, 0x35, 0xeb, 0x8e, 0xa0, 0x65, 0x76, 0x2d, 0xb3, 0x8b, 0x0c, 0x41, 0xf6,
	0x10, 0x3c, 0x4c, 0x24, 0xee, 0xd1, 0x4b, 0x5d, 0x57, 0x29, 0x4a, 0x0a, 0xf9, 0x83, 0xe0, 0x25,
	0x4c, 0x9b, 0x69, 0x0c, 0x24, 0x99, 0x90, 0x99, 0x06, 0x7a, 0xf3, 0x23, 0xf8, 0x31, 0xfc, 0x28,
	0x1e, 0x7b, 0xec, 0xd1, 0xa6, 0x17, 0x8f, 0xfd, 0x08, 0xd2, 0xb4, 0x29, 0x62, 0xf7, 0x36, 0x2f,
	0xbf, 0xdf, 0x3c, 0xef, 0xfb, 0xc0, 0x9b, 0x3c, 0x9d, 0x7c, 0xe3, 0x19, 0x2b, 0x12, 0x9e, 0x09,
	0x9b, 0x95, 0xa9, 0x5d, 0x3b, 0xf6, 0x44, 0x14, 0x71, 0xaa, 0x52, 0x51, 0x48, 0x5a, 0x56, 0x42,
	0x09, 0x74, 0xf1, 0xaf, 0x45, 0x59, 0x99, 0xd2, 0xda, 0xb9, 0xbe, 0x4a, 0x84, 0x48, 0x32, 0x6e,
	0xb7, 0xca, 0x78, 0x36, 0xb5, 0x59, 0x31, 0xdf, 0xf9, 0x2f, 0x7f, 0xea, 0xf0, 0xfc, 0xae, 0x0b,
	0x41, 0x08, 0x9e, 0xaa, 0x79, 0xc9, 0x31, 0x30, 0x81, 0x75, 0xee, 0xb5, 0x6f, 0xf4, 0x16, 0x1a,
	0x52, 0x31, 0x35, 0x93, 0x58, 0x37, 0x81, 0xf5, 0xd4, 0xb9, 0xa1, 0x0f, 0xac, 0xa0, 0x87, 0x0c,
	0xbf, 0x75, 0xbd, 0xfd, 0x1f, 0xd4, 0x87, 0x46, 0xc5, 0x99, 0x14, 0x05, 0x3e, 0x69, 0x33, 0xf7,
	0x13, 0xc2, 0xf0, 0x2c, 0xe7, 0x52, 0xb2, 0x84, 0xe3, 0xd3, 0x16, 0x74, 0x23, 0xba, 0x85, 0xfd,
	0x8c, 0x49, 0x15, 0xcd, 0xca, 0x98, 0x29, 0x1e, 0x47, 0x2a, 0xcd, 0xb9, 0x54, 0x2c, 0x2f, 0xf1,
	0x23, 0x13, 0x58, 0x27, 0xde, 0xe5, 0x96, 0x86, 0x3b, 0x18, 0x74, 0x0c, 0xbd, 0x86, 0x8f, 0x73,
	0xae, 0x58, 0xcc, 0x14, 0xc3, 0x86, 0x09, 0xac, 0x27, 0xce, 0x25, 0xdd, 0xb5, 0xa6, 0x5d, 0x6b,
	0x3a, 0x28, 0xe6, 0xde, 0xc1, 0x42, 0x36, 0xbc, 0x10, 0x63, 0xc9, 0xab, 0x9a, 0xc7, 0x51, 0xc2,
	0x0b, 0x5e, 0xb1, 0xed, 0xf9, 0xf8, 0xac, 0x5d, 0x82, 0x3a, 0xf4, 0xf1, 0x40, 0x5e, 0x4d, 0xe1,
	0xb3, 0xff, 0x5a, 0xa2, 0x17, 0x10, 0xdf, 0x8d, 0xdc, 0xf7, 0xc3, 0x60, 0x38, 0x72, 0x23, 0x3f,
	0x18, 0x04, 0xa1, 0x1f, 0x85, 0xee, 0x27, 0x77, 0xf4, 0xc5, 0xed, 0x69, 0xe8, 0x0a, 0x3e, 0x3f,
	0xa2, 0x81, 0x17, 0xde, 0xf7, 0x00, 0xba, 0x86, 0xfd, 0x23, 0xf4, 0x61, 0xf0, 0xd9, 0xbf, 0xef,
	0xe9, 0xef, 0x6e, 0x17, 0x2b, 0xa2, 0x2d, 0x57, 0x44, 0xdb, 0xac, 0x08, 0xf8, 0xde, 0x10, 0xf0,
	0xab, 0x21, 0x60, 0xd1, 0x10, 0xf0, 0xbb, 0x21, 0xe0, 0x4f, 0x43, 0xb4, 0x4d, 0x43, 0xc0, 0x8f,
	0x35, 0xd1, 0x16, 0x6b, 0xa2, 0x2d, 0xd7, 0x44, 0xfb, 0xaa, 0xd7, 0xce, 0xd8, 0x68, 0x6b, 0xbe,
	0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x50, 0xb0, 0xa4, 0x5a, 0x27, 0x02, 0x00, 0x00,
}

func (x ConditionStatus) String() string {
	s, ok := ConditionStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Condition) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&v2.Condition{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Status: "+fmt.Sprintf("%#v", this.Status)+",\n")
	s = append(s, "Reason: "+fmt.Sprintf("%#v", this.Reason)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "LastUpdatedTimestamp: "+fmt.Sprintf("%#v", this.LastUpdatedTimestamp)+",\n")
	if this.Metadata != nil {
		s = append(s, "Metadata: "+fmt.Sprintf("%#v", this.Metadata)+",\n")
	}
	s = append(s, "ObservedGeneration: "+fmt.Sprintf("%#v", this.ObservedGeneration)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringConditions(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Condition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Condition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Condition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ObservedGeneration != 0 {
		i = encodeVarintConditions(dAtA, i, uint64(m.ObservedGeneration))
		i--
		dAtA[i] = 0x38
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConditions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.LastUpdatedTimestamp != 0 {
		i = encodeVarintConditions(dAtA, i, uint64(m.LastUpdatedTimestamp))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintConditions(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintConditions(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = encodeVarintConditions(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintConditions(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConditions(dAtA []byte, offset int, v uint64) int {
	offset -= sovConditions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Condition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovConditions(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovConditions(uint64(m.Status))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovConditions(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovConditions(uint64(l))
	}
	if m.LastUpdatedTimestamp != 0 {
		n += 1 + sovConditions(uint64(m.LastUpdatedTimestamp))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovConditions(uint64(l))
	}
	if m.ObservedGeneration != 0 {
		n += 1 + sovConditions(uint64(m.ObservedGeneration))
	}
	return n
}

func sovConditions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConditions(x uint64) (n int) {
	return sovConditions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Condition) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Condition{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Status:` + fmt.Sprintf("%v", this.Status) + `,`,
		`Reason:` + fmt.Sprintf("%v", this.Reason) + `,`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`LastUpdatedTimestamp:` + fmt.Sprintf("%v", this.LastUpdatedTimestamp) + `,`,
		`Metadata:` + strings.Replace(fmt.Sprintf("%v", this.Metadata), "Any", "types.Any", 1) + `,`,
		`ObservedGeneration:` + fmt.Sprintf("%v", this.ObservedGeneration) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringConditions(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Condition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Condition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Condition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ConditionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedTimestamp", wireType)
			}
			m.LastUpdatedTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &types.Any{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedGeneration", wireType)
			}
			m.ObservedGeneration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedGeneration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConditions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConditions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConditions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConditions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConditions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConditions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConditions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConditions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConditions = fmt.Errorf("proto: unexpected end of group")
)
