// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// createLaneRunRequestValidateExt is an extension hook for additional validation logic
var createLaneRunRequestValidateExt func(*CreateLaneRunRequest, string) error

func (this *CreateLaneRunRequest) Validate(prefix string) error {

	{
		v := this.GetLaneRun()
		n := `lane_run`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetCreateOptions()
		n := `create_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createLaneRunRequestValidateExt != nil {
		if err := createLaneRunRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateLaneRunRequestValidateExt registers an extension validation function
func RegisterCreateLaneRunRequestValidateExt(f func(*CreateLaneRunRequest, string) error) {
	createLaneRunRequestValidateExt = f
}

// createLaneRunResponseValidateExt is an extension hook for additional validation logic
var createLaneRunResponseValidateExt func(*CreateLaneRunResponse, string) error

func (this *CreateLaneRunResponse) Validate(prefix string) error {

	{
		v := this.GetLaneRun()
		n := `lane_run`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createLaneRunResponseValidateExt != nil {
		if err := createLaneRunResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateLaneRunResponseValidateExt registers an extension validation function
func RegisterCreateLaneRunResponseValidateExt(f func(*CreateLaneRunResponse, string) error) {
	createLaneRunResponseValidateExt = f
}

// getLaneRunRequestValidateExt is an extension hook for additional validation logic
var getLaneRunRequestValidateExt func(*GetLaneRunRequest, string) error

func (this *GetLaneRunRequest) Validate(prefix string) error {

	{
		v := this.GetGetOptions()
		n := `get_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getLaneRunRequestValidateExt != nil {
		if err := getLaneRunRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetLaneRunRequestValidateExt registers an extension validation function
func RegisterGetLaneRunRequestValidateExt(f func(*GetLaneRunRequest, string) error) {
	getLaneRunRequestValidateExt = f
}

// getLaneRunResponseValidateExt is an extension hook for additional validation logic
var getLaneRunResponseValidateExt func(*GetLaneRunResponse, string) error

func (this *GetLaneRunResponse) Validate(prefix string) error {

	{
		v := this.GetLaneRun()
		n := `lane_run`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getLaneRunResponseValidateExt != nil {
		if err := getLaneRunResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetLaneRunResponseValidateExt registers an extension validation function
func RegisterGetLaneRunResponseValidateExt(f func(*GetLaneRunResponse, string) error) {
	getLaneRunResponseValidateExt = f
}

// updateLaneRunRequestValidateExt is an extension hook for additional validation logic
var updateLaneRunRequestValidateExt func(*UpdateLaneRunRequest, string) error

func (this *UpdateLaneRunRequest) Validate(prefix string) error {

	{
		v := this.GetLaneRun()
		n := `lane_run`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetUpdateOptions()
		n := `update_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateLaneRunRequestValidateExt != nil {
		if err := updateLaneRunRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateLaneRunRequestValidateExt registers an extension validation function
func RegisterUpdateLaneRunRequestValidateExt(f func(*UpdateLaneRunRequest, string) error) {
	updateLaneRunRequestValidateExt = f
}

// updateLaneRunResponseValidateExt is an extension hook for additional validation logic
var updateLaneRunResponseValidateExt func(*UpdateLaneRunResponse, string) error

func (this *UpdateLaneRunResponse) Validate(prefix string) error {

	{
		v := this.GetLaneRun()
		n := `lane_run`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateLaneRunResponseValidateExt != nil {
		if err := updateLaneRunResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateLaneRunResponseValidateExt registers an extension validation function
func RegisterUpdateLaneRunResponseValidateExt(f func(*UpdateLaneRunResponse, string) error) {
	updateLaneRunResponseValidateExt = f
}

// deleteLaneRunRequestValidateExt is an extension hook for additional validation logic
var deleteLaneRunRequestValidateExt func(*DeleteLaneRunRequest, string) error

func (this *DeleteLaneRunRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteLaneRunRequestValidateExt != nil {
		if err := deleteLaneRunRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteLaneRunRequestValidateExt registers an extension validation function
func RegisterDeleteLaneRunRequestValidateExt(f func(*DeleteLaneRunRequest, string) error) {
	deleteLaneRunRequestValidateExt = f
}

// deleteLaneRunResponseValidateExt is an extension hook for additional validation logic
var deleteLaneRunResponseValidateExt func(*DeleteLaneRunResponse, string) error

func (this *DeleteLaneRunResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteLaneRunResponseValidateExt != nil {
		if err := deleteLaneRunResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteLaneRunResponseValidateExt registers an extension validation function
func RegisterDeleteLaneRunResponseValidateExt(f func(*DeleteLaneRunResponse, string) error) {
	deleteLaneRunResponseValidateExt = f
}

// deleteLaneRunCollectionRequestValidateExt is an extension hook for additional validation logic
var deleteLaneRunCollectionRequestValidateExt func(*DeleteLaneRunCollectionRequest, string) error

func (this *DeleteLaneRunCollectionRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteLaneRunCollectionRequestValidateExt != nil {
		if err := deleteLaneRunCollectionRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteLaneRunCollectionRequestValidateExt registers an extension validation function
func RegisterDeleteLaneRunCollectionRequestValidateExt(f func(*DeleteLaneRunCollectionRequest, string) error) {
	deleteLaneRunCollectionRequestValidateExt = f
}

// deleteLaneRunCollectionResponseValidateExt is an extension hook for additional validation logic
var deleteLaneRunCollectionResponseValidateExt func(*DeleteLaneRunCollectionResponse, string) error

func (this *DeleteLaneRunCollectionResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteLaneRunCollectionResponseValidateExt != nil {
		if err := deleteLaneRunCollectionResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteLaneRunCollectionResponseValidateExt registers an extension validation function
func RegisterDeleteLaneRunCollectionResponseValidateExt(f func(*DeleteLaneRunCollectionResponse, string) error) {
	deleteLaneRunCollectionResponseValidateExt = f
}

// listLaneRunRequestValidateExt is an extension hook for additional validation logic
var listLaneRunRequestValidateExt func(*ListLaneRunRequest, string) error

func (this *ListLaneRunRequest) Validate(prefix string) error {

	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptionsExt()
		n := `list_options_ext`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listLaneRunRequestValidateExt != nil {
		if err := listLaneRunRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListLaneRunRequestValidateExt registers an extension validation function
func RegisterListLaneRunRequestValidateExt(f func(*ListLaneRunRequest, string) error) {
	listLaneRunRequestValidateExt = f
}

// listLaneRunResponseValidateExt is an extension hook for additional validation logic
var listLaneRunResponseValidateExt func(*ListLaneRunResponse, string) error

func (this *ListLaneRunResponse) Validate(prefix string) error {

	{
		v := this.GetLaneRunList()
		n := `lane_run_list`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listLaneRunResponseValidateExt != nil {
		if err := listLaneRunResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListLaneRunResponseValidateExt registers an extension validation function
func RegisterListLaneRunResponseValidateExt(f func(*ListLaneRunResponse, string) error) {
	listLaneRunResponseValidateExt = f
}
