// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// laneRunSpecValidateExt is an extension hook for additional validation logic
var laneRunSpecValidateExt func(*LaneRunSpec, string) error

func (this *LaneRunSpec) Validate(prefix string) error {

	{
		v := this.GetOwner()
		n := `owner`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if laneRunSpecValidateExt != nil {
		if err := laneRunSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterLaneRunSpecValidateExt registers an extension validation function
func RegisterLaneRunSpecValidateExt(f func(*LaneRunSpec, string) error) {
	laneRunSpecValidateExt = f
}

// laneRunStatusValidateExt is an extension hook for additional validation logic
var laneRunStatusValidateExt func(*LaneRunStatus, string) error

func (this *LaneRunStatus) Validate(prefix string) error {

	{
		v := this.GetConditions()
		for i, v := range v {
			n := `conditions[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if laneRunStatusValidateExt != nil {
		if err := laneRunStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterLaneRunStatusValidateExt registers an extension validation function
func RegisterLaneRunStatusValidateExt(f func(*LaneRunStatus, string) error) {
	laneRunStatusValidateExt = f
}

// laneRunValidateExt is an extension hook for additional validation logic
var laneRunValidateExt func(*LaneRun, string) error

func (this *LaneRun) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if laneRunValidateExt != nil {
		if err := laneRunValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterLaneRunValidateExt registers an extension validation function
func RegisterLaneRunValidateExt(f func(*LaneRun, string) error) {
	laneRunValidateExt = f
}

// laneRunListValidateExt is an extension hook for additional validation logic
var laneRunListValidateExt func(*LaneRunList, string) error

func (this *LaneRunList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if laneRunListValidateExt != nil {
		if err := laneRunListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterLaneRunListValidateExt registers an extension validation function
func RegisterLaneRunListValidateExt(f func(*LaneRunList, string) error) {
	laneRunListValidateExt = f
}
