// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/api/v2/lane_run_svc.proto

package v2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	api "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateLaneRunRequest struct {
	LaneRun       *LaneRun              `protobuf:"bytes,1,opt,name=lane_run,json=laneRun,proto3" json:"laneRun,omitempty"`
	CreateOptions *metav1.CreateOptions `protobuf:"bytes,2,opt,name=create_options,json=createOptions,proto3" json:"createOptions,omitempty"`
}

func (m *CreateLaneRunRequest) Reset()      { *m = CreateLaneRunRequest{} }
func (*CreateLaneRunRequest) ProtoMessage() {}
func (*CreateLaneRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{0}
}
func (m *CreateLaneRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateLaneRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateLaneRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateLaneRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaneRunRequest.Merge(m, src)
}
func (m *CreateLaneRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateLaneRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaneRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaneRunRequest proto.InternalMessageInfo

func (m *CreateLaneRunRequest) GetLaneRun() *LaneRun {
	if m != nil {
		return m.LaneRun
	}
	return nil
}

func (m *CreateLaneRunRequest) GetCreateOptions() *metav1.CreateOptions {
	if m != nil {
		return m.CreateOptions
	}
	return nil
}

type CreateLaneRunResponse struct {
	LaneRun *LaneRun `protobuf:"bytes,1,opt,name=lane_run,json=laneRun,proto3" json:"laneRun,omitempty"`
}

func (m *CreateLaneRunResponse) Reset()      { *m = CreateLaneRunResponse{} }
func (*CreateLaneRunResponse) ProtoMessage() {}
func (*CreateLaneRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{1}
}
func (m *CreateLaneRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateLaneRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateLaneRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateLaneRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaneRunResponse.Merge(m, src)
}
func (m *CreateLaneRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateLaneRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaneRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaneRunResponse proto.InternalMessageInfo

func (m *CreateLaneRunResponse) GetLaneRun() *LaneRun {
	if m != nil {
		return m.LaneRun
	}
	return nil
}

type GetLaneRunRequest struct {
	Name       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GetOptions *metav1.GetOptions `protobuf:"bytes,3,opt,name=get_options,json=getOptions,proto3" json:"getOptions,omitempty"`
}

func (m *GetLaneRunRequest) Reset()      { *m = GetLaneRunRequest{} }
func (*GetLaneRunRequest) ProtoMessage() {}
func (*GetLaneRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{2}
}
func (m *GetLaneRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLaneRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLaneRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLaneRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLaneRunRequest.Merge(m, src)
}
func (m *GetLaneRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLaneRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLaneRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLaneRunRequest proto.InternalMessageInfo

func (m *GetLaneRunRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetLaneRunRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetLaneRunRequest) GetGetOptions() *metav1.GetOptions {
	if m != nil {
		return m.GetOptions
	}
	return nil
}

type GetLaneRunResponse struct {
	LaneRun *LaneRun `protobuf:"bytes,1,opt,name=lane_run,json=laneRun,proto3" json:"laneRun,omitempty"`
}

func (m *GetLaneRunResponse) Reset()      { *m = GetLaneRunResponse{} }
func (*GetLaneRunResponse) ProtoMessage() {}
func (*GetLaneRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{3}
}
func (m *GetLaneRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLaneRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLaneRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLaneRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLaneRunResponse.Merge(m, src)
}
func (m *GetLaneRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLaneRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLaneRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLaneRunResponse proto.InternalMessageInfo

func (m *GetLaneRunResponse) GetLaneRun() *LaneRun {
	if m != nil {
		return m.LaneRun
	}
	return nil
}

type UpdateLaneRunRequest struct {
	LaneRun       *LaneRun              `protobuf:"bytes,1,opt,name=lane_run,json=laneRun,proto3" json:"laneRun,omitempty"`
	UpdateOptions *metav1.UpdateOptions `protobuf:"bytes,2,opt,name=update_options,json=updateOptions,proto3" json:"updateOptions,omitempty"`
}

func (m *UpdateLaneRunRequest) Reset()      { *m = UpdateLaneRunRequest{} }
func (*UpdateLaneRunRequest) ProtoMessage() {}
func (*UpdateLaneRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{4}
}
func (m *UpdateLaneRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateLaneRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateLaneRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateLaneRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLaneRunRequest.Merge(m, src)
}
func (m *UpdateLaneRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateLaneRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLaneRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLaneRunRequest proto.InternalMessageInfo

func (m *UpdateLaneRunRequest) GetLaneRun() *LaneRun {
	if m != nil {
		return m.LaneRun
	}
	return nil
}

func (m *UpdateLaneRunRequest) GetUpdateOptions() *metav1.UpdateOptions {
	if m != nil {
		return m.UpdateOptions
	}
	return nil
}

type UpdateLaneRunResponse struct {
	LaneRun *LaneRun `protobuf:"bytes,1,opt,name=lane_run,json=laneRun,proto3" json:"laneRun,omitempty"`
}

func (m *UpdateLaneRunResponse) Reset()      { *m = UpdateLaneRunResponse{} }
func (*UpdateLaneRunResponse) ProtoMessage() {}
func (*UpdateLaneRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{5}
}
func (m *UpdateLaneRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateLaneRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateLaneRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateLaneRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLaneRunResponse.Merge(m, src)
}
func (m *UpdateLaneRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdateLaneRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLaneRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLaneRunResponse proto.InternalMessageInfo

func (m *UpdateLaneRunResponse) GetLaneRun() *LaneRun {
	if m != nil {
		return m.LaneRun
	}
	return nil
}

type DeleteLaneRunRequest struct {
	Name          string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeleteOptions *metav1.DeleteOptions `protobuf:"bytes,3,opt,name=delete_options,json=deleteOptions,proto3" json:"deleteOptions,omitempty"`
}

func (m *DeleteLaneRunRequest) Reset()      { *m = DeleteLaneRunRequest{} }
func (*DeleteLaneRunRequest) ProtoMessage() {}
func (*DeleteLaneRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{6}
}
func (m *DeleteLaneRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteLaneRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteLaneRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteLaneRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLaneRunRequest.Merge(m, src)
}
func (m *DeleteLaneRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteLaneRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLaneRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLaneRunRequest proto.InternalMessageInfo

func (m *DeleteLaneRunRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteLaneRunRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteLaneRunRequest) GetDeleteOptions() *metav1.DeleteOptions {
	if m != nil {
		return m.DeleteOptions
	}
	return nil
}

type DeleteLaneRunResponse struct {
}

func (m *DeleteLaneRunResponse) Reset()      { *m = DeleteLaneRunResponse{} }
func (*DeleteLaneRunResponse) ProtoMessage() {}
func (*DeleteLaneRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{7}
}
func (m *DeleteLaneRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteLaneRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteLaneRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteLaneRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLaneRunResponse.Merge(m, src)
}
func (m *DeleteLaneRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeleteLaneRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLaneRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLaneRunResponse proto.InternalMessageInfo

type DeleteLaneRunCollectionRequest struct {
	Namespace     string                `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeleteOptions *metav1.DeleteOptions `protobuf:"bytes,2,opt,name=delete_options,json=deleteOptions,proto3" json:"deleteOptions,omitempty"`
	ListOptions   *metav1.ListOptions   `protobuf:"bytes,3,opt,name=list_options,json=listOptions,proto3" json:"listOptions,omitempty"`
}

func (m *DeleteLaneRunCollectionRequest) Reset()      { *m = DeleteLaneRunCollectionRequest{} }
func (*DeleteLaneRunCollectionRequest) ProtoMessage() {}
func (*DeleteLaneRunCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{8}
}
func (m *DeleteLaneRunCollectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteLaneRunCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteLaneRunCollectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteLaneRunCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLaneRunCollectionRequest.Merge(m, src)
}
func (m *DeleteLaneRunCollectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteLaneRunCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLaneRunCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLaneRunCollectionRequest proto.InternalMessageInfo

func (m *DeleteLaneRunCollectionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteLaneRunCollectionRequest) GetDeleteOptions() *metav1.DeleteOptions {
	if m != nil {
		return m.DeleteOptions
	}
	return nil
}

func (m *DeleteLaneRunCollectionRequest) GetListOptions() *metav1.ListOptions {
	if m != nil {
		return m.ListOptions
	}
	return nil
}

type DeleteLaneRunCollectionResponse struct {
}

func (m *DeleteLaneRunCollectionResponse) Reset()      { *m = DeleteLaneRunCollectionResponse{} }
func (*DeleteLaneRunCollectionResponse) ProtoMessage() {}
func (*DeleteLaneRunCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{9}
}
func (m *DeleteLaneRunCollectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteLaneRunCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteLaneRunCollectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteLaneRunCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLaneRunCollectionResponse.Merge(m, src)
}
func (m *DeleteLaneRunCollectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeleteLaneRunCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLaneRunCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLaneRunCollectionResponse proto.InternalMessageInfo

type ListLaneRunRequest struct {
	Namespace      string              `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ListOptions    *metav1.ListOptions `protobuf:"bytes,2,opt,name=list_options,json=listOptions,proto3" json:"listOptions,omitempty"`
	ListOptionsExt *api.ListOptionsExt `protobuf:"bytes,3,opt,name=list_options_ext,json=listOptionsExt,proto3" json:"listOptionsExt,omitempty"`
}

func (m *ListLaneRunRequest) Reset()      { *m = ListLaneRunRequest{} }
func (*ListLaneRunRequest) ProtoMessage() {}
func (*ListLaneRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{10}
}
func (m *ListLaneRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListLaneRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListLaneRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListLaneRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLaneRunRequest.Merge(m, src)
}
func (m *ListLaneRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListLaneRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLaneRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLaneRunRequest proto.InternalMessageInfo

func (m *ListLaneRunRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListLaneRunRequest) GetListOptions() *metav1.ListOptions {
	if m != nil {
		return m.ListOptions
	}
	return nil
}

func (m *ListLaneRunRequest) GetListOptionsExt() *api.ListOptionsExt {
	if m != nil {
		return m.ListOptionsExt
	}
	return nil
}

type ListLaneRunResponse struct {
	LaneRunList *LaneRunList `protobuf:"bytes,1,opt,name=lane_run_list,json=laneRunList,proto3" json:"laneRunList,omitempty"`
}

func (m *ListLaneRunResponse) Reset()      { *m = ListLaneRunResponse{} }
func (*ListLaneRunResponse) ProtoMessage() {}
func (*ListLaneRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5904965833da8f29, []int{11}
}
func (m *ListLaneRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListLaneRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListLaneRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListLaneRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLaneRunResponse.Merge(m, src)
}
func (m *ListLaneRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListLaneRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLaneRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLaneRunResponse proto.InternalMessageInfo

func (m *ListLaneRunResponse) GetLaneRunList() *LaneRunList {
	if m != nil {
		return m.LaneRunList
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateLaneRunRequest)(nil), "michelangelo.api.v2.CreateLaneRunRequest")
	proto.RegisterType((*CreateLaneRunResponse)(nil), "michelangelo.api.v2.CreateLaneRunResponse")
	proto.RegisterType((*GetLaneRunRequest)(nil), "michelangelo.api.v2.GetLaneRunRequest")
	proto.RegisterType((*GetLaneRunResponse)(nil), "michelangelo.api.v2.GetLaneRunResponse")
	proto.RegisterType((*UpdateLaneRunRequest)(nil), "michelangelo.api.v2.UpdateLaneRunRequest")
	proto.RegisterType((*UpdateLaneRunResponse)(nil), "michelangelo.api.v2.UpdateLaneRunResponse")
	proto.RegisterType((*DeleteLaneRunRequest)(nil), "michelangelo.api.v2.DeleteLaneRunRequest")
	proto.RegisterType((*DeleteLaneRunResponse)(nil), "michelangelo.api.v2.DeleteLaneRunResponse")
	proto.RegisterType((*DeleteLaneRunCollectionRequest)(nil), "michelangelo.api.v2.DeleteLaneRunCollectionRequest")
	proto.RegisterType((*DeleteLaneRunCollectionResponse)(nil), "michelangelo.api.v2.DeleteLaneRunCollectionResponse")
	proto.RegisterType((*ListLaneRunRequest)(nil), "michelangelo.api.v2.ListLaneRunRequest")
	proto.RegisterType((*ListLaneRunResponse)(nil), "michelangelo.api.v2.ListLaneRunResponse")
}

func init() {
	proto.RegisterFile("michelangelo/api/v2/lane_run_svc.proto", fileDescriptor_5904965833da8f29)
}

var fileDescriptor_5904965833da8f29 = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x52, 0x13, 0x41,
	0x14, 0x4d, 0xc7, 0x27, 0x37, 0x26, 0xa5, 0x0d, 0x14, 0x54, 0xa4, 0x5a, 0x9c, 0x05, 0xa2, 0x8b,
	0x1e, 0x09, 0x54, 0xe9, 0x5a, 0xb0, 0xa8, 0xb2, 0xb0, 0xd4, 0x51, 0x37, 0x58, 0x56, 0x1c, 0x27,
	0x97, 0x30, 0xc5, 0x64, 0x66, 0xcc, 0x74, 0xa6, 0x70, 0xe7, 0xc2, 0x0f, 0x60, 0xe9, 0x07, 0xb8,
	0xf3, 0x47, 0x5c, 0xb2, 0x70, 0xc1, 0x52, 0xc2, 0xc6, 0x25, 0x9f, 0x60, 0xcd, 0x23, 0x93, 0x79,
	0x92, 0x00, 0x59, 0xa5, 0x6f, 0xf7, 0xbd, 0xa7, 0xcf, 0xe9, 0xfb, 0x98, 0xc0, 0x52, 0x47, 0xd7,
	0x76, 0xd1, 0x50, 0xcd, 0x36, 0x1a, 0x96, 0xac, 0xda, 0xba, 0xec, 0x36, 0x64, 0x43, 0x35, 0xb1,
	0xd9, 0xed, 0x99, 0x4d, 0xc7, 0xd5, 0xb8, 0xdd, 0xb5, 0x84, 0x45, 0xa7, 0xe3, 0x7e, 0x5c, 0xb5,
	0x75, 0xee, 0x36, 0xea, 0x6b, 0x7b, 0x4f, 0x1d, 0xae, 0xfb, 0x61, 0x1d, 0x55, 0xdb, 0xd5, 0x4d,
	0xec, 0x7e, 0x95, 0xed, 0xbd, 0xb6, 0xb7, 0xe1, 0xc8, 0x1d, 0x14, 0xaa, 0xec, 0xae, 0xc8, 0x6d,
	0x34, 0xb1, 0xab, 0x0a, 0x6c, 0x05, 0x50, 0xf5, 0xbb, 0x99, 0x2b, 0x0d, 0xdd, 0x11, 0xe1, 0xa1,
	0x74, 0x16, 0x9f, 0xc0, 0x47, 0xfa, 0x45, 0x60, 0x66, 0xbd, 0x8b, 0xaa, 0xc0, 0x2d, 0xd5, 0x44,
	0xa5, 0x67, 0x2a, 0xf8, 0xa5, 0x87, 0x8e, 0xa0, 0x4f, 0xe0, 0xe6, 0xc0, 0x75, 0x9e, 0x2c, 0x92,
	0xe5, 0x4a, 0x63, 0x81, 0xe7, 0xf0, 0xe6, 0x83, 0xb0, 0x1b, 0x46, 0xb0, 0xa0, 0xdb, 0x50, 0xd3,
	0x7c, 0xc0, 0xa6, 0x65, 0x0b, 0xdd, 0x32, 0x9d, 0xf9, 0xb2, 0x1f, 0xbe, 0xca, 0x03, 0x85, 0x3c,
	0xae, 0x90, 0xdb, 0x7b, 0x6d, 0x6f, 0xc3, 0xe1, 0x9e, 0x42, 0xee, 0xae, 0xf0, 0x80, 0xcc, 0xab,
	0x20, 0x54, 0xa9, 0x6a, 0x71, 0x53, 0x7a, 0x0d, 0xb3, 0x29, 0xb2, 0x8e, 0x6d, 0x99, 0x0e, 0x5e,
	0x98, 0xad, 0xf4, 0x83, 0xc0, 0x9d, 0x4d, 0x14, 0x29, 0xf1, 0x14, 0xae, 0x9a, 0x6a, 0x07, 0x7d,
	0xa8, 0x29, 0xc5, 0x5f, 0xd3, 0x05, 0x98, 0xf2, 0x7e, 0x1d, 0x5b, 0xd5, 0xd0, 0x97, 0x34, 0xa5,
	0x0c, 0x37, 0xe8, 0x1b, 0xa8, 0xb4, 0x51, 0x44, 0x92, 0xaf, 0xf8, 0x1c, 0x1e, 0x8f, 0x27, 0x79,
	0x13, 0xc5, 0x40, 0x2f, 0xb4, 0xa3, 0xb5, 0xf4, 0x12, 0x68, 0x9c, 0xd9, 0x65, 0x95, 0x7a, 0x99,
	0x7e, 0x6f, 0xb7, 0x26, 0x9b, 0xe9, 0x9e, 0x0f, 0x78, 0xb1, 0x4c, 0x07, 0x64, 0xa2, 0x4c, 0xf7,
	0xe2, 0xa6, 0x97, 0xe9, 0x14, 0xd9, 0xcb, 0xea, 0xff, 0x49, 0x60, 0x66, 0x03, 0x0d, 0xcc, 0xe8,
	0x3f, 0x7f, 0xb2, 0xb7, 0xa1, 0xd6, 0xf2, 0x91, 0x52, 0xf9, 0x1e, 0x53, 0x78, 0xc0, 0x22, 0x12,
	0xde, 0x8a, 0x9b, 0xd2, 0x1c, 0xcc, 0xa6, 0x58, 0x06, 0xc2, 0xa5, 0x53, 0x02, 0x2c, 0x71, 0xb2,
	0x6e, 0x19, 0x06, 0x6a, 0x5e, 0xd4, 0x40, 0x49, 0x82, 0x35, 0x19, 0xcd, 0xba, 0x3c, 0x29, 0xd6,
	0xf4, 0x1d, 0xdc, 0xf2, 0x06, 0x4f, 0xea, 0x3d, 0x56, 0xc6, 0x43, 0xde, 0xd2, 0x9d, 0xa8, 0x01,
	0x2a, 0xc6, 0xd0, 0x90, 0xee, 0xc3, 0xbd, 0x42, 0xc5, 0xe1, 0xab, 0xfc, 0x21, 0x40, 0xbd, 0xf8,
	0x54, 0x4e, 0xcf, 0x7e, 0x89, 0x34, 0xdb, 0xf2, 0x24, 0xd8, 0xd2, 0x17, 0x70, 0x3b, 0x8e, 0xda,
	0xc4, 0x7d, 0x11, 0xbe, 0xc3, 0x62, 0xb6, 0x42, 0x63, 0x28, 0xcf, 0xf7, 0x85, 0x52, 0x33, 0x12,
	0xb6, 0xf4, 0x01, 0xa6, 0x13, 0xaa, 0xc2, 0xe2, 0xdf, 0x80, 0x6a, 0xf4, 0x3d, 0xf1, 0x22, 0xc2,
	0x0e, 0x58, 0x3c, 0xab, 0x03, 0x3c, 0x1c, 0xa5, 0x62, 0x0c, 0x8d, 0xc6, 0xc1, 0x35, 0xa8, 0x85,
	0x87, 0x6f, 0xb1, 0xeb, 0xea, 0x1a, 0xd2, 0x1d, 0xa8, 0x26, 0x06, 0x2b, 0x7d, 0x98, 0x0b, 0x99,
	0xf7, 0xa5, 0xa8, 0x3f, 0x1a, 0xc7, 0x35, 0x14, 0xf0, 0x11, 0x60, 0x38, 0xd3, 0xe8, 0x52, 0x6e,
	0x64, 0x66, 0x1c, 0xd7, 0x1f, 0x8c, 0xf4, 0x0b, 0xe1, 0x77, 0xa0, 0x9a, 0x98, 0x1a, 0x05, 0x32,
	0xf2, 0xc6, 0x60, 0x81, 0x8c, 0xfc, 0x21, 0xb4, 0x03, 0xd5, 0x44, 0x61, 0x16, 0xdc, 0x93, 0x37,
	0x6e, 0x0a, 0xee, 0xc9, 0xed, 0x79, 0xfa, 0x9d, 0xc0, 0x5c, 0x41, 0x07, 0xd0, 0xd5, 0xd1, 0x38,
	0x99, 0x09, 0x51, 0x5f, 0x3b, 0x5f, 0x50, 0x48, 0xe3, 0x13, 0x54, 0x62, 0xd5, 0x48, 0xf3, 0xd3,
	0x91, 0xed, 0xc2, 0xfa, 0xf2, 0x68, 0xc7, 0xe0, 0x86, 0x67, 0x6b, 0x87, 0xc7, 0xac, 0x74, 0x74,
	0xcc, 0x4a, 0xa7, 0xc7, 0x8c, 0x7c, 0xeb, 0x33, 0xf2, 0xbb, 0xcf, 0xc8, 0x61, 0x9f, 0x91, 0xbf,
	0x7d, 0x46, 0xfe, 0xf5, 0x59, 0xe9, 0xb4, 0xcf, 0xc8, 0xc1, 0x09, 0x2b, 0x1d, 0x9e, 0xb0, 0xd2,
	0xd1, 0x09, 0x2b, 0x6d, 0x97, 0xdd, 0xc6, 0xe7, 0xeb, 0xfe, 0x7f, 0x98, 0xd5, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x8f, 0xd2, 0xf2, 0x7f, 0x79, 0x09, 0x00, 0x00,
}

func (this *CreateLaneRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.CreateLaneRunRequest{")
	if this.LaneRun != nil {
		s = append(s, "LaneRun: "+fmt.Sprintf("%#v", this.LaneRun)+",\n")
	}
	if this.CreateOptions != nil {
		s = append(s, "CreateOptions: "+fmt.Sprintf("%#v", this.CreateOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateLaneRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.CreateLaneRunResponse{")
	if this.LaneRun != nil {
		s = append(s, "LaneRun: "+fmt.Sprintf("%#v", this.LaneRun)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetLaneRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.GetLaneRunRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.GetOptions != nil {
		s = append(s, "GetOptions: "+fmt.Sprintf("%#v", this.GetOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetLaneRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.GetLaneRunResponse{")
	if this.LaneRun != nil {
		s = append(s, "LaneRun: "+fmt.Sprintf("%#v", this.LaneRun)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdateLaneRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.UpdateLaneRunRequest{")
	if this.LaneRun != nil {
		s = append(s, "LaneRun: "+fmt.Sprintf("%#v", this.LaneRun)+",\n")
	}
	if this.UpdateOptions != nil {
		s = append(s, "UpdateOptions: "+fmt.Sprintf("%#v", this.UpdateOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdateLaneRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.UpdateLaneRunResponse{")
	if this.LaneRun != nil {
		s = append(s, "LaneRun: "+fmt.Sprintf("%#v", this.LaneRun)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteLaneRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.DeleteLaneRunRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.DeleteOptions != nil {
		s = append(s, "DeleteOptions: "+fmt.Sprintf("%#v", this.DeleteOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteLaneRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&v2.DeleteLaneRunResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteLaneRunCollectionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.DeleteLaneRunCollectionRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.DeleteOptions != nil {
		s = append(s, "DeleteOptions: "+fmt.Sprintf("%#v", this.DeleteOptions)+",\n")
	}
	if this.ListOptions != nil {
		s = append(s, "ListOptions: "+fmt.Sprintf("%#v", this.ListOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteLaneRunCollectionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&v2.DeleteLaneRunCollectionResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListLaneRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.ListLaneRunRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.ListOptions != nil {
		s = append(s, "ListOptions: "+fmt.Sprintf("%#v", this.ListOptions)+",\n")
	}
	if this.ListOptionsExt != nil {
		s = append(s, "ListOptionsExt: "+fmt.Sprintf("%#v", this.ListOptionsExt)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListLaneRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.ListLaneRunResponse{")
	if this.LaneRunList != nil {
		s = append(s, "LaneRunList: "+fmt.Sprintf("%#v", this.LaneRunList)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringLaneRunSvc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CreateLaneRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateLaneRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateLaneRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateOptions != nil {
		{
			size, err := m.CreateOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.LaneRun != nil {
		{
			size, err := m.LaneRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateLaneRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateLaneRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateLaneRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaneRun != nil {
		{
			size, err := m.LaneRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLaneRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLaneRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLaneRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GetOptions != nil {
		{
			size, err := m.GetOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintLaneRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLaneRunSvc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLaneRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLaneRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLaneRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaneRun != nil {
		{
			size, err := m.LaneRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateLaneRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateLaneRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateLaneRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdateOptions != nil {
		{
			size, err := m.UpdateOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.LaneRun != nil {
		{
			size, err := m.LaneRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateLaneRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateLaneRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateLaneRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaneRun != nil {
		{
			size, err := m.LaneRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteLaneRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteLaneRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteLaneRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeleteOptions != nil {
		{
			size, err := m.DeleteOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintLaneRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLaneRunSvc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteLaneRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteLaneRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteLaneRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *DeleteLaneRunCollectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteLaneRunCollectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteLaneRunCollectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ListOptions != nil {
		{
			size, err := m.ListOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DeleteOptions != nil {
		{
			size, err := m.DeleteOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintLaneRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteLaneRunCollectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteLaneRunCollectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteLaneRunCollectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListLaneRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListLaneRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListLaneRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ListOptionsExt != nil {
		{
			size, err := m.ListOptionsExt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ListOptions != nil {
		{
			size, err := m.ListOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintLaneRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListLaneRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListLaneRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListLaneRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaneRunList != nil {
		{
			size, err := m.LaneRunList.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLaneRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLaneRunSvc(dAtA []byte, offset int, v uint64) int {
	offset -= sovLaneRunSvc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateLaneRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaneRun != nil {
		l = m.LaneRun.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.CreateOptions != nil {
		l = m.CreateOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *CreateLaneRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaneRun != nil {
		l = m.LaneRun.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *GetLaneRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.GetOptions != nil {
		l = m.GetOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *GetLaneRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaneRun != nil {
		l = m.LaneRun.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *UpdateLaneRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaneRun != nil {
		l = m.LaneRun.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.UpdateOptions != nil {
		l = m.UpdateOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *UpdateLaneRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaneRun != nil {
		l = m.LaneRun.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *DeleteLaneRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.DeleteOptions != nil {
		l = m.DeleteOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *DeleteLaneRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *DeleteLaneRunCollectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.DeleteOptions != nil {
		l = m.DeleteOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.ListOptions != nil {
		l = m.ListOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *DeleteLaneRunCollectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListLaneRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.ListOptions != nil {
		l = m.ListOptions.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	if m.ListOptionsExt != nil {
		l = m.ListOptionsExt.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func (m *ListLaneRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaneRunList != nil {
		l = m.LaneRunList.Size()
		n += 1 + l + sovLaneRunSvc(uint64(l))
	}
	return n
}

func sovLaneRunSvc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLaneRunSvc(x uint64) (n int) {
	return sovLaneRunSvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CreateLaneRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateLaneRunRequest{`,
		`LaneRun:` + strings.Replace(fmt.Sprintf("%v", this.LaneRun), "LaneRun", "LaneRun", 1) + `,`,
		`CreateOptions:` + strings.Replace(fmt.Sprintf("%v", this.CreateOptions), "CreateOptions", "v1.CreateOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateLaneRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateLaneRunResponse{`,
		`LaneRun:` + strings.Replace(fmt.Sprintf("%v", this.LaneRun), "LaneRun", "LaneRun", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetLaneRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetLaneRunRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`GetOptions:` + strings.Replace(fmt.Sprintf("%v", this.GetOptions), "GetOptions", "v1.GetOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetLaneRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetLaneRunResponse{`,
		`LaneRun:` + strings.Replace(fmt.Sprintf("%v", this.LaneRun), "LaneRun", "LaneRun", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateLaneRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateLaneRunRequest{`,
		`LaneRun:` + strings.Replace(fmt.Sprintf("%v", this.LaneRun), "LaneRun", "LaneRun", 1) + `,`,
		`UpdateOptions:` + strings.Replace(fmt.Sprintf("%v", this.UpdateOptions), "UpdateOptions", "v1.UpdateOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateLaneRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateLaneRunResponse{`,
		`LaneRun:` + strings.Replace(fmt.Sprintf("%v", this.LaneRun), "LaneRun", "LaneRun", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteLaneRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteLaneRunRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`DeleteOptions:` + strings.Replace(fmt.Sprintf("%v", this.DeleteOptions), "DeleteOptions", "v1.DeleteOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteLaneRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteLaneRunResponse{`,
		`}`,
	}, "")
	return s
}
func (this *DeleteLaneRunCollectionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteLaneRunCollectionRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`DeleteOptions:` + strings.Replace(fmt.Sprintf("%v", this.DeleteOptions), "DeleteOptions", "v1.DeleteOptions", 1) + `,`,
		`ListOptions:` + strings.Replace(fmt.Sprintf("%v", this.ListOptions), "ListOptions", "v1.ListOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteLaneRunCollectionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteLaneRunCollectionResponse{`,
		`}`,
	}, "")
	return s
}
func (this *ListLaneRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListLaneRunRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`ListOptions:` + strings.Replace(fmt.Sprintf("%v", this.ListOptions), "ListOptions", "v1.ListOptions", 1) + `,`,
		`ListOptionsExt:` + strings.Replace(fmt.Sprintf("%v", this.ListOptionsExt), "ListOptionsExt", "api.ListOptionsExt", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListLaneRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListLaneRunResponse{`,
		`LaneRunList:` + strings.Replace(fmt.Sprintf("%v", this.LaneRunList), "LaneRunList", "LaneRunList", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringLaneRunSvc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CreateLaneRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateLaneRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateLaneRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaneRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LaneRun == nil {
				m.LaneRun = &LaneRun{}
			}
			if err := m.LaneRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreateOptions == nil {
				m.CreateOptions = &metav1.CreateOptions{}
			}
			if err := m.CreateOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateLaneRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateLaneRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateLaneRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaneRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LaneRun == nil {
				m.LaneRun = &LaneRun{}
			}
			if err := m.LaneRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLaneRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLaneRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLaneRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GetOptions == nil {
				m.GetOptions = &metav1.GetOptions{}
			}
			if err := m.GetOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLaneRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLaneRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLaneRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaneRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LaneRun == nil {
				m.LaneRun = &LaneRun{}
			}
			if err := m.LaneRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateLaneRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateLaneRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateLaneRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaneRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LaneRun == nil {
				m.LaneRun = &LaneRun{}
			}
			if err := m.LaneRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateOptions == nil {
				m.UpdateOptions = &metav1.UpdateOptions{}
			}
			if err := m.UpdateOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateLaneRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateLaneRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateLaneRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaneRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LaneRun == nil {
				m.LaneRun = &LaneRun{}
			}
			if err := m.LaneRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteLaneRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteLaneRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteLaneRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeleteOptions == nil {
				m.DeleteOptions = &metav1.DeleteOptions{}
			}
			if err := m.DeleteOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteLaneRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteLaneRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteLaneRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteLaneRunCollectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteLaneRunCollectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteLaneRunCollectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeleteOptions == nil {
				m.DeleteOptions = &metav1.DeleteOptions{}
			}
			if err := m.DeleteOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptions == nil {
				m.ListOptions = &metav1.ListOptions{}
			}
			if err := m.ListOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteLaneRunCollectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteLaneRunCollectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteLaneRunCollectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListLaneRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListLaneRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListLaneRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptions == nil {
				m.ListOptions = &metav1.ListOptions{}
			}
			if err := m.ListOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptionsExt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptionsExt == nil {
				m.ListOptionsExt = &api.ListOptionsExt{}
			}
			if err := m.ListOptionsExt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListLaneRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListLaneRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListLaneRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaneRunList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LaneRunList == nil {
				m.LaneRunList = &LaneRunList{}
			}
			if err := m.LaneRunList.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaneRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaneRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLaneRunSvc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLaneRunSvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLaneRunSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLaneRunSvc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLaneRunSvc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLaneRunSvc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLaneRunSvc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLaneRunSvc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLaneRunSvc = fmt.Errorf("proto: unexpected end of group")
)
