// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// revisionSpecValidateExt is an extension hook for additional validation logic
var revisionSpecValidateExt func(*RevisionSpec, string) error

func (this *RevisionSpec) Validate(prefix string) error {

	{
		v := this.GetBaseType()
		n := `base_type`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetBaseResource()
		n := `base_resource`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetContent()
		n := `content`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetOwner()
		n := `owner`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetParent()
		n := `parent`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.Source
		n := `source`
		if len(v) == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be empty")
		}
	}
	{
		v := this.GetGitCommit()
		n := `git_commit`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if revisionSpecValidateExt != nil {
		if err := revisionSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterRevisionSpecValidateExt registers an extension validation function
func RegisterRevisionSpecValidateExt(f func(*RevisionSpec, string) error) {
	revisionSpecValidateExt = f
}

// revisionStatusValidateExt is an extension hook for additional validation logic
var revisionStatusValidateExt func(*RevisionStatus, string) error

func (this *RevisionStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if revisionStatusValidateExt != nil {
		if err := revisionStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterRevisionStatusValidateExt registers an extension validation function
func RegisterRevisionStatusValidateExt(f func(*RevisionStatus, string) error) {
	revisionStatusValidateExt = f
}

// revisionValidateExt is an extension hook for additional validation logic
var revisionValidateExt func(*Revision, string) error

func (this *Revision) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if revisionValidateExt != nil {
		if err := revisionValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterRevisionValidateExt registers an extension validation function
func RegisterRevisionValidateExt(f func(*Revision, string) error) {
	revisionValidateExt = f
}

// revisionListValidateExt is an extension hook for additional validation logic
var revisionListValidateExt func(*RevisionList, string) error

func (this *RevisionList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if revisionListValidateExt != nil {
		if err := revisionListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterRevisionListValidateExt registers an extension validation function
func RegisterRevisionListValidateExt(f func(*RevisionList, string) error) {
	revisionListValidateExt = f
}
