// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// timeRangeValidateExt is an extension hook for additional validation logic
var timeRangeValidateExt func(*TimeRange, string) error

func (this *TimeRange) Validate(prefix string) error {

	{
		v := this.GetStart()
		n := `start`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetEnd()
		n := `end`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetDurationFromNow()
		n := `duration_from_now`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if timeRangeValidateExt != nil {
		if err := timeRangeValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTimeRangeValidateExt registers an extension validation function
func RegisterTimeRangeValidateExt(f func(*TimeRange, string) error) {
	timeRangeValidateExt = f
}

// durationValidateExt is an extension hook for additional validation logic
var durationValidateExt func(*Duration, string) error

func (this *Duration) Validate(prefix string) error {

	// Call extension validation if registered
	if durationValidateExt != nil {
		if err := durationValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDurationValidateExt registers an extension validation function
func RegisterDurationValidateExt(f func(*Duration, string) error) {
	durationValidateExt = f
}
