// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/api/v2/time.proto

package v2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TimeUnit int32

const (
	TIME_UNIT_INVALID TimeUnit = 0
	TIME_UNIT_YEAR    TimeUnit = 1
	TIME_UNIT_QUARTER TimeUnit = 2
	TIME_UNIT_MONTH   TimeUnit = 3
	TIME_UNIT_WEEK    TimeUnit = 4
	TIME_UNIT_DAY     TimeUnit = 5
	TIME_UNIT_HOUR    TimeUnit = 6
	TIME_UNIT_MINUTE  TimeUnit = 7
	TIME_UNIT_SECOND  TimeUnit = 8
)

var TimeUnit_name = map[int32]string{
	0: "TIME_UNIT_INVALID",
	1: "TIME_UNIT_YEAR",
	2: "TIME_UNIT_QUARTER",
	3: "TIME_UNIT_MONTH",
	4: "TIME_UNIT_WEEK",
	5: "TIME_UNIT_DAY",
	6: "TIME_UNIT_HOUR",
	7: "TIME_UNIT_MINUTE",
	8: "TIME_UNIT_SECOND",
}

var TimeUnit_value = map[string]int32{
	"TIME_UNIT_INVALID": 0,
	"TIME_UNIT_YEAR":    1,
	"TIME_UNIT_QUARTER": 2,
	"TIME_UNIT_MONTH":   3,
	"TIME_UNIT_WEEK":    4,
	"TIME_UNIT_DAY":     5,
	"TIME_UNIT_HOUR":    6,
	"TIME_UNIT_MINUTE":  7,
	"TIME_UNIT_SECOND":  8,
}

func (TimeUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_396fb3a4b97de9c4, []int{0}
}

type TimeRange struct {
	Start           *types.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End             *types.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	DurationFromNow *types.Duration  `protobuf:"bytes,3,opt,name=duration_from_now,json=durationFromNow,proto3" json:"durationFromNow,omitempty"`
}

func (m *TimeRange) Reset()      { *m = TimeRange{} }
func (*TimeRange) ProtoMessage() {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_396fb3a4b97de9c4, []int{0}
}
func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return m.Size()
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetStart() *types.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *TimeRange) GetEnd() *types.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *TimeRange) GetDurationFromNow() *types.Duration {
	if m != nil {
		return m.DurationFromNow
	}
	return nil
}

type Duration struct {
	Num  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Unit TimeUnit `protobuf:"varint,2,opt,name=unit,proto3,enum=michelangelo.api.v2.TimeUnit" json:"unit,omitempty"`
}

func (m *Duration) Reset()      { *m = Duration{} }
func (*Duration) ProtoMessage() {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_396fb3a4b97de9c4, []int{1}
}
func (m *Duration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return m.Size()
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Duration) GetUnit() TimeUnit {
	if m != nil {
		return m.Unit
	}
	return TIME_UNIT_INVALID
}

func init() {
	proto.RegisterEnum("michelangelo.api.v2.TimeUnit", TimeUnit_name, TimeUnit_value)
	proto.RegisterType((*TimeRange)(nil), "michelangelo.api.v2.TimeRange")
	proto.RegisterType((*Duration)(nil), "michelangelo.api.v2.Duration")
}

func init() { proto.RegisterFile("michelangelo/api/v2/time.proto", fileDescriptor_396fb3a4b97de9c4) }

var fileDescriptor_396fb3a4b97de9c4 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0xe3, 0x66, 0x1b, 0xc5, 0x88, 0xcd, 0xf5, 0x40, 0x2a, 0x95, 0x30, 0x68, 0x27, 0x84,
	0x50, 0x02, 0x81, 0x17, 0x08, 0xc4, 0x68, 0x11, 0x2c, 0x11, 0x26, 0x01, 0x8d, 0x4b, 0x94, 0xb1,
	0xb4, 0x58, 0x6a, 0xe2, 0x28, 0x75, 0xda, 0x2b, 0x8f, 0xc0, 0xb3, 0xf0, 0x14, 0x3d, 0xf6, 0xd8,
	0x23, 0x4d, 0x2f, 0x1c, 0xfb, 0x08, 0xa8, 0x0e, 0x51, 0x1b, 0x40, 0xe2, 0x66, 0xfd, 0xbf, 0xdf,
	0xef, 0xf3, 0x5f, 0x1f, 0x24, 0x29, 0xff, 0xfc, 0x25, 0x19, 0xc7, 0xd9, 0x28, 0x19, 0x0b, 0x33,
	0xce, 0xb9, 0x39, 0xb5, 0x4c, 0xc9, 0xd3, 0xc4, 0xc8, 0x0b, 0x21, 0x05, 0x3e, 0xdd, 0x9f, 0x1b,
	0x71, 0xce, 0x8d, 0xa9, 0x35, 0x78, 0x30, 0x12, 0x62, 0x34, 0x4e, 0x4c, 0x85, 0x5c, 0x95, 0x43,
	0x25, 0x4c, 0x64, 0x9c, 0xe6, 0xb5, 0x35, 0x20, 0x7f, 0x02, 0xd7, 0x65, 0x11, 0x4b, 0x2e, 0xb2,
	0x7a, 0x7e, 0xf6, 0x1d, 0xc0, 0x9b, 0x01, 0x4f, 0x13, 0xb6, 0xdd, 0x8b, 0x9f, 0xc2, 0xc3, 0x89,
	0x8c, 0x0b, 0xd9, 0x07, 0x0f, 0xc1, 0xa3, 0x5b, 0xd6, 0xc0, 0xa8, 0x6d, 0xa3, 0xb1, 0x8d, 0xa0,
	0x59, 0xcf, 0x6a, 0x10, 0x3f, 0x81, 0x7a, 0x92, 0x5d, 0xf7, 0x3b, 0xff, 0xe5, 0xb7, 0x18, 0xa6,
	0xb0, 0xd7, 0xfc, 0x1f, 0x0d, 0x0b, 0x91, 0x46, 0x99, 0x98, 0xf5, 0x75, 0xe5, 0xde, 0xfb, 0xcb,
	0x75, 0x7e, 0x93, 0xec, 0xa4, 0x71, 0x5e, 0x17, 0x22, 0xf5, 0xc4, 0xec, 0xcc, 0x87, 0xdd, 0x66,
	0x88, 0x11, 0xd4, 0xb3, 0x32, 0x55, 0x85, 0x75, 0xb6, 0x7d, 0xe2, 0x67, 0xf0, 0xa0, 0xcc, 0xb8,
	0x54, 0x9d, 0x8e, 0xad, 0xfb, 0xc6, 0x3f, 0xee, 0xa6, 0x7a, 0x85, 0x19, 0x97, 0x4c, 0xa1, 0x8f,
	0xe7, 0x00, 0x76, 0x9b, 0x08, 0xdf, 0x85, 0xbd, 0xc0, 0xbd, 0xa0, 0x51, 0xe8, 0xb9, 0x41, 0xe4,
	0x7a, 0x1f, 0xec, 0xb7, 0xae, 0x83, 0x34, 0x8c, 0xe1, 0xf1, 0x2e, 0xbe, 0xa4, 0x36, 0x43, 0xa0,
	0x8d, 0xbe, 0x0b, 0x6d, 0x16, 0x50, 0x86, 0x3a, 0xf8, 0x14, 0x9e, 0xec, 0xe2, 0x0b, 0xdf, 0x0b,
	0xce, 0x91, 0xde, 0xf6, 0x3f, 0x52, 0xfa, 0x06, 0x1d, 0xe0, 0x1e, 0xbc, 0xbd, 0xcb, 0x1c, 0xfb,
	0x12, 0x1d, 0xb6, 0xb1, 0x73, 0x3f, 0x64, 0xe8, 0x08, 0xdf, 0x81, 0x68, 0x6f, 0x9f, 0xeb, 0x85,
	0x01, 0x45, 0x37, 0xda, 0xe9, 0x7b, 0xfa, 0xca, 0xf7, 0x1c, 0xd4, 0x7d, 0xf9, 0x62, 0xb1, 0x22,
	0xda, 0x72, 0x45, 0xb4, 0xcd, 0x8a, 0x80, 0xaf, 0x15, 0x01, 0xf3, 0x8a, 0x80, 0x45, 0x45, 0xc0,
	0x8f, 0x8a, 0x80, 0x9f, 0x15, 0xd1, 0x36, 0x15, 0x01, 0xdf, 0xd6, 0x44, 0x5b, 0xac, 0x89, 0xb6,
	0x5c, 0x13, 0xed, 0x53, 0x67, 0x6a, 0x5d, 0x1d, 0xa9, 0xab, 0x3f, 0xff, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x17, 0xb1, 0xd4, 0xbb, 0x85, 0x02, 0x00, 0x00,
}

func (x TimeUnit) String() string {
	s, ok := TimeUnit_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *TimeRange) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.TimeRange{")
	if this.Start != nil {
		s = append(s, "Start: "+fmt.Sprintf("%#v", this.Start)+",\n")
	}
	if this.End != nil {
		s = append(s, "End: "+fmt.Sprintf("%#v", this.End)+",\n")
	}
	if this.DurationFromNow != nil {
		s = append(s, "DurationFromNow: "+fmt.Sprintf("%#v", this.DurationFromNow)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Duration) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.Duration{")
	s = append(s, "Num: "+fmt.Sprintf("%#v", this.Num)+",\n")
	s = append(s, "Unit: "+fmt.Sprintf("%#v", this.Unit)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTime(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TimeRange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TimeRange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TimeRange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DurationFromNow != nil {
		{
			size, err := m.DurationFromNow.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTime(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.End != nil {
		{
			size, err := m.End.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTime(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Start != nil {
		{
			size, err := m.Start.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTime(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Duration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Duration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Duration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Unit != 0 {
		i = encodeVarintTime(dAtA, i, uint64(m.Unit))
		i--
		dAtA[i] = 0x10
	}
	if m.Num != 0 {
		i = encodeVarintTime(dAtA, i, uint64(m.Num))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTime(dAtA []byte, offset int, v uint64) int {
	offset -= sovTime(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TimeRange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Start != nil {
		l = m.Start.Size()
		n += 1 + l + sovTime(uint64(l))
	}
	if m.End != nil {
		l = m.End.Size()
		n += 1 + l + sovTime(uint64(l))
	}
	if m.DurationFromNow != nil {
		l = m.DurationFromNow.Size()
		n += 1 + l + sovTime(uint64(l))
	}
	return n
}

func (m *Duration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Num != 0 {
		n += 1 + sovTime(uint64(m.Num))
	}
	if m.Unit != 0 {
		n += 1 + sovTime(uint64(m.Unit))
	}
	return n
}

func sovTime(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTime(x uint64) (n int) {
	return sovTime(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TimeRange) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TimeRange{`,
		`Start:` + strings.Replace(fmt.Sprintf("%v", this.Start), "Timestamp", "types.Timestamp", 1) + `,`,
		`End:` + strings.Replace(fmt.Sprintf("%v", this.End), "Timestamp", "types.Timestamp", 1) + `,`,
		`DurationFromNow:` + strings.Replace(fmt.Sprintf("%v", this.DurationFromNow), "Duration", "types.Duration", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Duration) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Duration{`,
		`Num:` + fmt.Sprintf("%v", this.Num) + `,`,
		`Unit:` + fmt.Sprintf("%v", this.Unit) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTime(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TimeRange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTime
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TimeRange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TimeRange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTime
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTime
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTime
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Start == nil {
				m.Start = &types.Timestamp{}
			}
			if err := m.Start.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTime
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTime
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTime
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.End == nil {
				m.End = &types.Timestamp{}
			}
			if err := m.End.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationFromNow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTime
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTime
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTime
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DurationFromNow == nil {
				m.DurationFromNow = &types.Duration{}
			}
			if err := m.DurationFromNow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTime(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTime
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Duration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTime
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Duration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Duration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTime
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			m.Unit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTime
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Unit |= TimeUnit(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTime(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTime
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTime(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTime
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTime
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTime
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTime
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTime
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTime
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTime        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTime          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTime = fmt.Errorf("proto: unexpected end of group")
)
