// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// cronScheduleValidateExt is an extension hook for additional validation logic
var cronScheduleValidateExt func(*CronSchedule, string) error

func (this *CronSchedule) Validate(prefix string) error {

	// Call extension validation if registered
	if cronScheduleValidateExt != nil {
		if err := cronScheduleValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCronScheduleValidateExt registers an extension validation function
func RegisterCronScheduleValidateExt(f func(*CronSchedule, string) error) {
	cronScheduleValidateExt = f
}

// intervalScheduleValidateExt is an extension hook for additional validation logic
var intervalScheduleValidateExt func(*IntervalSchedule, string) error

func (this *IntervalSchedule) Validate(prefix string) error {

	{
		v := this.GetInterval()
		n := `interval`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if intervalScheduleValidateExt != nil {
		if err := intervalScheduleValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterIntervalScheduleValidateExt registers an extension validation function
func RegisterIntervalScheduleValidateExt(f func(*IntervalSchedule, string) error) {
	intervalScheduleValidateExt = f
}

// batchPolicyValidateExt is an extension hook for additional validation logic
var batchPolicyValidateExt func(*BatchPolicy, string) error

func (this *BatchPolicy) Validate(prefix string) error {

	{
		v := this.GetWait()
		n := `wait`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if batchPolicyValidateExt != nil {
		if err := batchPolicyValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterBatchPolicyValidateExt registers an extension validation function
func RegisterBatchPolicyValidateExt(f func(*BatchPolicy, string) error) {
	batchPolicyValidateExt = f
}

// triggerValidateExt is an extension hook for additional validation logic
var triggerValidateExt func(*Trigger, string) error

func (this *Trigger) Validate(prefix string) error {

	if f, ok := this.TriggerType.(*Trigger_CronSchedule); ok {
		v := f.CronSchedule
		n := `cron_schedule`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	if f, ok := this.TriggerType.(*Trigger_BatchRerun); ok {
		v := f.BatchRerun
		n := `batch_rerun`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	if f, ok := this.TriggerType.(*Trigger_IntervalSchedule); ok {
		v := f.IntervalSchedule
		n := `interval_schedule`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetParametersMap()
		for k, v := range v {
			n := fmt.Sprintf(`parameters_map[%v]`, k)

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	{
		v := this.GetBatchPolicy()
		n := `batch_policy`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if triggerValidateExt != nil {
		if err := triggerValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTriggerValidateExt registers an extension validation function
func RegisterTriggerValidateExt(f func(*Trigger, string) error) {
	triggerValidateExt = f
}

// triggerRunSpecValidateExt is an extension hook for additional validation logic
var triggerRunSpecValidateExt func(*TriggerRunSpec, string) error

func (this *TriggerRunSpec) Validate(prefix string) error {

	{
		v := this.GetPipeline()
		n := `pipeline`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetRevision()
		n := `revision`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetTrigger()
		n := `trigger`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetActor()
		n := `actor`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStartTimestamp()
		n := `start_timestamp`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetEndTimestamp()
		n := `end_timestamp`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetNotifications()
		for i, v := range v {
			n := `notifications[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if triggerRunSpecValidateExt != nil {
		if err := triggerRunSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTriggerRunSpecValidateExt registers an extension validation function
func RegisterTriggerRunSpecValidateExt(f func(*TriggerRunSpec, string) error) {
	triggerRunSpecValidateExt = f
}

// batchRerunValidateExt is an extension hook for additional validation logic
var batchRerunValidateExt func(*BatchRerun, string) error

func (this *BatchRerun) Validate(prefix string) error {

	{
		v := this.GetPipelineRuns()
		n := `pipeline_runs`
		if len(v) == 0 {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"cannot be empty")
		}
		for i, v := range v {
			n := `pipeline_runs[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if batchRerunValidateExt != nil {
		if err := batchRerunValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterBatchRerunValidateExt registers an extension validation function
func RegisterBatchRerunValidateExt(f func(*BatchRerun, string) error) {
	batchRerunValidateExt = f
}

// triggerRunStatusValidateExt is an extension hook for additional validation logic
var triggerRunStatusValidateExt func(*TriggerRunStatus, string) error

func (this *TriggerRunStatus) Validate(prefix string) error {

	{
		v := this.GetActualNotifications()
		for i, v := range v {
			n := `actual_notifications[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	{
		v := this.GetActualTrigger()
		n := `actual_trigger`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if triggerRunStatusValidateExt != nil {
		if err := triggerRunStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTriggerRunStatusValidateExt registers an extension validation function
func RegisterTriggerRunStatusValidateExt(f func(*TriggerRunStatus, string) error) {
	triggerRunStatusValidateExt = f
}

// triggerRunValidateExt is an extension hook for additional validation logic
var triggerRunValidateExt func(*TriggerRun, string) error

func (this *TriggerRun) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if triggerRunValidateExt != nil {
		if err := triggerRunValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTriggerRunValidateExt registers an extension validation function
func RegisterTriggerRunValidateExt(f func(*TriggerRun, string) error) {
	triggerRunValidateExt = f
}

// triggerRunListValidateExt is an extension hook for additional validation logic
var triggerRunListValidateExt func(*TriggerRunList, string) error

func (this *TriggerRunList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if triggerRunListValidateExt != nil {
		if err := triggerRunListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTriggerRunListValidateExt registers an extension validation function
func RegisterTriggerRunListValidateExt(f func(*TriggerRunList, string) error) {
	triggerRunListValidateExt = f
}
