// Code generated by protoc-gen-kubeconversion. DO NOT EDIT.
package v1

import (
	v2 "github.com/michelangelo-ai/michelangelo/proto-go/test/kubeproto/conversion/v2"
	conversion1 "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	conversion "sigs.k8s.io/controller-runtime/pkg/conversion"
)

func ConvertM1ToHub(in *M1, out *v2.M1) error {
	if in == nil {
		return nil
	}
	if in.F1 == nil {
		out.F1 = nil
	} else {
		out.F1 = []v2.E1{}
	}
	for _, v := range in.F1 {
		out.F1 = append(out.F1, v2.E1(int32(v)))
	}
	if in.F2 == nil {
		out.F2 = nil
	} else {
		out.F2 = make(map[string]string, len(in.F2))
		for k, v := range in.F2 {
			out.F2[k] = v
		}
	}
	if in.F3 == nil {
		out.F3 = nil
	} else {
		out.F3 = make(map[string]v2.E1, len(in.F3))
		for k, v := range in.F3 {
			out.F3[k] = v2.E1(int32(v))
		}
	}
	return nil
}

func ConvertM1FromHub(in *v2.M1, out *M1) error {
	if in == nil {
		return nil
	}
	if in.F1 == nil {
		out.F1 = nil
	} else {
		out.F1 = []E1{}
	}
	for _, v := range in.F1 {
		out.F1 = append(out.F1, E1(int32(v)))
	}
	if in.F2 == nil {
		out.F2 = nil
	} else {
		out.F2 = make(map[string]string, len(in.F2))
		for k, v := range in.F2 {
			out.F2[k] = v
		}
	}
	if in.F3 == nil {
		out.F3 = nil
	} else {
		out.F3 = make(map[string]E1, len(in.F3))
		for k, v := range in.F3 {
			out.F3[k] = E1(int32(v))
		}
	}
	return nil
}

func ConvertM2ToHub(in *M2, out *v2.M2) error {
	if in == nil {
		return nil
	}
	if in.F1 == nil {
		out.F1 = nil
	} else {
		if in.F1 == nil {
			out.F1 = nil
		} else {
			out.F1 = []*v2.M3{}
		}
		for _, v := range in.F1 {
			t := &v2.M3{}
			ConvertM3ToHub(v, t)
			out.F1 = append(out.F1, t)
		}
	}
	return nil
}

func ConvertM2FromHub(in *v2.M2, out *M2) error {
	if in == nil {
		return nil
	}
	if in.F1 == nil {
		out.F1 = nil
	} else {
		if in.F1 == nil {
			out.F1 = nil
		} else {
			out.F1 = []*M3{}
		}
		for _, v := range in.F1 {
			t := &M3{}
			ConvertM3FromHub(v, t)
			out.F1 = append(out.F1, t)
		}
	}
	return nil
}

func ConvertM3ToHub(in *M3, out *v2.M3) error {
	if in == nil {
		return nil
	}
	if in.F1 == nil {
		out.F1 = nil
	} else {
		out.F1 = []v2.E2{}
	}
	for _, v := range in.F1 {
		out.F1 = append(out.F1, v2.E2(int32(v)))
	}
	return nil
}

func ConvertM3FromHub(in *v2.M3, out *M3) error {
	if in == nil {
		return nil
	}
	if in.F1 == nil {
		out.F1 = nil
	} else {
		out.F1 = []E2{}
	}
	for _, v := range in.F1 {
		out.F1 = append(out.F1, E2(int32(v)))
	}
	return nil
}

type CustomTestObjectConvertor interface {
	ConvertToHub(src *TestObject, dst *v2.TestObject) error
	ConvertFromHub(src *v2.TestObject, dst *TestObject) error
}

func SetCustomTestObjectConvertor(convertor CustomTestObjectConvertor) {
	if customTestObjectConvertor == nil {
		customTestObjectConvertor = convertor
	} else {
		panic("CustomTestObjectConvertor has already been set")
	}
}

var customTestObjectConvertor CustomTestObjectConvertor = nil

func (src *TestObject) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*v2.TestObject)
	// Preserve ObjectMeta (name, namespace, labels, annotations, etc.)
	dst.ObjectMeta = src.ObjectMeta
	if err := ConvertTestObjectSpecToHub(&src.Spec, &dst.Spec); err != nil {
		return err
	}
	if err := ConvertTestObjectStatusToHub(&src.Status, &dst.Status); err != nil {
		return err
	}
	if customTestObjectConvertor != nil {
		return customTestObjectConvertor.ConvertToHub(src, dst)
	}
	return nil
}

func (dst *TestObject) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*v2.TestObject)
	// Preserve ObjectMeta (name, namespace, labels, annotations, etc.)
	dst.ObjectMeta = src.ObjectMeta
	if err := ConvertTestObjectSpecFromHub(&src.Spec, &dst.Spec); err != nil {
		return err
	}
	if err := ConvertTestObjectStatusFromHub(&src.Status, &dst.Status); err != nil {
		return err
	}
	if customTestObjectConvertor != nil {
		return customTestObjectConvertor.ConvertFromHub(src, dst)
	}
	return nil
}

func init() {
	SchemeBuilder.SchemeBuilder.Register(func(s *runtime.Scheme) error {
		if err := s.AddGeneratedConversionFunc((*TestObject)(nil), (*v2.TestObject)(nil), func(a, b interface{}, _ conversion1.Scope) error {
			return a.(*TestObject).ConvertTo(b.(conversion.Hub))
		}); err != nil {
			return err
		}
		return s.AddGeneratedConversionFunc((*v2.TestObject)(nil), (*TestObject)(nil), func(a, b interface{}, _ conversion1.Scope) error {
			return b.(*TestObject).ConvertFrom(a.(conversion.Hub))
		})
	})
}

func ConvertTestObjectSpecToHub(in *TestObjectSpec, out *v2.TestObjectSpec) error {
	if in == nil {
		return nil
	}
	out.F1 = in.F1
	if in.F2 == nil {
		out.F2 = nil
	} else {
		out.F2 = []string{}
	}
	for _, v := range in.F2 {
		out.F2 = append(out.F2, v)
	}
	if in.F3 == nil {
		out.F3 = nil
	} else {
		out.F3 = &v2.M1{}
		ConvertM1ToHub(in.F3, out.F3)
	}
	if in.F4 == nil {
		out.F4 = nil
	} else {
		if in.F4 == nil {
			out.F4 = nil
		} else {
			out.F4 = []*v2.M1{}
		}
		for _, v := range in.F4 {
			t := &v2.M1{}
			ConvertM1ToHub(v, t)
			out.F4 = append(out.F4, t)
		}
	}
	if in.F5 == nil {
		out.F5 = nil
	} else {
		out.F5 = make(map[string]*v2.M2, len(in.F5))
		for k, v := range in.F5 {
			if v == nil {
				out.F5[k] = nil
				continue
			}
			t := &v2.M2{}
			ConvertM2ToHub(v, t)
			out.F5[k] = t
		}
	}
	switch v := in.TestOneof.(type) {
	case *TestObjectSpec_OneofStr:
		out.TestOneof = &v2.TestObjectSpec_OneofStr{OneofStr: v.OneofStr}
	case *TestObjectSpec_OneofInt:
		out.TestOneof = &v2.TestObjectSpec_OneofInt{OneofInt: v.OneofInt}
	case *TestObjectSpec_OneofMsg:
		if v.OneofMsg != nil {
			t := &v2.M1{}
			ConvertM1ToHub(v.OneofMsg, t)
			out.TestOneof = &v2.TestObjectSpec_OneofMsg{OneofMsg: t}
		}
	}
	return nil
}

func ConvertTestObjectSpecFromHub(in *v2.TestObjectSpec, out *TestObjectSpec) error {
	if in == nil {
		return nil
	}
	out.F1 = in.F1
	if in.F2 == nil {
		out.F2 = nil
	} else {
		out.F2 = []string{}
	}
	for _, v := range in.F2 {
		out.F2 = append(out.F2, v)
	}
	if in.F3 == nil {
		out.F3 = nil
	} else {
		out.F3 = &M1{}
		ConvertM1FromHub(in.F3, out.F3)
	}
	if in.F4 == nil {
		out.F4 = nil
	} else {
		if in.F4 == nil {
			out.F4 = nil
		} else {
			out.F4 = []*M1{}
		}
		for _, v := range in.F4 {
			t := &M1{}
			ConvertM1FromHub(v, t)
			out.F4 = append(out.F4, t)
		}
	}
	if in.F5 == nil {
		out.F5 = nil
	} else {
		out.F5 = make(map[string]*M2, len(in.F5))
		for k, v := range in.F5 {
			if v == nil {
				out.F5[k] = nil
				continue
			}
			t := &M2{}
			ConvertM2FromHub(v, t)
			out.F5[k] = t
		}
	}
	switch v := in.TestOneof.(type) {
	case *v2.TestObjectSpec_OneofStr:
		out.TestOneof = &TestObjectSpec_OneofStr{OneofStr: v.OneofStr}
	case *v2.TestObjectSpec_OneofInt:
		out.TestOneof = &TestObjectSpec_OneofInt{OneofInt: v.OneofInt}
	case *v2.TestObjectSpec_OneofMsg:
		if v.OneofMsg != nil {
			t := &M1{}
			ConvertM1FromHub(v.OneofMsg, t)
			out.TestOneof = &TestObjectSpec_OneofMsg{OneofMsg: t}
		}
	}
	return nil
}

func ConvertTestObjectStatusToHub(in *TestObjectStatus, out *v2.TestObjectStatus) error {
	if in == nil {
		return nil
	}
	out.F1 = v2.E1(int32(in.F1))
	return nil
}

func ConvertTestObjectStatusFromHub(in *v2.TestObjectStatus, out *TestObjectStatus) error {
	if in == nil {
		return nil
	}
	out.F1 = E1(int32(in.F1))
	return nil
}
